### ISSUE TITLE
kpod load always try to pull image

### ISSUE THREAD

**Issue by gouyang** [projectatomic/libpod#107]
```
# ./bin/kpod load -i nginx.tar
Trying to pull docker.io/library/nginx:latest...
Getting image source signatures
Copying blob sha256:cec7521cdf36a6d4ad8f2e92e41e3ac1b6fa6e05be07fa53cc84a63503bc5700
 55.73 MB / 55.73 MB [======================================================] 0s
Copying blob sha256:350d50e58b6cb4cef21d4b4a3460e82c3221bad93b31175c2cc387f744f3b5c2
 51.27 MB / 51.27 MB [======================================================] 0s
Copying blob sha256:63c39cd4a7759b03edef476bba3d3cd9ab377b3a71cba12586a506c9e94427b5
 3.50 KB / 3.50 KB [========================================================] 0s
Copying config sha256:9e7424e5dbaeb9b28fea44d8c75b41ac6104989b49b2464b7cbbed16ceeccfc3
 5.70 KB / 5.70 KB [========================================================] 0s
Writing manifest to image destination
Storing signatures
# ./bin/kpod --version
kpod version 0.1
```

**Comment by rhatdan** [comment]
@umohnani8 ptal

**Comment by umohnani8** [comment]
So kpod load is not actually pulling the image again, it correctly loads the image from the tar file. The print statement is what is misleading. Basically what happens is, when it detects the transport is of docker-archive or oci-archive, it opens up the tar files and reads the image name from the manifest stored inside, which is what is printed in the statement "Trying to print ..." as the image name stored in the tar file is of the form "registry.com/image:tag".
I can fix this to print the file name instead when loading or we can follow what docker does and just print something like `Loaded image: docker.io/alpine:latest` at the end.
@rhatdan what do you think?

**Comment by rhatdan** [comment]
When in doubt do what Docker does.

**Comment by umohnani8** [comment]
@rhatdan @mheon please close this.

**Comment by rhatdan** [comment]
Fixed
