### ISSUE TITLE
podman ps prints Dead instead of Unknown

### ISSUE THREAD

**Issue by haircommander** [projectatomic/libpod#1074]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
>
> /kind feature

**Description**

podman ps prints a state of unknown (typically for a messed up state) as Dead, which doesn't accurately describe the situation.

**Steps to reproduce the issue:**

1. Look in cmd/podman/ps.go:521

2. See default is Dead, when the only remaining state is unknown

I don't know how to corrupt the state but I wanted to make sure this was intended behavior before pod_ps recreates it.

**Comment by mheon** [comment]
Unknown state should probably be an error condition - inside libpod, it's not considered a valid state, it's just there to ensure uninitialized ContainerState variables cause errors

**Comment by haircommander** [comment]
So then is there a situation we can even get to the point where ps will print dead?

**Comment by mheon** [comment]
With the current code, it's possible it could be printed - just retrieving the state of the container won't error. However, any operation that tries to alter the state of the container - start, stop, etc - will fail as the state is not known.

**Comment by rhatdan** [comment]
Bottom line, should we be printing "Dead" or "Unknown"?

**Comment by mheon** [comment]
I think "Unknown" or "Error" are good options. Error might be the most accurate.

**Comment by rhatdan** [comment]
Fine lets display Error now.

**Comment by haircommander** [comment]
I'll take care of it

**Comment by haircommander** [comment]
closed via #1083
