### ISSUE TITLE
podman run, with -a stdin: inconsistent exit status

### ISSUE THREAD

**Issue by edsantiago** [projectatomic/libpod#1078]
This one is weird:
```
# for i in $(seq 1 10); do podman run -a stdin --tty=false fedora false </dev/null;echo $?;done
493440fe37f79f3f3904d5d2535114e14e9ff1abb84b5d128a2ae316f5807c4e
1
6c1bf90b206e62fa57cab2f7a0ffca9865f85e7f62227672a5c1507bdab7d3a4
0
92d4adb28dfdc0b806091deed606cb4eac272fd6c81f9f1dbad408695331b43e
1
aacf93cb4d6a4dc7a9d040accd13fdfc0c7bb03da72cd1a07f33bfbb22a5249c
1
c50d8334c64f32ca4aa6abd69f9118e44bf42855ff3ea9b72525652ab3b6872a
1
d17aea655844c025c607e292a8a074e896887ca2b67ba5fd008974a8010557de
1
1d9842c3152631c6f6104f2138e4ad0029aa9b3d97049340b1d1dcb1ba4c2e06
1
c7092af7ec0cb79a5cb776efc26f1213146a603d6ae916f0d53ef7e433f88305
0
f7bc4f79f3674b96ba4507556b0cc66f0ab27e6cae503ac058160825ceeadfe7
0
292d7452fed468554a901c64dbe988c8fde07aa78d95760a7a3de5218c6a9ba2
1
```
I'm actually not sure what the correct behavior should be. FWIW docker is consistently 0.

podman-0.7.1-1.git802d4f2.fc28

**Comment by mheon** [comment]
I can only reproduce inside of the bash loop, it seems to always return 0 if not. Some sort of timing issue setting up attach?

**Comment by mheon** [comment]
You're right, though it seems less consistent without - 1 time out of 4 versus 1 out of 2.

Running with `--log-level=debug` gets me an exit code of 127 and a broken pipe error, which is probably a separate issue.

**Comment by rhatdan** [comment]
So the key factor here is the -a stdin
Running without this I dont see an issue.

**Comment by rhatdan** [comment]
PR Merged this should be fixed.
