### ISSUE TITLE
Podman won't start container with `-ti` and volume mount

### ISSUE THREAD

**Issue by vrutkovs** [projectatomic/libpod#1094]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**Description**

Podman hangs on starting a container with `-ti` and `-v`

**Steps to reproduce the issue:**

1. `sudo podman run --rm -v /:/host -ti registry.fedoraproject.org/fedora:27`

**Describe the results you received:**
No container created

**Describe the results you expected:**
Container, bash prompt in the container is displayed

**Additional information you deem important (e.g. issue happens only occasionally):**
Works when no volume is attached or either of `--tty` or `--interactive` is omitted

**Output of `podman version`:**
```
Version:       0.7.1
Go Version:    go1.10.3
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  MemFree: 262852608
  MemTotal: 16452083712
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 8
  hostname: morbo
  kernel: 4.17.5-200.fc28.x86_64
  os: linux
  uptime: 1h 15m 55.11s (Approximately 0.04 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions:
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 5
  RunRoot: /var/run/containers/storage
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical, Fedora Silverblue 28

**Comment by mheon** [comment]
Verified locally on F27.

Container is being created, and it seems like it is running. `podman run` is definitely hanging though.

**Comment by mheon** [comment]
Correction: I don't think it's actually hanging. Typing 'exit' does cause it to exit, and I can get the output of some bash commands.
Not seeing a prompt, though.

**Comment by mheon** [comment]
@vrutkovs Are you sure that's the right command line to reproduce? There's just a `-i` and no `-ti` - and this is expected behavior for attach without a terminal, Docker will act identically.

**Comment by vrutkovs** [comment]
@mheon oops, my fault. `-i` works fine (not allocating tty, so `exit` works) and `-t` works fine (no interactive mode). `-ti` won't create a container (at least its not visible in `podman ps -a`). Updated the description

On my other machine podman 0.6.4 on F28 works correctly - I'll check if updating to 0.7.1 breaks it
