### ISSUE TITLE
podman rmi: overzealous removal of referenced images

### ISSUE THREAD

**Issue by edsantiago** [projectatomic/libpod#1154]
This seems to be a variant of #992. Build an image:
```
# podman run --name c1 fedora true
# podman commit c1 img1
# podman rm c1
```
Build a second image based on the first:
```
# podman run --name c2 img1 true
# podman commit c2 img2
# podman rm c2
```
Run `podman images`, see img1 and img2 as expected. Delete the new (second) image, and the first one is gone too:
```
# podman rmi img2
# podman images
<where did img1 go?>
```
podman-0.7.3-1.git0791210.fc28

**Comment by vrothberg** [comment]
Fixed with #1174.
