### ISSUE TITLE
container init very slow

### ISSUE THREAD

**Issue by ypu** [projectatomic/libpod#1168]
/kind bug

**Description**
The container start with podman run init very slow. If we start the container with -d option and then use another command line to try to check it, the command will report "container has already been removed
". Here use podman ps as an example.

**Steps to reproduce the issue:**
Use a script to test it:

1.  Use podman run  -d to create a container
2.  Use podman ps -a to show it right after step 1 finished

**Describe the results you received:**
podman ps return with following err msg:
ERRO[0000] error joining network namespace for container 8136ca3055b42292f2b7d29ea053ee6cce06f592041db413cc559addfe8cc868 
container has already been removed

**Describe the results you expected:**
The container is list as expect

**Additional information you deem important (e.g. issue happens only occasionally):**
This is not can be triggered 100%. It may related with the test env. It made 4 test cases failed in the e2e test out of 358 test cases. And test it today with following script, it will be easier to triggered(8/10).

Here is the script:
```
# cat test.sh 
#! /bin/bash
podman run -d -name test docker.io/library/alpine:latest ls
sleep $1
podman ps -a
podman rm -fa
```
Test it with "./test.sh 0" for several times you will trigger it. And try "./test.sh 1" it will not shows up.

**Output of `podman version`:**

```
Version:       0.7.4-dev
Go Version:    go1.9.1
OS/Arch:       linux/amd64
```

**Comment by rhatdan** [comment]
@ypu So the container is being created, but the ps command reports that it is not, because the network has not been setup in time for the ps command?

If I specify a sleep time, then it works?

@mheon WDYT

**Comment by mheon** [comment]
So it's having issues finding the network namespace... Hm.

It's definitely https://github.com/projectatomic/libpod/blob/master/libpod/container_linux.go#L35-L36 triggering based on the ErrCtrRemoved we're returning.

**Comment by mheon** [comment]
This is properly strange, given that `podman run` should never return before the network namespace has fully established itself...

It could be a race between the cleanup process launched by `podman run -d` cleaning up the network ns, and `ps` trying to join it? But that might require the two to be inside the database at the same time which shouldn't be allowed...

**Comment by ypu** [comment]
Hi @rhatdan 
Not sure it is caused by the network setup. But the process for init the container should not finished when we try to use ps or logs to show it. And yes, if we sleep for 1s, then it works as expect.

**Comment by mheon** [comment]
This has to be environment related, I can't reproduce locally... @ypu Is this on AWS or similar?

**Comment by ypu** [comment]
Hi @mheon It is a rhel 8 kvm guest.

**Comment by rhatdan** [comment]
I would figure it is a conflict between `podman container cleanup` and `podman ps`.

**Comment by mheon** [comment]
By the time `container cleanup` exits, the netns should be completely gone from the database. If `ps` happens before this, it should find a good, clean netns and join it successfully. If `ps` happens after it, there is no namespace in the database, so it does not join a netns. They should not be able to happen concurrently due to database and container locking.

**Comment by baude** [comment]
@mheon with master on my laptop, what I am seeing is that it isn't ps throwing the error, but rm.

**Comment by mheon** [comment]
Same fundamental issue - locks should prevent this from happening.

**Comment by mheon** [comment]
This is happening before `rm` actually tries to remove the container, too - so it can't be a race around removal.

Somehow, we're retrieving a container from the database that has a valid network namespace path, but that path no longer exists on disk. That shouldn't be possible given that the state is saved back to the DB immediately after we delete the namespace, and both of those operations happen while we're holding the container lock...

Wait wait wait, figured this one. We don't hold the container lock when we initially retrieve a container - we're just fetching it from the database. So it's retrieval racing against netns removal...

We could potentially fix by swapping the order of the two operations, removing it from the database first and then tearing it down. Or we could grab the container lock as a part of retrieval... That might be safer.

**Comment by mheon** [comment]
Opened #1180 to fix

**Comment by mheon** [comment]
#1186 should have fixed
