### ISSUE TITLE
[Question] Podman architecture

### ISSUE THREAD

**Issue by elimisteve** [projectatomic/libpod#1175]
I am drawn to podman and rkt because they don't require a daemon like Docker does, and I believe that there shouldn't be a single point of failure that would kill all containers if it died itself.  (It doesn't help that I've had to restart the Docker daemon in order to solve problems with Docker; bye bye containers...)

Indeed, in @rhatdan's blog post at
https://www.projectatomic.io/blog/2018/02/reintroduction-podman/ , it reads:

> Podman doesn’t require a daemon to run containers and pods. This makes it a great asset for your container tools arsenal.

But I just learned that conmon is a daemon that runs the containers started by podman.

Therefore, is podman's architecture actually better than Docker's?  Is it even different?

rkt has systemd run the containers, which seems very smart and simple.  Doesn't this make rkt's architecture superior to podman's?

Thanks!

**Comment by mheon** [comment]
`conmon` isn't really a daemon in the same sense Docker is - it's an extremely small C binary that wraps each container we launch (one conmon per container), providing basic services such as attaching to the container, recording its exit code, and cleaning up resources after it exits. `conmon` only exists while the container it is managing is running - once it exits, `conmon` will also exit.

**Comment by elimisteve** [comment]
That sounds fantastic, but does that mean that `podman ps` somehow gets its info from talking to each individual `conmon` instance without needing a separate, persistent daemon?

**Comment by mheon** [comment]
`ps` actually doesn't need to talk directly to `conmon`. We use `runc` to get the status of a container, then if it has exited, it looks for a file that `conmon` creates giving information on how (exit code, whether it was killed due to an OOM condition, and the rough time it exited). No daemon involved.

**Comment by rhatdan** [comment]
I think this issue is satisfied, reopen if I am mistaken.
