### ISSUE TITLE
behavior change: podman mount: no longer idempotent

### ISSUE THREAD

**Issue by edsantiago** [projectatomic/libpod#1183]
Repeated `podman mounts` now stack on top of each other:
```
# podman run --name foo fedora bash -c 'echo abc >/bar'
! mount the fs twice
# mp=$(podman mount foo)
# mp2=$(podman mount foo)
! umount; I would expect to see the mountpoint empty
# podman umount foo
98a80af02c6454178a0eca372ea075249cf2d31db8c85fd0f48cc39805085708
# ls $mp
bar  bin  boot  dev  etc  home  lib  lib64  lost+found  media  mnt [...]
! second umount is the one that works
# podman umount foo
...cid again...
# ls $mp
<empty>
```
podman-0.7.4-4.git80612fb.fc28

Although this could be seen as unimportant, one could argue that `podman mount` should behave as "make sure the fs is mounted, and give me the mount point", not as "keep mounting it over and over so I the end user have to keep track of how many times I've invoked podman mount".

**Comment by mheon** [comment]
This was a deliberate change to allow concurrent use of mount (potentially
in different shells) without worrying about a single unmount wiping out all
ongoing mounts in use. I believe Dan added a force option to unmount to get
the former behavior still?

**Comment by edsantiago** [comment]
>to allow concurrent use of mount

OK, I can buy that. However there doesn't seem to be a `--force` anywhere: not in man page, or in --help, or in actual practice. Should I file an issue? Rename this one?

**Comment by rhatdan** [comment]
I have it in the library but not in the command.  I will open a PR to allow podman umount and buildah umount to --force the umount.

**Comment by rhatdan** [comment]
This should be in podman 8.1
