### ISSUE TITLE
Varlink creates a new runtime for each API operation

### ISSUE THREAD

**Issue by mheon** [projectatomic/libpod#1211]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**Description**

`podman varlink` can occasionally linger for a time accepting multiple requests, due to the default timeout. While it lingers, it services any new inbound API requests. Each new API request for every endpoint that is not `podman version` will initialize a new libpod Runtime. However, each Runtime will initialize a new `ocicni` CNI plugin manager, which will initiate inotify on a directory to search for new plugins. There is a max of 128 inotify sessions per user by default in Fedora, so if we receive 128 API requests before `podman varlink` times out and dies, we will begin throwing errors.

@jwhonce first noticed this in the Python tests.

Best solution is probably to initialize a single Runtime when `podman varlink` starts up and save it in the varlink API struct so that multiple API requests can share a runtime.

**Steps to reproduce the issue:**

1. Repeatedly barrage the varlink interface with requests without pause

**Describe the results you received:**

`{'parameters': {'reason': 'error configuring CNI network plugin: could not create new watcher too many open files'}, 'error': 'io.projectatomic.podman.RuntimeError'}`

**Describe the results you expected:**

No open files error

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by rhatdan** [comment]
@baude PTAL

**Comment by baude** [comment]
I'll look at it.

**Comment by baude** [comment]
can someone provide a way for me to test this more easily so I can verify the new implementation actually works?
