### ISSUE TITLE
--attach stdin: questionable behaviors

### ISSUE THREAD

**Issue by edsantiago** [projectatomic/libpod#1229]
Possibly related to #1078. This is a collection of various weird behaviors.

First: `-a stdin` blocks the terminal even if the command terminates:
```
# podman run -a stdin  fedora true
f91f1b2917567b0c604db277bb2658c7ff282c1007f235d7562e57524803b8ed
[hangs. ^D clears. I would expect podman to terminate. Note that adding --tty=false has no effect.]
```
(docker compatibility note: podman and docker behave identically here. It just strikes me as odd.)

Next: it's not really clear what `-a stdin` is doing even when it's running:
```
# echo potrzebie | podman run -a stdin --name foo  fedora cat
4bd681190e355c20d62f7015a4c144b942c8df13dc662e3c0daa791885ca8a06
# podman logs foo
[nothing]
```
(docker compatibility note: again, docker and podman behave identically).

Closely related: 
```
# podman run -a stdin --tty=true --name foo  fedora cat
146bcb93f7cff128ad88393e85d2d6a5f25ba07ceda87b503bf9975d705c1ff6
                                                                [cursor is here. I type "line 1<CR>line 2<CR>line 3<CR>^D^D". Yes, it requires two ^Ds. None of it is echoed.]
# podman logs foo

li
ne

1

line 1
li
n
e

2

line 2
l
i
n
e

3

line 3
```
(docker compatibility: here's where docker gets weird. With `--tty=true`, docker seems to be behaving the same as podman: the cursor sits idle, no prompt back. As soon as I type any character -- not just ^D, I mean any plain character like 'a' -- docker returns me to the command prompt, exit status 0, leaving the container running. It is not clear to me how this is sensible behavior but that's beyond the scope of this conversation).

Finally, the exit status seems to be that of the container command. I'm not sure what it should actually be, but for reference docker always exits 0 in this case:
```
# podman run -a stdin fedora false </dev/null;echo $?
55a58e36ba93f2ec16a535fd6a0093392556f24db3852bbe81f4f1dfba59dbba
1
```
podman-0.8.1-1.git6b4ab2a.fc28 with conmon-1.11.1-1.git1759204.fc28; Also podman-0.8.1-2.git6b4ab2a.fc27 with its built-in conman.

**Comment by mheon** [comment]
For the first two - we and Docker detach all streams that are not stdin when `-a stdin` is specified, but not any other `-a` attach flags. So the containers have no stdout or stderr, but do have an stdin so you can type to them. I'm not sure how this prevents `true` from exiting cleanly, though. In the TTY case, you're probably seeing the terminal echoing what you're typing - though, again, not sure why we're not exiting.

The last case, exit status - we intentionally added the exit status of the command there. If Docker doesn't have it and we want to be compatible, we can easily remove it - @rhatdan WDYT?

**Comment by mheon** [comment]
Should have been fixed by #1239

**Comment by mheon** [comment]
Actually, we never solved the exit status case - going to reopen

**Comment by rhatdan** [comment]
./bin/podman run --attach stdin fedora bash -c "exit 100"; echo $?
eaaf1cc3d5e2dfabab96cfb3bcb01c229302692677a2920025645bb00357aeec
100

This is correct behavior?  What is the problem.  If a container gets created successfully it always exits with the exit code of pid 1 in the container?

**Comment by mheon** [comment]
Alright, fair enough - I think I was misunderstanding what the bug was
