### ISSUE TITLE
Podman run --rm hangs after podman rm -af

### ISSUE THREAD

**Issue by mheon** [projectatomic/libpod#1245]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**Description**

`podman run` with the `--rm` flag will hang until killed after a `podman rm -af`

**Steps to reproduce the issue:**

1. `podman run -t -i --rm fedora bash`

2. In another terminal: `podman rm -af`

3. Switch back to the first terminal

**Describe the results you received:**

`
[root@6f3cea11ccee /]# exit

`

If you type, the terminal will echo it back, but otherwise the terminal will be useless until `podman run` is killed by control-c or similar.

**Describe the results you expected:**

Podman terminates and I get a fresh bash prompt back.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

Reproduced on master and 0.7.4 F28 package

**Comment by vrothberg** [comment]
I can reproduce with HEAD on openSUSE as well. I will look into it.

**Comment by vrothberg** [comment]
I found the issue. It's a deadlock (preparing a PR).
