### ISSUE TITLE
kpod rm doesn't remove container created by Buildah

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [projectatomic/libpod#144]
kpod rm fails when removing a container via it's name when the container is created by Buildah yet 'buildah rm' removes the container without an issue.

```
# CID=$(buildah from $TARGET)
# echo $CID
scratch-image-working-container
# buildah containers
CONTAINER ID  BUILDER  IMAGE ID     IMAGE NAME                       CONTAINER NAME
7b94f4b95eb4     *     87a2e5d48135 docker.io/library/scratch-image:latest scratch-image-working-container
# kpod rm $CID
no container with ID or name scratch-image-working-container found: no such container
unable to find container scratch-image-working-container: no container with ID or name scratch-image-working-container found: no such container
[root@docker test]# buildah rm $CID
7b94f4b95eb4a12a78f4e582bf1700e2a2c24f9978db634b1ac2dd34882afe97
```

**Comment by rhatdan** [comment]
This is because buildah is not working with libpod yet.  kpod rm is looking at the database for containers not just what is defined in container storage.   I guess we could extend kpod rm to look there as well, but I think we should get buildah to use the libpod code to register its containers.

**Comment by TomSweeneyRedHat** [comment]
This will become more of a problem once we get podman build calling buildah bud to create a container.

**Comment by rhatdan** [comment]
Well we have it now.  Can we get limited libpod support into buildah?  Can we just get buildah to register its containers with libpod?  @mheon WDYT?

**Comment by mheon** [comment]
@rhatdan I don't think we can rip just the database parts of libpod out easily, so just registering containers is probably a no-go. Using libpod for container creation should be fine, though there might be a bit of duplication of work around c/storage. I'll poke around the buildah APIs when I get some spare time to get an idea of how difficult integrating them would be.

**Comment by rhatdan** [comment]
This works in current podman.
