### ISSUE TITLE
conmon path should include alternates

### ISSUE THREAD

**Issue by baude** [projectatomic/libpod#167]
We should look for conmon in /usr/libexec/crio and /usr/local/libexec/crio.  I'm also wondering about the reasoning of having a crio directory housing a single binary.

**Comment by rhatdan** [comment]
I think there is a chance other content could be added their in the future.  What does CRI-O do currently?  Does it look in both places or only in the default?

**Comment by baude** [comment]
The problem is until we have packaging this remains sort of loose.  I don't expect our packages to install to /usr/local/libexec/crio which is where we currently look.  The latter question was really just a question.

**Comment by rhatdan** [comment]
Yes having a search path would be fine.

**Comment by baude** [comment]
done in #172
