### ISSUE TITLE
podman top panics under certain conditions

### ISSUE THREAD

**Issue by baude** [projectatomic/libpod#169]
Under certain conditions, podman top will panic with an index out of range error.  To replicate:

```
sudo podman run -dt -e HTTPD_VAR_RUN=/var/run/httpd -e HTTPD_MAIN_CONF_D_PATH=/etc/httpd/conf.d \
                    -e HTTPD_MAIN_CONF_PATH=/etc/httpd/conf \
                    -e HTTPD_CONTAINER_SCRIPTS_PATH=/usr/share/container-scripts/httpd/ \
                    registry.fedoraproject.org/f26/httpd /usr/bin/run-httpd
```
And then:
```[cloud-user@baude-fedora-cloud libpod]$ sudo podman top c2b65f476274
panic: runtime error: index out of range

goroutine 1 [running]:
main.psDataToPSParams(0xc42080e0d0, 0xb, 0xb, 0xc4203e0400, 0x8, 0x8, 0xc, 0x0, 0x0, 0x221d0de, ...)
	/home/cloud-user/src/github.com/projectatomic/libpod/_output/src/github.com/projectatomic/libpod/cmd/podman/top.go:151 +0x46e
main.topCmd(0xc420398160, 0x0, 0x0)
	/home/cloud-user/src/github.com/projectatomic/libpod/_output/src/github.com/projectatomic/libpod/cmd/podman/top.go:87 +0x3d9
github.com/projectatomic/libpod/vendor/github.com/urfave/cli.HandleAction(0x1ef65e0, 0x22cc488, 0xc420398160, 0x0, 0xc420248ba0)
	/home/cloud-user/src/github.com/projectatomic/libpod/_output/src/github.com/projectatomic/libpod/vendor/github.com/urfave/cli/app.go:501 +0xd2
github.com/projectatomic/libpod/vendor/github.com/urfave/cli.Command.Run(0x2218892, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2254845, 0x2c, 0x0, ...)
	/home/cloud-user/src/github.com/projectatomic/libpod/_output/src/github.com/projectatomic/libpod/vendor/github.com/urfave/cli/command.go:165 +0x505
github.com/projectatomic/libpod/vendor/github.com/urfave/cli.(*App).Run(0xc420762000, 0xc420010090, 0x3, 0x3, 0x0, 0x0)
	/home/cloud-user/src/github.com/projectatomic/libpod/_output/src/github.com/projectatomic/libpod/vendor/github.com/urfave/cli/app.go:259 +0x740
main.main()
	/home/cloud-user/src/github.com/projectatomic/libpod/_output/src/github.com/projectatomic/libpod/cmd/podman/main.go:155 +0x1112
```
It looks like the issue is around the default use of *cmd* in the ps options as removing that will allow it to work.

**Comment by baude** [comment]
The problem is that the CMD may contain space delimited data.  i.e. http -D This throws the splitting of that line of data off by index.

**Comment by baude** [comment]
@rhatdan @mheon @TomSweeneyRedHat I've been noodling on this for a while... I havent stumbled on a great way to fix this.  Do you guys have any ideas?

Basically the issue is that we run a ps command inside the container and perform a strings.Field on the output which splits the string into a []string based on whitespace.

Ideally ps could identify a field delimiter but that doesn't seem to be an option.  I messed with OFS and awk but I don't think it is reliable.  Moving 'cmd' output to the end of the output table could be an option, but it surely doesn't output then in the order the user asked for.  However, there are alias shortcuts in ps that include cmd so we could not always control it.

I also looked at the golang/psutil project and while good, it cannot support true ps options and would require a lot of wiring to make it work.

**Comment by mheon** [comment]
@baude It would require some refactoring, but we could use the headers of the ps output to determine where the columns are in the output line and use that to split instead - get the index of the start of each word in the header, and then split at those indexes

**Comment by baude** [comment]
@mheon I looked into this a bit ... The problem I am seeing is that the column data line up is not reliable either.  Consider the following:
```
01234567890123456789012345678901234567890
  UID   PID  PPID  C STIME TTY          TIME CMD
    0 13908 13898  0  2017 pts/0    00:01:44 top
```

Some line up to the header on the right, the left, and even in the middle!

**Comment by mheon** [comment]
@baude Oh that's just lovely. And I take it we can't guarantee that CMD will always be the last entry, either?

**Comment by baude** [comment]
Nope ... think we might need to deep dive this a little deeper and see what others do
