### ISSUE TITLE
Add optional --destination for podman push

### ISSUE THREAD

**Issue by baude** [projectatomic/libpod#198]
For podman push, we want the user to be able to optionally specify a destination for their image.  This prevents us from having to re-tag the image before pushing.  For example,

```
podman push --destination myregistry/foobar:latest foobar
```

**Comment by rhatdan** [comment]
WHy not have an optional second argument
`podman push foobar  myregistry/foobar:latest `
That feels more natural to me.
Or we just require it.

**Comment by TomSweeneyRedHat** [comment]
This is what Buildah does fwiw:

buildah push [options [...]] imageID [destination]

Looks like the man page is off a bit, the code in Buildah requires that both the source and destination be provided.

**Comment by baude** [comment]
optional second arg would be fine too!

**Comment by umohnani8** [comment]
podman push already does this. It takes 2 arguments, the image and the destination https://github.com/projectatomic/libpod/blob/master/docs/podman-push.1.md
```
➜  libpod git:(kpod_inspect) ✗ sudo podman push alpine docker://umohnani/myalpine:test
Getting image source signatures
Copying blob sha256:04a094fe844e055828cb2d64ead6bd3eb4257e7c7b5d1e2af0da89fa20472cf4
 4.20 MB / 4.20 MB [========================================================] 1s
Copying config sha256:e21c333399e0aeedfd70e8827c9fba3f8e9b170ef8a48a29945eb7702bf6aa5f
 1.48 KB / 1.48 KB [========================================================] 2s
Writing manifest to image destination
Storing signatures
```
Is this trying to do something else?

**Comment by baude** [comment]
@umohnani8 do you have to supply the transport  on the second arg ?

**Comment by umohnani8** [comment]
@baude yeah you do.

**Comment by rhatdan** [comment]
So we should close this issue.

**Comment by baude** [comment]
imho having to provide the transport (as required) is something we should fix.

**Comment by umohnani8** [comment]
So a --transport flag instead?

**Comment by baude** [comment]
no, just that the transport would be optional and docker:// would probably be the default if omitted.

**Comment by rhatdan** [comment]
@baude what syntax would you prefer.  No arg defaults to docker transport?

**Comment by baude** [comment]
yeah, seems right
