### ISSUE TITLE
Tutorial using sudo when already su

### ISSUE THREAD

**Issue by ipbabble** [projectatomic/libpod#207]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
>
> /kind feature

**Description**

**Steps to reproduce the issue:**

1.

2.

3.

**Describe the results you received:**

I see a lot of:

# sudo

In the tutorials. But # assumes you are already root so why do the 'sudo'?

**Describe the results you expected:**
Either 

$ sudo 

or s/sudo //

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
Your a git expert now, open a PR to change the `# to a $`
