### ISSUE TITLE
Use Conmon to hold ports open for CNI iptables portmapping

### ISSUE THREAD

**Issue by mheon** [projectatomic/libpod#210]
For CNI's IPTables-based portmapping to work properly, ports on the host must be opened and held by something that lives as long as the container. As libpod/podman do not guarantee a running daemon, the easiest way to do this is to have Conmon open ports on the host if requested, and close them when it exits

**Comment by rhatdan** [comment]
Could you open this issue in CRI-O, since we are trying to drop conmon from libpod.

**Comment by mheon** [comment]
I'll keep this open here to track, and open an issue against CRI-O to modify conmon to support opening and holding ports

**Comment by rhatdan** [comment]
If we move away from conmon, would this be easier with runc?

**Comment by mheon** [comment]
Yeah, we'd do it ourself, which should be easy enough - run through our port forwards and reserve them all on the host

**Comment by rhatdan** [comment]
@mheon @baude What is the current state of this?

**Comment by mheon** [comment]
The current plan is to open the ports in libpod and pass their file descriptors over to Conmon, being careful not to overlap them with FDs that actually need to be leaked into the container. I don't think any progress has been made on implementing that.

**Comment by rhatdan** [comment]
@baude made any progress?

**Comment by baude** [comment]
I wasn't aware this was assigned to me.  I think this is more suited to @giuseppe due to C skills.  What do you guys think?

**Comment by mheon** [comment]
@baude The new plan is to open the ports in libpod, and then leak the FDs into conmon and close them. Might still be a good job for someone with more conmon experience, because we have to do the leaking in such a way as to not interfere with the FDs we are already leaking to conmon.

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Comment by giuseppe** [comment]
sure I can take a look at it.  Could someone more familiar with this part point me to where the ports are currently open?

**Comment by baude** [comment]
I have to defer to @mheon ... this was his idea.

**Comment by mheon** [comment]
@giuseppe I don't think we are opening them anywhere yet - presumably we'd do it somewhere in the OCI create code as we're starting to set up Conmon.

**Comment by giuseppe** [comment]
PR here: https://github.com/projectatomic/libpod/pull/1100
