### ISSUE TITLE
kpod run -i -t <image> <command> has no stdout

### ISSUE THREAD

**Issue by baude** [projectatomic/libpod#25]
We are observing an error with kpod run where the the command output does not display anything to stdout **unless preceeded by bash -c**.  An example would be:
```
kpod run -i -t fedora cat /etc/fedora-release.
```
The results of the command **are** being sent to the container log.

If I remove the conditional around https://github.com/projectatomic/libpod/blob/master/conmon/conmon.c#L698, stdout begins to work again.  I suspect there is an issue with detecting what is a tty or not somewhere up from this but I wasn't able to put my finger on it yet.

Our call to conmon from kpod looks like:
```
DEBU[0001] running conmon: /usr/local/libexec/crio/conmon  args=[-c f5b28122ca709c28a1370b7bcd1d1d90fdd5f1c585dbb2e4e66b17a54b95d8ca -u f5b28122ca709c28a1370b7bcd1d1d90fdd5f1c585dbb2e4e66b17a54b95d8ca -r /usr/bin/runc -b /var/run/containers/storage/overlay-containers/f5b28122ca709c28a1370b7bcd1d1d90fdd5f1c585dbb2e4e66b17a54b95d8ca/userdata -p /var/run/containers/storage/overlay-containers/f5b28122ca709c28a1370b7bcd1d1d90fdd5f1c585dbb2e4e66b17a54b95d8ca/userdata/pidfile -l /var/lib/containers/storage/overlay-containers/f5b28122ca709c28a1370b7bcd1d1d90fdd5f1c585dbb2e4e66b17a54b95d8ca/userdata/ctr.log --exit-dir /var/run/libpod/exits --socket-dir-path /var/run/libpod/socket -t]
```

**Comment by baude** [comment]
@rhatdan @mrunalp PTAL and tag others

**Comment by rhatdan** [comment]
@runcom PTAL

**Comment by rhatdan** [comment]
@alexlarsson could you take a look at this.

**Comment by alexlarsson** [comment]
I'll have a look tomorrow

**Comment by alexlarsson** [comment]
I guess this might depend on some exact version thing, because it seems to work here:
```
[root@localhost alex]# kpod run -i -t registry.fedoraproject.org/fedora cat /etc/fedora-release
Fedora release 26 (Twenty Six)
```

This is kpod from 0e2fc603d9cbb21d72a548af087dd6b09a3bed1b, using runc-1.0.0-10.rc4.gitaea4f21.fc26.x86_64 on Fedora 26.

**Comment by rhatdan** [comment]
Run it multiple times.  I see it works for a couple of runs and then fails.

I see it lots of times running.

kpod run -i -t registry.fedoraproject.org/fedora printenv

**Comment by alexlarsson** [comment]
Its clearly a race of some sort. I got it to fail only once in 27 tries.

**Comment by rhatdan** [comment]
@baude claims that commenting out the line in conmon, fixes this?  Is this line necessary?
BTW I am doing it on a VM, and I get it to happen all the time.  Might have something to do with process speed.

**Comment by alexlarsson** [comment]
So, i did some tracing here, and the problem in the failing case is that the child is writing data to the terminal before kpod has attached to conmon. 
In the working case it looks like this:

```

conmon <ninfo>: addr{<ninfo>: addr{sun_family=AF_UNIX, sun_path=/tmp/conmon-term.7T198Y}
<ninfo>: about to waitpid: 20368
<ninfo>: terminal_accept_cb
<ninfo>: about to accept from console_socket_fd: 9
<ninfo>: about to recvfd from connfd: 12
<ninfo>: container PID: 20377
<ninfo>: attach sock path: /var/run/libpod/socket/4a6284fd38ac7c3077f60d99033b6ef6090c8ccbe626fb9acea71ed87c5bb814/attach
<ninfo>: addr{sun_family=AF_UNIX, sun_path=/var/run/libpod/socket/4a6284fd38ac7c3077f60d99033b6ef6090c8ccbe626fb9acea71ed87c5bb814/attach}
<ninfo>: ctl fifo path: /var/run/containers/storage/overlay-containers/4a6284fd38ac7c3077f60d99033b6ef6090c8ccbe626fb9acea71ed87c5bb814/userdata/ctl
<ninfo>: terminal_ctrl_fd: 13
<ninfo>: stdio_cb
<ninfo>: attach_cb
<ninfo>: Accepted connection 10
<ninfo>: stdio_cb
<ninfo>: Total bytes written: 51
<ninfo>: stdio_cb
<ninfo>: container 20377 exited with status 0
<nwarn>: stdio_input read failed Input/output error
```
Whereas in the failing case it looks like this:
```
<ninfo>: addr{sun_family=AF_UNIX, sun_path=/tmp/conmon-term.9Z0D9Y}
<ninfo>: about to waitpid: 20319
<ninfo>: terminal_accept_cb
<ninfo>: about to accept from console_socket_fd: 9
<ninfo>: about to recvfd from connfd: 12
<ninfo>: container PID: 20328
<ninfo>: attach sock path: /var/run/libpod/socket/f3e412dd721f4005de1be1cd1897bb2dea857bf7045a927f7736abdfef8be205/attach
<ninfo>: addr{sun_family=AF_UNIX, sun_path=/var/run/libpod/socket/f3e412dd721f4005de1be1cd1897bb2dea857bf7045a927f7736abdfef8be205/attach}
<ninfo>: ctl fifo path: /var/run/containers/storage/overlay-containers/f3e412dd721f4005de1be1cd1897bb2dea857bf7045a927f7736abdfef8be205/userdata/ctl
<ninfo>: terminal_ctrl_fd: 13
<ninfo>: stdio_cb
<ninfo>: stdio_cb
<ninfo>: Total bytes written: 51
<ninfo>: attach_cb
<ninfo>: Accepted connection 10
<ninfo>: stdio_cb
<ninfo>: container 20328 exited with status 0
<nwarn>: stdio_input read failed Input/output error
``` 

See how in the failing case we handle stdio_cb and write 51 bytes *before* we got attach_cb from kpod. This means that in read_stdio() when we read the data from the child, conn_sock_writable is false (and conn_sock is invalid), so we can't send the data to kpod.

Honestly, i'm not sure how to fix this though. I don't think we can always wait for kpod to attach before we start handling input from the child, because there is no real guarantee that something will always connect.

**Comment by alexlarsson** [comment]
The fix for the kpod case is probably to accept the socket directly in setup_console_socket(), or at least before starting the container. However, i'm not sure that is correct when being used for kubernetes, because there is no guarantee that anything will attach to the container immediately.

Maybe you can add a switch to conmon that triggers this behaviour, and use that from kpod?

**Comment by alexlarsson** [comment]
Basically i think you can add to end of setup_attach_socket() something like:

```
if (opt_block_on_attach)
 attach_cb(atattach_socket_fd,  G_IO_IN, NULL);
```

**Comment by baude** [comment]
Fixed upstream
