### ISSUE TITLE
Add ability to load libpod default configuration from file

### ISSUE THREAD

**Issue by mheon** [projectatomic/libpod#270]
Similar to c/image and c/storage, libpod should load its default configuration in from a file, to allow unified system-wide container runtime settings to be honored by default

**Comment by surajssd** [comment]
@mheon how are these configs fed right now?

**Comment by mheon** [comment]
Right now we respect the default containers/storage and containers/image configs. The storage config lives at `/etc/containers/storage.conf` (I'm not entirely sure where the image configs reside, never needed to tweak them). Changes to `storage.conf` will affect all users of containers/storage on the system (libpod, CRI-O, etc) unless they are explicitly set to ignore them via command line flag.

**Comment by rhatdan** [comment]
/etc/containers/registries,conf /etc/containers/policy.json /etc/containers/registries.d are all used in containers/image.

**Comment by mheon** [comment]
Will be fixed by #430

**Comment by mheon** [comment]
Support was merged
