### ISSUE TITLE
Potential symlink/directory traversal issue in user ID extraction

### ISSUE THREAD

**Issue by nalind** [projectatomic/libpod#29]
kpod inherited some configured-user to uid/gid resolution logic from buildah, so it also has [this problem](https://github.com/projectatomic/buildah/issues/66), which we're trying to solve in https://github.com/projectatomic/buildah/pull/313.  We'll need a similar change here.

**Comment by mheon** [comment]
We've imported the code buildah uses for resolving UIDs and GIDs and are using it in libpod, which should resolve this issue
