### ISSUE TITLE
Podman build does not respect log-level flag

### ISSUE THREAD

**Issue by mheon** [projectatomic/libpod#294]
Podman build does not pass the `--log-level` global flag into Buildah, so debugging output will only occur for Podman itself.

I haven't checked, but I suspect other global flags are also not respected

**Comment by TomSweeneyRedHat** [comment]
Most if not all the global flags are indeed not respected.  I'll work on that, nice catch @mheon.

**Comment by TomSweeneyRedHat** [comment]
@mheon --log-level=debug should work now in podman.  However that's the only error level logging that Buildah does atm, so anything else passed in is a no-op.  I also turned on the flags that are common between both.  That was in #312.  More to be added.

**Comment by mheon** [comment]
@TomSweeneyRedHat I think we can say #312 fixed this issue. Closing.
