### ISSUE TITLE
Simple differences between podman inspect and docker inspect of container images.

### ISSUE THREAD

**Issue by rhatdan** [projectatomic/libpod#305]
Comparing inspect between

docker pull registry.fedoraproject.org/f26/httpd:latest
podman pull registry.fedoraproject.org/f26/httpd:latest

docker inspect registry.fedoraproject.org/f26/httpd:latest

podman inspect registry.fedoraproject.org/f26/httpd:latest

Quickly what I see.

Podman refers to "ID", while Docker refers to "Id", can we change this?  or is this buried in container storage.  Also Docker id has a sha256: prepended on it, while Podman does not?

The Config Section on Podman is referred to as ContainerConfig on Docker, I think this should change.

Docker shows a "hostname:" field equivalent to the shortname of the image, while podman does not show this field at all?  Not sure this matters, since I don't know what a hostname for a container image means anyways.

Command field in podman is

        "Cmd": [
            "/usr/bin/run-httpd"
        ],

Docker:

            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) USER [1001]"
            ],

Docker has an entrypoint field, while podman does not, Entrypoint=null?

**Comment by mheon** [comment]
@rhatdan Can we close this? I think #306 fixed it

**Comment by rhatdan** [comment]
I will close this but we still have the issue where docker inspect accepts multiple containers and returns a list. Where podman only takes one.  @baude is working on this I believe.

**Comment by mheon** [comment]
I think that merged as well?

**Comment by mheon** [comment]
It did, 6ce70a33c5825c0f4d2afae7643db95e8b7d46f1
