### ISSUE TITLE
podman does not support entrypoint 

### ISSUE THREAD

**Issue by ipbabble** [projectatomic/libpod#321]
**Steps to reproduce the issue:**

This is just an example 

1. buildah config --entrypoint "ls -al /etc" my-container 

2. buildah inspect  my-container   // it's set correctly

3. buildah commit my-container ls 

4. podman run -it ls  

**Describe the results you received:**
You get an error asking you for a command 

**Describe the results you expected:**
The long listing of a directory /etc  

**Additional information you deem important (e.g. issue happens only occasionally):**

The entries in entrypoint are set correctly. Docker has no problem using them in the image.

**Output of `podman version`:**

```
podman version 0.1
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Fedroa 27, physical

**Comment by rhatdan** [comment]
@baude Can you get this fixed before we announce on Monday?

**Comment by baude** [comment]
yes working on it now

**Comment by baude** [comment]
This is verified to be working now.
