### ISSUE TITLE
ENH: return imageid from 'podman pull'

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [projectatomic/libpod#329]
/kind feature

**Description**
When issuing the command "podman pull fedora" it would be nice if the last line of the output was the imageid.  If the -q parameter was supplied, then only the imageId would be returned.  This would allow one do something like:

imageId=$(podman pull -q fedora)
podman run $imageid /bin/bash

and have the imageid in the variable rather than having to look it up via the ps command.  It would make scripting easier.

**Steps to reproduce the issue:**

1.  'podman pull alpine'

**Describe the results you received:**
The progress from the pull command was shown as expected, but no imageid was displayed on the last line.

**Describe the results you expected:**

Not expected, but wanted, I'd like the imageid to be printed at the end.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
# podman version
Version:       
Go Version:    go1.9.3
OS/Arch:       linux/amd64

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

VM running an updated Fedora 27 and the podman test kit.

**Comment by rhatdan** [comment]
Seems like a reasonable idea.

**Comment by mheon** [comment]
I want to do a general overhaul of our image handling. This can probably happen as part of it.

**Comment by TomSweeneyRedHat** [comment]
Will do, want to give it a quick spin first and haven't gotten there yet.

**Comment by TomSweeneyRedHat** [comment]
@baude, looks great, tyvm!
