### ISSUE TITLE
Basic Build & Run Fails

### ISSUE THREAD

**Issue by fatherlinux** [projectatomic/libpod#334]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
>
> /kind feature

**Description**

I cloned the repository and built per the instructions in install.md. The build seemed to complete with no errors, but a basic pull or run fails. It complains about parsing the registries.conf file, so I took a look but can't see anything obviously wrong with the syntax. I am getting the following error

**Steps to reproduce the issue:**

1. Clone libpod repository from the latest tag

2. Follow install.md instructions, build, install

3. Run simple commands

**Describe the results you received:**

podman pull fedora
error pulling image "fedora": error getting default registries to try: unable to parse the registries.conf file and the image name 'fedora' is incomplete.: Near line 9 (last key parsed ''): Bare keys cannot contain ':'.

**Describe the results you expected:**

podman pull fedora

Then, the image pulls down and is saved

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:       0.2
Go Version:    go1.8.3
Git Commit:    "e814936915d28286fa88f1211bc354687a358a7c"
Built:         Thu Feb 15 05:25:24 2018
OS/Arch:       linux/amd64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running on RHEL 7.4
cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.4 (Maipo)
[root@rhel7 etc]# uname -a
Linux rhel7.dc2.crunchtools.com 3.10.0-693.el7.x86_64 #1 SMP Thu Jul 6 19:56:57 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by TomSweeneyRedHat** [comment]
@fatherlinux quick guess is your system is missing atomic-registries.  Can you check with "rpm -qa | grep atomic-registries" and if missing dnf/yum install it?  I'll go poke at the docs to make sure it's there.

**Comment by fatherlinux** [comment]
@TomSweeneyRedHat I just checked and you nailed it. I had a version installed, but it was old (1.18), when I updated to 1.20, everything started working! I submitted a pull request to add atomic-registries to the list of requirements for RHEL/CentOS/Fedora. I am not quite sure if there is a different package for Ubuntu/Debian, etc....

**Comment by TomSweeneyRedHat** [comment]
#335 addresses Fedora issue

**Comment by fatherlinux** [comment]
Closing as fixed :-)

**Comment by praveenkumar** [comment]
@TomSweeneyRedHat  Today I am also trying out `podman` on fedora-28 and encounter the same issue. I do have `atomic-registries` not able to figure out what's wrong. I am happy to provide any other information which is need to debug it. Not sure should I reopen this or create a new issue.

```
$ sudo dnf --enablerepo updates-testing install podman
$ podman version
Version:       0.5.2
Go Version:    go1.10.2
OS/Arch:       linux/amd64

$ sudo podman pull fedora
error pulling image "fedora": unable to pull fedora: error getting default registries to try: Near line 9 (last key parsed ''): Bare keys cannot contain ':'.
```

**Comment by TomSweeneyRedHat** [comment]
@praveenkumar I'm going to open a new issue under libpod/podman.  Thanks for the problem report.  If by chance you don't get a link to that issue in the next 15 minutes or so, please ping me or reply here.
