### ISSUE TITLE
tty size incorrect

### ISSUE THREAD

**Issue by cgwalters** [projectatomic/libpod#351]
This is *probably* a `crio/conmon` bug but on:

```
● fedora-27:fedora/27/x86_64/workstation
                   Version: 27.74 (2018-02-15 16:36:40)
```

```
$  rpm -q docker podman
docker-1.13.1-44.git584d391.fc27.x86_64
podman-0.2-3.git3d0100b.fc27.x86_64
$ for x in docker podman; do echo -n "${x} tty width:" && ${x} run --rm -ti registry.fedoraproject.org/fedora:27 /bin/sh -c 'sleep 2 && tput cols'; done
docker tty width:211
podman tty width:80
$
```

I was trying to switch my dev container to podman, and it's not respecting the outer tty size.

**Comment by mheon** [comment]
That does indeed sound like a conmon bug. Any chance you can try and reproduce with `crictl`/`crio`

**Comment by TomasTomecek** [comment]
For me, this is even worse: weechat refuses to start because tty size is not set at all:
```
$ sudo podman run ... bash
[root@3c02c4569466 /]# stty size
0 0
```

On my host:
```
$ stty size
42 173
```

Now I run the podman container once again and weechat works when the tty size is set:
```
$ sudo podman run ... bash
[root@1659a0a88e9d /]# stty columns 173
[root@1659a0a88e9d /]# stty rows 42
[root@1659a0a88e9d /]# stty size
42 173
```

**Comment by rhatdan** [comment]
@mrunalp @alexlarsson PTAL

**Comment by rhatdan** [comment]
I don't know or understand this code but it looks like it tries to do something with window size in 
static gboolean ctrl_cb(int fd, G_GNUC_UNUSED GIOCondition condition, G_GNUC_UNUSED gpointer user_data)

```
		ret = ioctl(masterfd_stdout, TIOCGWINSZ, &ws);
		ninfo("Existing size: %d %d", ws.ws_row, ws.ws_col);
		ws.ws_row = height;
		ws.ws_col = width;
		ret = ioctl(masterfd_stdout, TIOCSWINSZ, &ws);
		if (ret == -1) {
			nwarn("Failed to set process pty terminal size");
		}
```

But looking at the logs this code never gets called.
