### ISSUE TITLE
podman save: generates corrupt image on stdout

### ISSUE THREAD

**Issue by edsantiago** [projectatomic/libpod#352]
`podman save`, in its default mode of writing to stdout, seems to create a corrupt image.

Good:

    # podman run --name mycontainer docker.io/stackbrew/centos  /bin/true
    # podman commit mycontainer myimage
    ... (ok)
    # podman save -o /tmp/myimage.1.tar myimage
    ... (ok)
    # podman rm mycontainer; podman rmi myimage
    # podman load </tmp/myimage.1.tar
    ... success

Bad:

    # podman save myimage >/tmp/myimage.2.tar
    # podman rmi myimage
    # podman load </tmp/myimage.2.tar
    Failed
    error pulling "dir:/dev/stdin": error pulling image from "dir:/dev/stdin": Error determining manifest MIME type for dir:/dev/stdin: open /dev/stdin/manifest.json: not a directory

    # ls -l /tmp/myimage.?.tar
    -rw-r--r--. 1 root root 204870656 Feb 19 15:22 /tmp/myimage.1.tar
    -rw-r--r--. 1 root root 204870656 Feb 19 15:23 /tmp/myimage.2.tar
    # file /tmp/myimage.?.tar
    /tmp/myimage.1.tar: POSIX tar archive
    /tmp/myimage.2.tar: data
    # cmp /tmp/myimage.?.tar
    /tmp/myimage.1.tar /tmp/myimage.2.tar differ: byte 199, line 1

Suggested starting point: the corrupt image includes strings that look like progress meters:

    24.82 MB  / 195.38 MB [=======>--------------

**Comment by mheon** [comment]
@umohnani8 Any chance you can take a look at this?

**Comment by umohnani8** [comment]
@mheon will look into this.

**Comment by umohnani8** [comment]
@mheon @TomSweeneyRedHat could you please close this. Fixed in #362
