### ISSUE TITLE
podman images: implement --all

### ISSUE THREAD

**Issue by edsantiago** [projectatomic/libpod#354]
It looks like `podman images` lists all images by default, including intermediates. docker, OTOH, only lists intermediates when given `--all`. Neither approach is right or wrong, this is simply a design decision. I am filing this issue to ensure that the decision is an active, deliberate one.

**Comment by rhatdan** [comment]
I think we should follow what Docker does.

**Comment by baude** [comment]
we will ... but cannot until buildah produces cached images

**Comment by baude** [comment]
fwiw https://github.com/projectatomic/libpod/blob/master/cmd/podman/images.go#L128

**Comment by mheon** [comment]
It's not in the manpage, so we're consistent at least.

Though maybe we should add a "-a" private option (not visible in the manpage or help text) that does nothing, to make sure people who habitually types `images -a` aren't broken?

**Comment by rhatdan** [comment]
Yes lets add the flag. And change our defaults to match docker.

**Comment by baude** [comment]
@rhatdan my thinking was to add this when buildah supports cached images and we actually can differentiate between --all and not all . is that cool?

**Comment by rhatdan** [comment]
@edsantiago PTAL at PR.

**Comment by rhatdan** [comment]
podman images --all now works.
