### ISSUE TITLE
podman rm: implement --volumes

### ISSUE THREAD

**Issue by edsantiago** [projectatomic/libpod#356]
[placeholder]

**Comment by rhatdan** [comment]
@umohnani8 PTAL

**Comment by rhatdan** [comment]
Basically we want content in the volumes removed.

**Comment by rhatdan** [comment]
Well I don't this there is anything mounted.  I believe this is only for builtin volumes, not for the case where you bind mounted something on disk into the container.

In our case right now, if you run a image that was built with a VOLUME flag in the Dockerfile, we create content.
If I do a podman rm --volumes, the content should be removed.

**Comment by umohnani8** [comment]
@rhatdan I am creating the image volumes within the container directory, basically if the dockerfile has a VOLUME /myvol and we want to bind mount it, the volume is created in /var/lib/containers/storage/container-id/volumes/myvol. So when the container is removed, the volume is automatically removed.
We had a discussion that there is no point putting it outside the container state directory as we don't support sharing of volumes.
I am a bit confused, where would these volumes that we want to remove with podman rm --volumes live?

**Comment by rhatdan** [comment]
@umohnani8 Ok, so then this is not an issue and not something we need to support.

**Comment by rhatdan** [comment]
@edsantiago We don't need or supprot podman rm --volume.
