### ISSUE TITLE
podman inspect: output is not a JSON array

### ISSUE THREAD

**Issue by edsantiago** [projectatomic/libpod#360]
`podman-inspect(1)` claims:

    By default, this will render all results in a JSON array.

Methinks this is copy-pasted from `docker-inspect`. That statement is true for docker, but not for podman.

If podman wishes to be consistent with docker-inspect, it will need to: (1) accept multiple arguments on the command line; (2) output a JSON array instead of a single element; and (3) change the example output in the man page.

If podman is to retain its current behavior, it should change the wording on the man page to reflect that it does not output an array.

**Comment by mheon** [comment]
If `docker inspect` accepts multiple containers for inspection at the command line, we'll want to duplicate that behavior for `podman inspect`

**Comment by rhatdan** [comment]
I agree, @baude can  you fix this?

**Comment by baude** [comment]
Ill add it to the queue

**Comment by baude** [comment]
it looks like podman inspect only accepts one arg at a time ... so i will fix the output and inputs.

**Comment by mheon** [comment]
Fixed by #371
