### ISSUE TITLE
[v.low] podman stop: --timeout option: allow abbreviating as --time

### ISSUE THREAD

**Issue by edsantiago** [projectatomic/libpod#366]
`docker stop` accepts a `--time` option; in podman, the option is `--timeout`. I think the latter is a better name, but it might be a good idea to enable `--time` as an alias for command-line compatibility with docker.

**Comment by mheon** [comment]
Agree, this is a nice and simple change for compatibility

**Comment by mheon** [comment]
Closed via #375
