### ISSUE TITLE
podman run: exit status 126/127 seem to be reversed in sense

### ISSUE THREAD

**Issue by edsantiago** [projectatomic/libpod#367]
`podman-run(1)` asserts that it will exit with 126 if command cannot be _invoked_ (e.g. permission denied), and 127 if the command cannot be _found_. I believe the test sense in `cmd/podman/run.go:83-86` is reversed:

    # podman run --rm registry.access.redhat.com/rhel7/rhel:latest /etc;echo $?
    container create failed: container_linux.go:348: starting container process caused "exec: \"/etc\": permission denied"
    : internal libpod error
    127

    # podman run --rm registry.access.redhat.com/rhel7/rhel:latest nonexistent-command;echo $?
    container create failed: container_linux.go:348: starting container process caused "exec: \"nonexistent-command\": executable file not found in $PATH"
    : internal libpod error
    126

**Comment by mheon** [comment]
This sounds like https://github.com/projectatomic/libpod/blob/5529143877778ef8bcdd05179e279bb7d662b431/cmd/podman/run.go#L81-L87

Either the error codes are switched in the code or in the manpages. We should fix whichever breaks with Docker convention.

**Comment by edsantiago** [comment]
My bad: I meant to include this: docker is the opposite. That is: I believe the podman documentation should remain as-is, and the code itself should be adjusted.

As long as I'm blabbing, though: I'm not sure if grepping for "permission denied" is the best way to implement this. There may be other reasons why a command cannot be invoked. I can't think of any offhand, though, and don't have a better suggestion atm.

**Comment by mheon** [comment]
I tend to agree that manually manipulating the error seems like a bad idea. It might be a good idea to expose more explicit error codes of of libpod so we have a better idea of what's going on

**Comment by mheon** [comment]
I'm also far from certain ctr.Init() erroring means the command did not exist, given that Init failure could also be issues with storage and mounts.

**Comment by rhatdan** [comment]
The convention that is followed in the chroot command.
```
info chroot
...
     125 if ‘chroot’ itself fails
     126 if COMMAND is found but cannot be invoked
     127 if COMMAND cannot be found
     the exit status of COMMAND otherwise
```

**Comment by rhatdan** [comment]
Permission denied should be 126

SO they are reversed.

**Comment by baude** [comment]
Fixed!
