### ISSUE TITLE
'kpod login' doesn't allow certificates to be in non-default directory

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [projectatomic/libpod#38]
There's no way to  specify a directory to 'kpod login' to have it grab the ssl certificates from.  It always looks for the certificates at:

/etc/docker/certs.d/{registry location}

The --certs-dir and probably --tls-verify parameters used for push/pull should be added to 'kpod login' so a non-default directory can be used if desired.

**Comment by umohnani8** [comment]
If we agree to do this, I can work on this.
@rhatdan PTAL

**Comment by rhatdan** [comment]
I would like to see this be a fail over case /etc/containers/certs.d, /etc/docker/certs.d and then override-able by the kpod login command.

**Comment by rhatdan** [comment]
Should this be something specified in the /etc/containers/registries.conf file?
@baude WDYT?

**Comment by rhatdan** [comment]
@TomSweeneyRedHat @umohnani8 Is this fixed now?

**Comment by umohnani8** [comment]
@rhatdan will be fixed once #303 is in.
