### ISSUE TITLE
podman tag: assume 'latest' if source is untagged name

### ISSUE THREAD

**Issue by edsantiago** [projectatomic/libpod#384]
For compatibility with docker, and just general user-friendliness, `podman tag` should assume `:latest` if given a source image with no tag:

    # podman pull docker.io/stackbrew/centos:7
    ....
    # podman tag docker.io/stackbrew/centos:7 foo
    # podman tag foo bar
    unable to locate image "foo": image not known

Specifying `foo:latest` works as expected, as does specifying the SHA.

On a closely related note, `podman-tag(1)` is incomplete. I'll file a new issue for that.

**Comment by baude** [comment]
I agree with this, i will take this one up
