### ISSUE TITLE
Bug: Should not override user-specified /etc/resolv.conf mount

### ISSUE THREAD

**Issue by mheon** [projectatomic/libpod#388]
As of right now, we unconditionally mount a few things (`/etc/resolv.conf`, `/etc/hostname`, `/etc/hosts`) into the container. People may want to override these. We should not mount these if the user has already specified something to be mounted at that destination.

**Comment by rhatdan** [comment]
Yes I agree.

**Comment by baude** [comment]
Ill take this one ... what are your thoughts on this ... if /etc is mounted or specifically just /etc/resolv.conf, /etc/hostname, /etc/hosts

**Comment by mheon** [comment]
For now let's say only if the specific mount is being requested, no need to override for all of `/etc/`

**Comment by rhatdan** [comment]
Yes I think that is all docker does.  If the user specifies the specific mount, we should not mount over it.
