### ISSUE TITLE
podman run: exit status is 0 after signal

### ISSUE THREAD

**Issue by edsantiago** [projectatomic/libpod#389]
`podman run` passes through an error exit, but not a signal exit:

    a# podman run --rm --name foo registry.access.redhat.com/rhel7/rhel:latest sleep 60

In another shell:

    b# podman kill foo
    <sha>

Back to first shell:

    a# echo $?
    0

Expected: 137

**Comment by edsantiago** [comment]
Ping, just checking in: this behavior is still present in podman-0.3.5-1.gitdb6bf9e.fc27.x86_64

**Comment by mheon** [comment]
This one is really confusing to me - we should be picking up the exit code of the container and setting our exit code to it regardless of what kills the container

**Comment by mheon** [comment]
This may have something to do with https://github.com/kubernetes-incubator/cri-o/pull/1513 - will need to check if it's fixed after we get a Conmon with that patch.

**Comment by giuseppe** [comment]
yes this should be fixed by: https://github.com/kubernetes-incubator/cri-o/pull/1513

**Comment by mheon** [comment]
Need to verify that we have this conmon in all our builds

**Comment by mheon** [comment]
This should be fixed now
