### ISSUE TITLE
New default directory for credential files for kpod login?

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [projectatomic/libpod#39]
Currently the default location for credential files for 'kpod login' is /etc/docker/certs.d/{registryname}.  It would be nice to be able to change that to '/etc/oci/certs.d/{registryname}' or some other location that @rhatdan thinks is appropriate.  The one caveat is we need to make sure that a private registry will run OK with this location in play.

**Comment by rhatdan** [comment]
/etc/containers/certs.d/...
Works for me.

**Comment by surajssd** [comment]
I would like to work on this issue if nobody else is?

**Comment by TomSweeneyRedHat** [comment]
@umohnani8 Did you pick this one up yet?  If not, then it's all yours @surajssd Thanks!

**Comment by rhatdan** [comment]
@surajssd Assign your self and go for it.

**Comment by umohnani8** [comment]
Is this the same as issue #38? The description looks very alike.

**Comment by TomSweeneyRedHat** [comment]
@umohnani8 #38 and #39 are closely related but different.  This one is meant to set a default directory for certificates that kpod and in specific 'kpod login' will use.  #38 is to add a --certs-dir parameter to kpod login so a non-default directory could be specified if so desired.

**Comment by rhatdan** [comment]
@umohnani8 @TomSweeneyRedHat Is this fixed now?

**Comment by TomSweeneyRedHat** [comment]
Not yet, @umohnani8 has a WIP for the docs and a few code tweaks in Buildah.

**Comment by umohnani8** [comment]
Will be fixed when #303 is in.

**Comment by umohnani8** [comment]
@rhatdan @TomSweeneyRedHat please close this issue.

**Comment by mheon** [comment]
Fixed by #303
