### ISSUE TITLE
Bug: Cannot resolve DNS from inside the container

### ISSUE THREAD

**Issue by Drakonis** [projectatomic/libpod#390]
Currently containers are incapable of resolving DNS, including --net=host when creating the container enables DNS resolving.

**Comment by baude** [comment]
can you try something like:

```
iptables -t filter -I FORWARD -i cni0 ! -o cni0 -j ACCEPT
```

and see if that fixes things?

**Comment by Drakonis** [comment]
yeah it is working now.

**Comment by mheon** [comment]
Sounds like iptables-allow in CNI would fix this (https://github.com/containernetworking/plugins/pull/75). Hopefully we can speed that along.

**Comment by vrothberg** [comment]
Is it possible to add a (temporary) workaround to `podman` until the issue is resolved in CNI?

**Comment by mheon** [comment]
The original plan was to wait until the CNI PR merged, but that's been stalled upstream for a long time now. Given that, I think we need to include a local fix until it merges.

**Comment by rhatdan** [comment]
@baude Can you add a temporary hack, and we can remove once new version of CNI happens.

**Comment by baude** [comment]
yup! its in now

**Comment by vrothberg** [comment]
I just tested it in openSUSE and it works like a charm. Thanks a lot, @baude!

**Comment by rhatdan** [comment]
Nice,  Any chance you could write a blog about podman on OpenSuse?

**Comment by vrothberg** [comment]
> Nice, Any chance you could write a blog about podman on OpenSuse?

@rhatdan Sure, with pleasure. I can send you a draft via email if you want to have a look. I should find some time this week to write it.

**Comment by rhatdan** [comment]
Looking forward to it.
