### ISSUE TITLE
I/O: podman run --interactive not detecting close on stdin?

### ISSUE THREAD

**Issue by edsantiago** [projectatomic/libpod#392]
`podman run --interactive`, with stdin as tty, seems to work as expected. With stdin as a pipe or redirected, hangs:

    # echo hi | podman run --interactive --rm registry.access.redhat.com/rhel7/rhel:latest cat
    hi
    hi
    (hang forever)

    # podman run --interactive --rm registry.access.redhat.com/rhel7/rhel:latest cat </etc/hostname
    myhostname
    myhostname
    (hangs)

Note the duplicate duplication.

Expected: single line of output, followed by exit 0.

I'm really sorry for not providing better details on this. I'm running late and need to head out.

**Comment by edsantiago** [comment]
ping, any love on this? Still seeing it on podman-0.3.3-2.gitb47fc0d.fc27

**Comment by mheon** [comment]
This sounds like an issue with our stdin copy code. This code was originally from CRI-O and is still basically identical, so we should try and verify if it's a problem over there with `crictl exec`, and if it is maybe they'll be nice enough to fix it for us.

**Comment by rhatdan** [comment]
@mrunalp WDYT

**Comment by edsantiago** [comment]
Confirmed fixed in podman-0.4.1-1.gitb51d327.fc27
