### ISSUE TITLE
Podman - Detect when net.ipv4.ip_forward=0 and warn user

### ISSUE THREAD

**Issue by BenHall** [projectatomic/libpod#399]
If net.ipv4.ip_forward is not enabled then the Podman/libpod containers will not be able to reach the internet with the packets being dropped.

In my case (clean Ubuntu environment), it was due to net.ipv4.ip_forward not being enabled.

My solution was to enable forwarding which allowed the containers to reach the internet.

```
echo 'net.ipv4.ip_forward=1' >> /etc/sysctl.conf
sudo sysctl -p
```

I think Podman should warn users when ip_forward hasn't been set.

**Comment by mheon** [comment]
This is easy enough to detect (it's exposed as `/proc/sys/net/ipv4/ip_forward`). I wonder if we shouldn't upstream this to the OCICNI package or CNI plugins themselves, as this is something that would also affect Kubernetes.

**Comment by rhatdan** [comment]
Lets get a quick fix into podman, and then work on getting it into OCICNI.  That way we can help our users who hit this issue.

**Comment by baude** [comment]
@BenHall  you must use a cni configuration file that has isGateway: true in it.  that will automatically flip the forwarding bit for you.  We ship a default cni configuration file in podman.

**Comment by BenHall** [comment]
@baude Is that currently the default?

**Comment by baude** [comment]
yes, in the podman default configuration -> https://github.com/projectatomic/libpod/blob/master/cni/87-podman-bridge.conflist#L8

**Comment by BenHall** [comment]
@baude Just checked the environment. The file was in the correct location.

**Comment by baude** [comment]
@BenHall i tested on xenail ... what are you on?

**Comment by BenHall** [comment]
@baude Ubuntu 16.04.2 LTS. I'll double check the environment without the IP forward flag

**Comment by rhatdan** [comment]
Are we just saying that this works on Xenail?
