### ISSUE TITLE
podman exec: exit status is always 0

### ISSUE THREAD

**Issue by edsantiago** [projectatomic/libpod#402]
(at least for all cases I've tested):

    # podman run -d --name foo registry.access.redhat.com/rhel7/rhel:latest sleep 5m

    # podman exec foo /bin/false
    # echo $?
    0

    # podman exec foo /bin/bash -c 'exit 32'
    # echo $?
    0

docker propagates the exit status. However, neither docker-exec(1) nor podman-exec(1) actually specify a behavior.

**Comment by mheon** [comment]
This should be fixed in #394 whenever I finally get that working - we were ignoring all error returns from the exec'd process.

**Comment by edsantiago** [comment]
Thank you! Sorry to have missed that in my search.

**Comment by mheon** [comment]
It's fine, I never opened an issue when I noticed the problem, and the PR is mainly fixing other things.

**Comment by mheon** [comment]
Partial fix landed in #412 - we now exit with an error code, but the code is not the one from the exec'd program.

**Comment by rhatdan** [comment]
Any movement on this?

**Comment by rhatdan** [comment]
@mheon Is this an issue with runc or something else?

**Comment by mheon** [comment]
@rhatdan Naw, this is just our code - I think the `podman` side of things isn't setting the right error code

**Comment by rhatdan** [comment]
@haircommander PTAL
