### ISSUE TITLE
Interface different with Docker

### ISSUE THREAD

**Issue by fatherlinux** [projectatomic/libpod#431]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
>
> /kind feature

**Description**
I "think" this is a bug, because the two behave differently. Basically, with a build, podman requires a "." at the end of the command, where docker doesn't even when pulling a remote Dockerfile...

**Steps to reproduce the issue:**

1. podman build -t fedora-netcat-dockerfile-docker https://raw.githubusercontent.com/fatherlinux/two-pizza-team/master/Dockerfile-fedora-experiement
error prepping temporary context directory: Error processing tar file(exit status 1): unexpected EOF
error running the buildah build-using-dockerfile (bud) command: exit status 1

2.

3.

**Describe the results you received:**

When the above command is run, this is the output.

pizza-team/master/Dockerfile-fedora-experiment
error prepping temporary context directory: Error processing tar file(exit status 1): unexpected EOF
error running the buildah build-using-dockerfile (bud) command: exit status 1

To make it work, you have to run the following command:

podman build -t fedora-netcat-dockerfile-podman -f https://raw.githubusercontent.com/fatherlinux/two-pizza-team/master/Dockerfile-fedora-experiment .

You have to add the -f, and the "." at the end of the command

**Describe the results you expected:**

I would expect complete compatibility, where literally, I just change the "docker" to "podman" - also, one final note. The same command doesn't work with docker....

docker build -t fedora-netcat-dockerfile-docker -f https://raw.githubusercontent.com/fatherlinux/two-pizza-team/master/Dockerfile-fedora-experiment .
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /root/https:: no such file or directory

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:       0.2.2
Go Version:    go1.9.4
OS/Arch:       linux/amd64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Fedora VM running on KVM in RHEL 7.4

**Comment by mheon** [comment]
This sounds like a buildah issue... @TomSweeneyRedHat @nalind PTAL

**Comment by TomSweeneyRedHat** [comment]
Closing this one and have move it to Buildah's issue list at: https://github.com/projectatomic/buildah/issues/504
