### ISSUE TITLE
Different in tagging between Docker and Podman

### ISSUE THREAD

**Issue by fatherlinux** [projectatomic/libpod#432]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
>
> /kind feature

**Description**

Basically, if you look at the output, you will notice that podman automatically adds a docker.io Registry Server to the URL when building, even when the short name is specified.

**Steps to reproduce the issue:**

1. podman build -t fedora-netcat-dockerfile-podman -f https://raw.githubusercontent.com/fatherlinux/two-pizza-team/master/Dockerfile-fedora-experiment .

2.

3.

**Describe the results you received:**

[root@fedora ~]# docker images
REPOSITORY                        TAG                 IMAGE ID            CREATED             SIZE
fedora-netcat-dockerfile-docker   latest              21ee72aa7dc8        3 hours ago         440 MB
docker.io/fedora                  26                  1ba39c7494fb        3 months ago        231 MB
docker.io/fedora                  latest              422dc563ca32        3 months ago        252 MB
docker.io/fedora                  25                  9cffd21a45e3        3 months ago        232 MB
docker.io/fedora                  24                  971e0f0a8b71        5 months ago        204 MB
docker.io/openshift/origin-pod    v3.6.0              fb52c4c8f037        7 months ago        213 MB
docker.io/fedora/tools            latest              7a6d1eb41075        12 months ago       1.7 GB
docker.io/nate/dockviz            latest              4ea294712533        14 months ago       7.33 MB
[root@fedora ~]# podman images
REPOSITORY                                          TAG      IMAGE ID       CREATED          SIZE
docker.io/library/fedora                            25       9cffd21a45e3   3 months ago     243MB
docker.io/library/fedora                            26       1ba39c7494fb   3 months ago     242MB
docker.io/library/fedora                            latest   422dc563ca32   3 months ago     263MB
docker.io/library/fedora                            24       971e0f0a8b71   5 months ago     214MB
<none>                                              <none    15b0d13a541d   10 minutes ago   452MB
docker.io/library/fedora-netcat-dockerfile-podman   latest   361d8952a695   2 minutes ago    452MB

**Describe the results you expected:**

[root@fedora ~]# docker images
REPOSITORY                        TAG                 IMAGE ID            CREATED             SIZE
fedora-netcat-dockerfile-docker   latest              21ee72aa7dc8        3 hours ago         440 MB
docker.io/fedora                  26                  1ba39c7494fb        3 months ago        231 MB
docker.io/fedora                  latest              422dc563ca32        3 months ago        252 MB
docker.io/fedora                  25                  9cffd21a45e3        3 months ago        232 MB
docker.io/fedora                  24                  971e0f0a8b71        5 months ago        204 MB
docker.io/openshift/origin-pod    v3.6.0              fb52c4c8f037        7 months ago        213 MB
docker.io/fedora/tools            latest              7a6d1eb41075        12 months ago       1.7 GB
docker.io/nate/dockviz            latest              4ea294712533        14 months ago       7.33 MB
[root@fedora ~]# podman images
REPOSITORY                                          TAG      IMAGE ID       CREATED          SIZE
docker.io/library/fedora                            25       9cffd21a45e3   3 months ago     243MB
docker.io/library/fedora                            26       1ba39c7494fb   3 months ago     242MB
docker.io/library/fedora                            latest   422dc563ca32   3 months ago     263MB
docker.io/library/fedora                            24       971e0f0a8b71   5 months ago     214MB
<none>                                              <none    15b0d13a541d   10 minutes ago   452MB
fedora-netcat-dockerfile-podman   latest   361d8952a695   2 minutes ago    452MB

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:       0.2.2
Go Version:    go1.9.4
OS/Arch:       linux/amd64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Fedora 27 VM running in KVM on RHEL 7.4

**Comment by mheon** [comment]
@baude Is this what we were talking about earlier, with c/storage assuming docker.io for all shortnames?

**Comment by baude** [comment]
yeah I  hate this ... even with docker you can create foo:latest with out prepends.

**Comment by baude** [comment]
Dup of #639 Will solve on that one
