### ISSUE TITLE
podman logs -f: does not detect container stop or rm

### ISSUE THREAD

**Issue by edsantiago** [projectatomic/libpod#435]
`logs -f` happily continues forever even after container stops and is removed:
```
# podman run -d --name foo fedora bash -c 'sleep 30;date;sleep 10;date;echo goodbye'
ed5408187e0e75a484c38f862af01fc0d07a735cb7286640d7e9b879b6bccc86
# podman logs -f foo
Thu Mar 1 22:42:02 UTC 2018
Thu Mar 1 22:42:12 UTC 2018
goodbye
```
And that's all folks: I do not get a prompt back until I ^C. Even if I `podman rm foo` in another window.

FWIW `docker logs` exits immediately after the goodbye.

Whether or not this is fixed to agree with docker, I think a man page update is in order: the behavior should be explicitly documented, whichever way it goes.

**Comment by mheon** [comment]
I think Docker has an advantage over us here, having a server that you stream logs from instead of us just grabbing a file descriptor...

I suppose with `-f` specified we could spawn a goroutine doing a `podman wait` and, if the container exits, exit ourselves?

**Comment by mheon** [comment]
Wait, that only detects container exit, not removal. We don't have an easy way to wait for removal. Ack.

**Comment by baude** [comment]
i think i last messed with this code, ill peek at it too.
