### ISSUE TITLE
podman ps -a reports 'no exit file for container found' after manually killing conmon process

### ISSUE THREAD

**Issue by sunilcio** [projectatomic/libpod#439]
Manually killing `conmon` process of a container results in below error for `podman ps -a`
```
unable to create output: no exit file for container a9aa67f40bc6c... found: timed out waiting for the condition
```
Scenario and how to reproduce:

### TEST 01: First kill the process inside container - no issue observed

- Run a container:
```
# podman run -d alpine sleep 1000 &
# ab60719c7d0af70a355d14bc558faa1032d89987ea94afa0055b6d8af597e57b

# podman ps
CONTAINER ID   IMAGE    COMMAND      CREATED AT                      STATUS              PORTS   NAMES
ab60719c7d0a   alpine   sleep 1000   2018-03-02 11:16:00 -0500 EST   Up 16 seconds ago           cocky_hawking
```

- First kill `sleep` process inside container. This will also result in `conmon` process exiting, all ok:
```
F   UID   PID  PPID PRI  NI    VSZ   RSS WCHAN  STAT TTY        TIME COMMAND
1     0   942     1  20   0  86080  1848 SyS_po Ssl  ?          0:00 /usr/libexec/crio/conmon -c ab60719c7d0af70a355d14bc558faa1032d89987ea94afa0055b6d8af597e57b -u ab60719c7d0af70a355d14bc558faa1032d89987ea94afa0055b6d8af597e57b -r /usr/bin/runc -b /var/lib/containers/storage/overlay-containers/ab60719c7d0af70a355d14bc558faa1032d89987ea94afa0055b6d8af597e57b/userdata -p /var/run/containers/storage/overlay-containers/ab60719c7d0af70a355d14bc558faa1032d89987ea94afa0055b6d8af597e57b/userdata/pidfile -l /var/lib/containers/storage/overlay-containers/ab60719c7d0af70a355d14bc558faa1032d89987ea94afa0055b6d8af597e57b/userdata/ctr.log --exit-dir /var/run/libpod/exits --socket-dir-path /var/run/libpod/socket
4     0   963   942  20   0   1512     4 hrtime Ss   ?          0:00 sleep 1000

# kill -9 963
```

- No issue observed and `podman ps -a` works correctly:
```
# podman ps -a
CONTAINER ID   IMAGE    COMMAND      CREATED AT                      STATUS                          PORTS   NAMES
ab60719c7d0a   alpine   sleep 1000   2018-03-02 11:16:00 -0500 EST   Exited (0) About a minute ago           cocky_hawking
```

### TEST 02: First kill `conmon` process & then process inside container - issue observed

- Run a container:
```
# podman run -d alpine sleep 1000 &
# a9aa67f40bc6cf158850110b8c7f6cf74a00c654bc6d4c9fca16ddcef8a02dc3
```

- First kill `conmon` process of container. 
```
F   UID   PID  PPID PRI  NI    VSZ   RSS WCHAN  STAT TTY        TIME COMMAND
1     0  1103     1  20   0  86080  1916 SyS_po Ssl  ?          0:00 /usr/libexec/crio/conmon -c a9aa67f40bc6cf158850110b8c7f6cf74a00c654bc6d4c9fca16ddcef8a02dc3 -u a9aa67f40bc6cf158850110b8c7f6cf74a00c654bc6d4c9fca16ddcef8a02dc3 -r /usr/bin/runc -b /var/lib/containers/storage/overlay-containers/a9aa67f40bc6cf158850110b8c7f6cf74a00c654bc6d4c9fca16ddcef8a02dc3/userdata -p /var/run/containers/storage/overlay-containers/a9aa67f40bc6cf158850110b8c7f6cf74a00c654bc6d4c9fca16ddcef8a02dc3/userdata/pidfile -l /var/lib/containers/storage/overlay-containers/a9aa67f40bc6cf158850110b8c7f6cf74a00c654bc6d4c9fca16ddcef8a02dc3/userdata/ctr.log --exit-dir /var/run/libpod/exits --socket-dir-path /var/run/libpod/socket
4     0  1113  1103  20   0   1512     4 hrtime Ss   ?          0:00 sleep 1000

# kill -9 1103
```

- After killing `conmon` process first, `PID 1` will become `PPID` of `sleep` process which is running inside container. I guess this is expected:
```
F   UID   PID  PPID PRI  NI    VSZ   RSS WCHAN  STAT TTY        TIME COMMAND
4     0  1113     1  20   0   1512     4 hrtime Ss   ?          0:00 sleep 1000
```

- Now `systemd` with `PID 1` have become parent of `sleep` which was running inside container. Running `podman ps -a` still shows container up but there is no `conmon` process:
```
# podman ps -a
CONTAINER ID   IMAGE    COMMAND      CREATED AT                      STATUS                     PORTS   NAMES
a9aa67f40bc6   alpine   sleep 1000   2018-03-02 11:18:55 -0500 EST   Up 56 seconds ago                  youthful_wilson
ab60719c7d0a   alpine   sleep 1000   2018-03-02 11:16:00 -0500 EST   Exited (0) 3 minutes ago           cocky_hawking
```

- Now kill `sleep` process and `podman ps -a` shows below error. It states `no exit file for container found`
```
# kill -9 1103

# podman ps -a
unable to create output: no exit file for container a9aa67f40bc6cf158850110b8c7f6cf74a00c654bc6d4c9fca16ddcef8a02dc3 found: timed out waiting for the condition
```

- After this state if I run any more containers, I can check running containers with `podman ps` but running `podman ps -a` results in above error becuase of how first container was killed.
- Trying to remove the first container with container ID also does not work.
```
# podman rm a9aa67f40bc6cf158850110b8c7f6cf74a00c654bc6d4c9fca16ddcef8a02dc3
failed to delete container a9aa67f40bc6cf158850110b8c7f6cf74a00c654bc6d4c9fca16ddcef8a02dc3: no exit file for container a9aa67f40bc6cf158850110b8c7f6cf74a00c654bc6d4c9fca16ddcef8a02dc3 found: timed out waiting for the condition
```

**Comment by sunilcio** [comment]
Forgot to specify version while opening issue.
```
# podman version
Version:       0.2.3-dev
Go Version:    go1.9.4
Git Commit:    "656840c9924b0348c7e939b4215f14c5b076842f"
Built:         Fri Mar  2 09:47:14 2018
OS/Arch:       linux/amd64
```

**Comment by mheon** [comment]
This sounds like a `conmon` issue.

Conmon, if it is killed by a signal we can catch (ex. SIGTERM), should first kill the container it's managing, create the exit file, and then exit. This guarantees that the container is actually dead, and we are in a sane state.

To ensure containers in a bad state can actually be removed, we have added code in master to better handle missing exit files. The container process running would still interfere with removal, but that should be fixable by manually killing the runc in question

**Comment by mheon** [comment]
There's a PR open against `conmon` upstream with a partial fix - https://github.com/kubernetes-incubator/cri-o/pull/1409

This, combined with the existing fix we added here, should be enough to handle most cases where `conmon` is manually killed. We can't do anything about SIGKILL, though, as SIGKILL cannot be caught.

**Comment by mheon** [comment]
Partial fix in `conmon` merged, though we won't take advantage of it until we move to using `conmon` for cleanup.

**Comment by rhatdan** [comment]
@mheon Any progress on this?  Or does this still need @giuseppe to implement this in conmon?

**Comment by mheon** [comment]
@rhatdan I think this is fixed in conmon

**Comment by rhatdan** [comment]
@mheon so we have not done the second part yet for podman to tell conmon to cleanup?

**Comment by mheon** [comment]
@rhatdan Yes. I'm not sure if we are really in a better place for this bug once that lands, though.

If conmon is manually killed in such a way that it can't create the exit file and can't clean up, we end up in a bad place, especially in the CRI-O case where we only determine exit files based on inotify for the exit file. I don't think there's a way around that.

**Comment by rhatdan** [comment]
I am fine with keeping this open, but I would like to get moving on implementing this hook.

**Comment by rhatdan** [comment]
@giuseppe could you look into this?

**Comment by vrothberg** [comment]
@rhatdan I wonder if it makes sense to break conmon out into a dedicated project. I know there are pros and cons, but it would make packaging much easier and maybe even testing as we could make tests depend on CRI-O and Podman.

**Comment by rhatdan** [comment]
Yes we have talked about moving conmon out into its own package.

**Comment by rhatdan** [comment]
We now have podman container cleanup.
