### ISSUE TITLE
podman commit: verbosier than docker

### ISSUE THREAD

**Issue by edsantiago** [projectatomic/libpod#450]
The (undocumented) output of `podman commit` differs from the (undocumented) output of docker:

    # docker run --name foo fedora date
    Mon Mar  5 21:52:20 UTC 2018
    # docker commit foo bar
    sha256:5b738753cc3e63780447d7c84459dd01fa9ec07f41c56ff19d0336bfb81346b7

podman emits progress bars but no easily-machine-readable hash:

    # podman run --name foo fedora date
    Mon Mar  5 22:00:44 UTC 2018
    [root@esm-f27-1 ~]# podman commit foo bar
    Getting image source signatures
    Copying blob sha256:7eb19aa639a66cdce2d7a3a2f00ba80406555cb48263d25a9018548ce09d4f94
     250.98 MB / 250.98 MB [====================================================] 2s
    Copying config sha256:cd7acbd59347491f08f6fb6e515d959b3ea6e460ca2c0cb4c12a6dd24e5a95ec
     409 B / 409 B [============================================================] 0s
    Writing manifest to image destination
    Storing signatures

docker-autotest (unsafely!) assumes that `commit` will output a hash and nothing else.

This behavior is not documented anywhere in dockerland but I do see posts where others describe and rely on this docker behavior. Sorry.

**Comment by mheon** [comment]
I think having a `-q` flag that would only output a hash would be useful for machine parsing, like docker-autotest wants to.

We should probably display the ID of the image regardless, too.

**Comment by rhatdan** [comment]
I agree.  I thought we already fixed something like this.

**Comment by TomSweeneyRedHat** [comment]
We started returning the imageId from the 'podman pull' command relatively recently.  I'm not sure we've done similar for other commands though.  It would be nice to have to have for commit, run too if I could get greedy.  I don't think Docker returns it in run though.

**Comment by baude** [comment]
run already does this, i will take a look at commit .. shouldnt the default behaviour then be to be quiet and then we would have a verbose to see the extra status. assigning to me

**Comment by mheon** [comment]
@baude I'm fine with --verbose and quiet being default

**Comment by edsantiago** [comment]
To followup on my stdout/stderr suggestion: see #362 in which @umohnani8 made progress meters output to stderr. Whether or not you add --verbose, I think it might be a good idea to emit these progress meters to stderr as well. For consistency, and also because it would still allow capture of the cid in stderr:

    # CID=$(podman commit --verbose foo bar)
    ...blah blah blah I'm working hard, ...
    # echo $CID
    this-is-your-sha
