### ISSUE TITLE
(ultra-minor): podman top output is not tabular

### ISSUE THREAD

**Issue by edsantiago** [projectatomic/libpod#458]
This is a nit. I am not requesting that it be fixed, and I even suggest that you close-WONTFIX immediately upon reading it. I am filing because some day someone might possibly encounter this and check if it's a known issue.

`podman top` emits `ps` output unaltered. This differs from docker, which reformats it using its standard table output. The most significant difference is that the column headers in docker are left-aligned, while podman (consistent with ps) has mixed alignment:

    # docker top foo
    UID    PID     PPID      C        STIME       TTY         TIME        CMD
    root   14245   14230     0        15:59       ?           00:00:00    sleep 5m

    # podman top foo
      UID   PID  PPID  C STIME TTY          TIME CMD
        0 19212 19203  0 20:59 ?        00:00:00 sleep 5m

(note that UID, PID, PPID, and TIME headings are left-aligned for docker, right-aligned for podman).

Docker also outputs much more whitespace between columns; I've taken the liberty of trimming for readability. That's the second difference in output.

Again: this is as minor as you can get. docker-autotest has code that relies on headings being left-aligned, but I doubt that any other code anywhere would care.

**Comment by mheon** [comment]
@baude The easiest in my mind would be to vendor + use docker's output code, I think? They clearly have some solution for it

**Comment by rhatdan** [comment]
@baude Any progress on this or should we close this as a WONTFIX?

**Comment by baude** [comment]
I think we should close it; I know it is a sore point with some folks but the leap is going to be large to fix it.

**Comment by TomSweeneyRedHat** [comment]
Anything wrong with marking it an enhancement and seeing is someone grabs it at some point?

**Comment by rhatdan** [comment]
That would be fine, but I hate that the number of issues just climbs and gets crufty. I wish there was a separate place in github to list enhancements.

**Comment by vrothberg** [comment]
> @mheon can you think of a way i can deal with this given that tabular output is hard to do with this command given that some columns can have spaces (like cmd)

I've been looking into Moby's code and the basic assumption is that the last column is always CMD, so we can "merge" all exceeding columns into one. A fix for libpod is here: https://github.com/projectatomic/libpod/pull/939
