### ISSUE TITLE
podman load doesn't work on xz compressed files

### ISSUE THREAD

**Issue by vrothberg** [projectatomic/libpod#472]
/kind bug

**Description**

`podman load` on xz compressed files fails.

**Steps to reproduce the issue:**
1. Perform a `podman load` on an xz compressed file.

**Describe the results you received:**
`open container-feeder471485113/manifest.json: not a directory`

There are two things related to this issue. The first one is that the fall-through logic in PullImage is masking the actual bug, which made debugging the issue harder. I guess we could improve the situation by being more verbose when falling through the various transports. The second one is that `containers/image` currently doesn't support xz compressed images and compressed layers. @cyphar has fixed the latter with https://github.com/containers/image/pull/427. I tested https://github.com/containers/image/pull/427 locally with libpod by updating the vendored image library, which required just a minor tweak in the code to reflect the new tar API.

**Describe the results you expected:**
A successful image load.

**Comment by mheon** [comment]
Sounds like a nice, easy improvement. We can track the PR in c/image and merge once that's ready.

**Comment by baude** [comment]
@umohnani8 you did the gz, how hard would it be to add this ?

**Comment by umohnani8** [comment]
@baude If it is fixed in containers/image, just a matter of vendoring it in.

**Comment by cyphar** [comment]
I've implemented it in containers/image#427. Just going through review now.

**Comment by rhatdan** [comment]
@umohnani8 Could you follow up on this one?

**Comment by umohnani8** [comment]
@rhatdan ACK. Will keep an eye on the containers/image PR for this.

**Comment by umohnani8** [comment]
Fixed in #1137.
