### ISSUE TITLE
Packaging change: Separate Conmon package for Podman on Fedora

### ISSUE THREAD

**Issue by mheon** [projectatomic/libpod#475]
As of right now, we share `conmon` with CRI-O via the `conmon` subpackage of CRI-O. However, we've been running into issues recently with podman specific fixes for `conmon` landing in CRI-O master. The CRI-O maintainers are reluctant to backport these to the release branches the package (and `conmon` subpackage) are built from, as the new features landing in `conmon` could break CRI-O releases.

We are presently blocked on introducing several new features as `conmon` is too old to include them (and, given `conmon` is a very limited executable with almost no versioning, we cannot reliably determine what features the host `conmon` supports). A `conmon` package with support may not become available until the F29 timeframe (would be tied to CRI-O 1.10, which depending on Kube 1.10's schedule may not make F28). This is a very long time to hold off on adding critical features like container restart and proper cleanup.

Given this, we'd like to bundle `conmon` in our `podman` in Fedora to hold a more up-to-date version of `conmon` while not risking breakage in CRI-O. This will allow us to control what version of `conmon` we ship against and guarantee the features we need are available. This will hopefully be a temporary measure until development slows down and the two can unify again.

Specific steps to fix:
- Check out CRI-O repository's master and build `conmon` when building `podman`. Include this `conmon` in the package, installing to `/usr/libexec/podman/conmon` (alongside the normal `conmon` located at `/usr/libexec/crio/conmon`)
- Install the libpod config file `libpod.conf` located in the root of the repository to `/usr/share/containers` so we can specify which conmon path we want to use via configuration file once installed

**Comment by rhatdan** [comment]
We need to update the README with this information.

**Comment by baude** [comment]
Done

**Comment by vrothberg** [comment]
Once Podman has a requirement on a specific commit or range of commit, would you mention that in the release notes? Currently, there is no specific podman-conmon package for openSUSE and I'd like to defer it unless really necessary.

**Comment by mheon** [comment]
@vrothberg Sure, we should probably keep track of that in the readme.

**Comment by vrothberg** [comment]
@mheon Thanks :-)
