### ISSUE TITLE
podman run: implement --restart

### ISSUE THREAD

**Issue by edsantiago** [projectatomic/libpod#486]
Filing as separate issue because I don't want to clutter #482

Once restart is working, should the `--restart` option to `podman run` be implemented? If so, implement & document. If not, it might be wise to update podman-run(1) and remove the "incompatible with any restart policy other than none" statement from the --rm documentation.

**Comment by rhatdan** [comment]
We will not be implementing podman run --restart since we don't have a daemon. This should be done via systemd, if you want it.

**Comment by mheon** [comment]
Should change the manpages for run to remove things mentioning it, then

**Comment by mheon** [comment]
Manpages updated, closing
