### ISSUE TITLE
[docker compatibility] podman inspect: no leading slash in Name

### ISSUE THREAD

**Issue by edsantiago** [projectatomic/libpod#490]
Filing purely for archival purposes and as an FYI for future users who encounter this quirk. I do not expect any action, and indeed hope none is taken other than closing this as KTHXBYE.

`docker inspect` has an obnoxious long-standing [issue](https://github.com/moby/moby/issues/29997) in which the `Name` field has a leading slash:

    # docker run --name foo fedora date
    # docker inspect --format '{{.Name}}' foo
    /foo

This appears to have elicited much grumbling over the years, and probably countless workarounds in production code, but it appears unlikely to be fixed in docker.

podman has no such bug, and no such historical baggage, and—I hope—no reason to actually emulate docker's behavior.

**Comment by rhatdan** [comment]
SGTM

**Comment by mheon** [comment]
I think this is basically a WONTFIX
