### ISSUE TITLE
podman images-related actions: inconsistent handling of sha256

### ISSUE THREAD

**Issue by edsantiago** [projectatomic/libpod#493]
Although `podman images --no-trunc` outputs a hash with a `sha256:` prefix, no image commands (that I've found) accept those identifiers:

    # podman images --no-trunc
    REPOSITORY                                   TAG      IMAGE ID ...
    docker.io/library/fedora                     latest   sha256:9110ae7f579f35ee0c3....
    # ID=$(podman images --no-trunc|grep /fedora|awk '{print $3}')
    # podman inspect $ID
    []
    error getting image "sha256:9110ae7f579f35e...": error parsing reference to image "": %!q(MISSING) is an empty reference: invalid reference

Likewise for `history` or `run`. Would it be hard to get commands that act on images to accept the optional `sha256:` prefix, and (just in case) future such extensions? It seems rather hardcoded right now.

On a related note, `docker commit` outputs an ID without the prefix; docker outputs `sha256:<id>`. Would it make sense to consistently output the prefix when displaying (untruncated) image IDs?

~~And on an unrelated note, I'm feeling really stupid here, but why are `id` and `digest` completely different in the output of `podman images --format json`?~~ *Never mind. Sorry about that.*

**Comment by baude** [comment]
@edsantiago This makes sense and I am working on image resolution right now. I'll add this in as I migrate all the subcommands to it.
