### ISSUE TITLE
podman 0.3.3 depends on containernetworking-cni > 0.6, missing from virt7-container-common repo

### ISSUE THREAD

**Issue by nathwill** [projectatomic/libpod#494]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**Description**

ran into this working on a new Chef cookbook for crio... it worked this morning, broke this afternoon.

podman is currently uninstallable due to a missing containernetworking-cni package > 0.6 in the virt7-container-common repos. 

**Steps to reproduce the issue:**

1. spin up a cent 7 box

2. set up the virt7-container-common-candidate repo

3. try to install podman

**Describe the results you received:**
```
Error: Package: podman-0.3.3-1.dev.gitbc358eb.el7.x86_64 (virt7-container-common)
           Requires: containernetworking-cni > 0.6
           Installed: containernetworking-cni-0.5.2-7.el7.x86_64 (@virt7-container-common)
               containernetworking-cni = 0.5.2-7.el7

```
**Describe the results you expected:**

podman 0.3.3 successfully installed

**Comment by rhatdan** [comment]
@lsm5 Is this something you could look at?

**Comment by lsm5** [comment]
On Thu, Mar 15, 2018 at 12:19:02PM +0000, Daniel J Walsh wrote:
> @lsm5 Is this something you could look at?
> 
building here: https://cbs.centos.org/koji/taskinfo?taskID=360043

-- 
Lokesh
IRC: lsm5
GPG: 0xC7C3A0DD
https://keybase.io/lsm5

**Comment by nathwill** [comment]
works again, thank you @rhatdan & @lsm5!

**Comment by rhatdan** [comment]
@nathwill Any chance you want to Blog on what you are doing?  We are always looking for bloggers on medium.com/crio

**Comment by nathwill** [comment]
@rhatdan yeah, sounds great! i'm `@nathwhal` on medium, `nath.e.will@gmail.com` if you need to email me anything.

**Comment by lsm5** [comment]
On Thu, Mar 15, 2018 at 06:19:58PM +0000, Nathan Williams wrote:
> @rhatdan yeah, sounds great! i'm `@nathwhal` on medium, `nath.e.will@gmail.com` if you need to email me anything.
> 

awesome, thanks! feel free to ping me here or freenode/#centos-virt or
#centos-devel in case of issues with centos packages.

-- 
Lokesh
IRC: lsm5
GPG: 0xC7C3A0DD
https://keybase.io/lsm5
