### ISSUE TITLE
podman run --cgroup-parent: missing cleanup on exit?

### ISSUE THREAD

**Issue by edsantiago** [projectatomic/libpod#496]
[insert standard disclaimer about me not grokking cgroups]

podman seems to be leaving cruft behind in `/sys/fs/cgroup/`:

    # podman run --rm --cgroup-parent=aaaa.slice fedora true
    # podman run --rm --cgroup-parent=aaaa.slice fedora true
    # ls -l /sys/fs/cgroup/pids/aaaa.slice
    total 0
    -rw-r--r--. 1 root root 0 Mar 15 13:35 cgroup.clone_children
    -rw-r--r--. 1 root root 0 Mar 15 13:35 cgroup.procs
    drwxr-xr-x. 2 root root 0 Mar 15 13:35 libpod-conmon-460527d9b[...]   <<<<------
    drwxr-xr-x. 2 root root 0 Mar 15 13:35 libpod-conmon-c83c79605[...]   <<<<------
    -rw-r--r--. 1 root root 0 Mar 15 13:35 notify_on_release
    -r--r--r--. 1 root root 0 Mar 15 13:35 pids.current
    -r--r--r--. 1 root root 0 Mar 15 13:35 pids.events
    -rw-r--r--. 1 root root 0 Mar 15 13:35 pids.max
    -rw-r--r--. 1 root root 0 Mar 15 13:35 tasks

The two entries flagged with `<<<<------`: should they be removed upon container termination? 

Comparison with docker:

    # docker run --rm --cgroup-parent=aaaa.slice fedora true
    # docker run --rm  --cgroup-parent=aaaa.slice fedora true
    # ls -l /sys/fs/cgroup/pids/aaaa.slice
    [no docker-*.scope entries]

Same docker behavior without --rm, i.e. the scope entry is removed upon container stop, not removal.

**Comment by mheon** [comment]
I'm going to self-assign this one and poke at it once restart is merged. I imagine we're missing some steps during container cleanup.

**Comment by mheon** [comment]
I'm fairly certain this (and probably validation) have something to do with https://github.com/kubernetes-incubator/cri-o/blob/master/server/sandbox_run.go#L379-L400 being missing from our OCI spec generation - as such CGroups aren't being passed properly to runc, which is not cleaning them up properly

**Comment by mheon** [comment]
Fixed by #507
