### ISSUE TITLE
image WorkingDir not used in container WorkingDir

### ISSUE THREAD

**Issue by nathwill** [projectatomic/libpod#499]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**Description**

podman 0.3.3 does not use the image WorkingDir when setting container WorkingDir

**Steps to reproduce the issue:**

1. inspect an images WorkingDir (e.g. library/redis)

2. create a container with `podman create` or `podman run`

3. inspect the container WorkingDir

**Describe the results you received:**

```
[root@default-centos-7 ~]# podman images
REPOSITORY                TAG      IMAGE ID       CREATED        SIZE
docker.io/library/redis   latest   4760dc956b2d   23 hours ago   111MB
[root@default-centos-7 ~]# podman inspect 4760 | grep WorkingDir
            "WorkingDir": "/data"
[root@default-centos-7 ~]# podman create docker.io/library/redis:latest
d7b6d6be8365f2dc44fa70f049320a2be99507d9929a5dd9af0fff60c50fa61e
[root@default-centos-7 ~]# podman inspect d7b6 | grep WorkingDir
            "WorkingDir": "/",
```

this also breaks running of containers that rely on command arguments relative to the WorkingDir

**Describe the results you expected:**

container WorkingDir should match the image WorkingDir unless overridden by `--workdir` arg

**Additional information you deem important (e.g. issue happens only occasionally):**

passing the `--workdir` parameter works as a workaround, but is not ideal

**Output of `podman version`:**

```
[root@default-centos-7 ~]# podman version
Version:       0.3.3-dev
Go Version:    go1.9.2
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
[root@default-centos-7 ~]# podman info
host:
  MemFree: 445145088
  MemTotal: 1040576512
  SwapFree: 2147475456
  SwapTotal: 2147479552
  arch: amd64
  cpus: 1
  hostname: default-centos-7.vagrantup.com
  kernel: 3.10.0-693.17.1.el7.x86_64
  os: linux
  uptime: 39m 34s
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
store:
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions:
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 1
  RunRoot: /var/run/containers/storage
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

VirtualBox

**Comment by mheon** [comment]
This should be simple enough - just have to check it when we generate the runtime config.

**Comment by rhatdan** [comment]
@nathwill PTAL at https://github.com/projectatomic/libpod/pull/501

**Comment by mheon** [comment]
Fixed in #501

**Comment by nathwill** [comment]
thanks for the super quick resolution y'all! 🥇

**Comment by rhatdan** [comment]
@nathwill Thanks for finding the bugs.  I like easy to fix bugs.  :^)
