### ISSUE TITLE
ENH: Add --latest param to ps command

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [projectatomic/libpod#504]
/kind feature

**Description**
It would be nice to have a --latest parameter for the ps command so you could do "libpod ps --latest" to see which container was latest.  That was if there was doubt, it could be easily verified.

**Comment by baude** [comment]
I think this already exists. Is this what you had in mind?

```
$ sudo podman run alpine ls
bin    dev    etc    home   lib    media  mnt    proc   root   run    sbin   srv    sys    tmp    usr    var

$ sudo podman ps -l
CONTAINER ID   IMAGE                             COMMAND   CREATED AT                      STATUS                     PORTS   NAMES
27a500e1cf29   docker.io/library/alpine:latest   ls        2018-03-19 14:07:05 -0500 CDT   Exited (0) 4 seconds ago           confident_newton
```

**Comment by TomSweeneyRedHat** [comment]
UGH, someday I'll learn to scroll.    I popped up the man page and didn't see anything beyond format (because dummy here didn't scroll.).  Closing and apologies.
