### ISSUE TITLE
Add persistent logging (syslog and/or audit)

### ISSUE THREAD

**Issue by mheon** [projectatomic/libpod#513]
/kind feature

Right now, when you start a Podman container, there is no persistent record that the container was started. Docker and CRI-O are both daemons and will usually be managed by init, logging their output to syslog, providing a persistent record of when containers are started, stopped, attached to, etc. We have no such persistent record with Podman - Conmon will log a bit of information to syslog when a container is run, but that's a very poor substitute for proper logging.

**Comment by mheon** [comment]
Since we expect Podman to be managed as a systemd unit in some cases, any logging to syslog should be configurable. It would be useful to switch off logging for `podman run` in the systemd unit file, but subsequently attaching with `podman attach` would generate logs.

**Comment by baude** [comment]
We should brain storm around this a little.  Right now iirc, Atomic systems do not have syslog capabilities.

**Comment by cgwalters** [comment]
I'm confused, why wouldn't you log to the journal?  Ideally with structured data.  Systemd also handles the syslog protocol by default.

You may be thinking of remote logging?  There's two options there, systemd native forwarding as well as `rpm-ostree install rsyslog`, same as classic systems.

**Comment by rhatdan** [comment]
I agree, we should either just call syslog, which would be more portable to other Linuxs or call into journal.  I have asked Steve Grubb to look at whether we should be auditing.

podman should not do anything special in logging, IE No remote logging.

**Comment by rhatdan** [comment]
Is it possible to get logrus to log both to syslog and to the screen?

**Comment by rhatdan** [comment]
mw := io.MultiWriter(os.Stdout, logFile)
logrus.SetOutput(mw)

If we did this could we output to both syslog and the stdout?

**Comment by mheon** [comment]
@rhatdan That sounds like a good option

**Comment by rhatdan** [comment]
@haircommander PTAL

**Comment by mheon** [comment]
@rhatdan I think logrus logging to syslog should be fine. I think we should make it an option, though, not a default.

If we end up needing more things logged, we should probably be adding more logrus statements.

**Comment by rhatdan** [comment]
Merging patch.
