### ISSUE TITLE
maintain a changelog (for packaging)

### ISSUE THREAD

**Issue by vrothberg** [projectatomic/libpod#514]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**

I know my request imposes some extra work on each release and that I am asking a lot, but I want to give it a try.

Would you be willing to maintain a changelog file? This would facilitate packaging a lot. I am currently bumping Podman to v0.3.3 on openSUSE and noticed that some changes require more than just downloading another tarball (e.g., the libpod.conf). If you are interested in maintaining such a file, I am willing to help (if needed).

My current workflow is basically `git log --no-merges v..v+1` to skim all updates and parse the commits that either impact packaging or that are visible to the user. That's not a very hard task, but it includes a potential for human error.

**Comment by rhatdan** [comment]
We are planning to release new versions every Friday for the time being, I think we could do what you want.  It would be nice to some how automate the generation of the document with a script like you propose and then have someone edited it to make it more readable.

**Comment by vrothberg** [comment]
Wonderful, thanks  a lot :+1: The exact git command I am using is as follows:
```shell
git log --no-merges  --format="  * %s"
```
This prints a list of commit subjects, e.g.:
  * Bump to v0.3.3q
  * Fix build after c/image changesq
  * Update containers/imageq
  * Fix E2E testsq
  * Address review commentsq
  * Fix E2E testsq
  * Add restart to main podman manpageq

**Comment by rhatdan** [comment]
Could you open a PR for this command to be added to the Makefile
Perhaps something like
make changelog
Which would add that data to the changelog file.  Then we could review the changelog through the normal process after the person gutting the release edits it.

**Comment by vrothberg** [comment]
@rhatdan I gave it a shot in https://github.com/projectatomic/libpod/pull/515

**Comment by rhatdan** [comment]
Excellent, Thanks.

**Comment by vrothberg** [comment]
https://github.com/projectatomic/libpod/pull/515 has been merged. Closing the issue now.
