### ISSUE TITLE
nit: podman usage: one of our dashes is missing

### ISSUE THREAD

**Issue by edsantiago** [projectatomic/libpod#521]
This has been bugging me for weeks; I've now changed my mind about it being too unimportant to file.

podman error/usage messages display long option names with only one dash:
```
# podman ps --last f                            
Incorrect Usage: invalid value "f" for flag -last: strconv.ParseInt: parsing "f": invalid syntax
```
This is jarring because `-last` is not an option: it must be explicitly given as `--last` with two dashes.

This happens with *every* usage message about incorrect options. I'm hoping it's a trivial fix to a golang arg-processing call.

**Comment by mheon** [comment]
@baude Is this an urfave/cli bug?

**Comment by TomSweeneyRedHat** [comment]
@mheon, smells like a urfave/cli hiccup.  I'll take a quick peak.

**Comment by baude** [comment]
Let the debate begin:
```
$ docker ps --last -f name=foo
invalid argument "-f" for --last: strconv.ParseInt: parsing "-f": invalid syntax
See 'docker ps --help'.
$
```

**Comment by rhatdan** [comment]
Definitely a bug and should be fixed. Most likely i urfave/cli

**Comment by rhatdan** [comment]
Removed short option handling to see if it could have been us that introduced the error, but error still appears.

**Comment by TomSweeneyRedHat** [comment]
@mheon, smells like a urfave/cli hiccup.  I'll take a quick peak.  (oops, thought I hit comment yesterday).

**Comment by baude** [comment]
i wonder if we should vndr in the latest code and see if that fixes it?

**Comment by mheon** [comment]
@baude Sure. If that doesn't resolve it, we can open an issue upstream.

**Comment by rhatdan** [comment]
I took a quick look at their code, and I can not even figure where this error is coming from.  But we have the same issue on buildah.

**Comment by vrothberg** [comment]
It looks like the error generation while parsing flags is responsible: https://github.com/urfave/cli/blob/master/command.go#L128

I have some time to spare and can look into this (seems to affect too many tools to ignore).

**Comment by vrothberg** [comment]
It turns out that `urfave/cli` partially depends on the flag package from the stdlib, which uses single dashes for flags. You can the error coming from here: https://golang.org/src/flag/flag.go#L912

**Comment by rhatdan** [comment]
Any thoughts on ways to fix this?

**Comment by baude** [comment]
Closing as CANT/WONT FIX
