### ISSUE TITLE
RFE: touch a file to make it easy to tell we're containerized

### ISSUE THREAD

**Issue by jlebon** [projectatomic/libpod#529]
/kind feature

**Description**

AFAICT, there isn't a file like `/.dockerenv` to make it easy to tell we're in a container. Can we add something like `/run/podman-container`?

**Comment by mheon** [comment]
This seems like an easy enough thing to do

**Comment by jlebon** [comment]
That sounds OK too. I find `/run` nicer to indicate the ephemeral nature of it though that's mostly personal preference. :)

**Comment by TomSweeneyRedHat** [comment]
/run/.containerenv would be fine by me too.  My main thing was to not include the d-word....

**Comment by mheon** [comment]
Is there anything we should look into including in the that would be helpful, besides its existence? Podman version, potentially?

**Comment by jlebon** [comment]
Hmm, how about we just leave it empty for now? Adding things later on if we really want would be a mostly backwards compatible change.

**Comment by rhatdan** [comment]
Will this work with readonly containers?  Should the file be read-only, should we make sure the file does not end up in an image?  Putting the file in /run, would be my preferred mechanism to.  Adding the version of the tool that created the file inside buildah-1.13 or podman-0.3.3

**Comment by nalind** [comment]
If we add a file, like dockerd does, but give it a different name, then we're not reducing the amount of work required for anyone.  systemd [suggests](https://www.freedesktop.org/wiki/Software/systemd/ContainerInterface/#environmentvariables) setting `container` in the environment to a short value that identifies the implementation.  Would that work for the use case?

**Comment by rhatdan** [comment]
Yes systemd like container=podman or container=buildah to be set.

**Comment by mheon** [comment]
Fixed in #533
