### ISSUE TITLE
podman run --cidfile: fail if path exists

### ISSUE THREAD

**Issue by edsantiago** [projectatomic/libpod#530]
podman happily clobbers an existing cidfile:
```
# touch /tmp/mycid
# podman run --cidfile /tmp/mycid fedora date
Thu Mar 22 15:05:26 UTC 2018
```
docker fails with a helpful diagnostic:
```
/usr/bin/docker-current: Container ID file found, make sure the other container isn't running or delete /tmp/mycid.
```
This is a judgment call: one can imagine a UNIX old-timer ranting about overprotective tools and let me shoot myself in the foot if I want to and get off my lawn. I lean that way myself at times. Still... the cost of debugging a problem is much higher if the cidfile is silently overwritten. I would recommend following the docker convention. (Bonus: I think the diagnostic would be more readable as 'Will not overwrite existing cidfile "/tmp/mycid"')

**Comment by baude** [comment]
indeed, ill take it

**Comment by baude** [comment]
well if this was name that tune, I would lose. it took me six lines (3 lines in two places)

**Comment by rhatdan** [comment]
Yes lets fix it.
