### ISSUE TITLE
how should --restart work

### ISSUE THREAD

**Issue by baude** [projectatomic/libpod#534]
We still need to implement how --restart should work.  In an irc discussion, there seemed to be two approaches each with pros and cons:

* systemd unit files
* cleanup script/conmon

I have asked @giuseppe to look into implementing this given his familiarity with systemcontainers.  We will use this issue to help him define how this should work.

**Comment by mheon** [comment]
I think cleanup callbacks are the correct way to do this once it's ready. They'll be triggering anyways, to clean up mounts and record exit status, so adding restart policy shouldn't be hard. There are potential difficulties with indicating whether a container should restart (we'll need to record whether the container was user-stopped in the DB, as I presume users don't want a container they just `podman stop`'d restarting).

**Comment by mheon** [comment]
I will not that cleanup callbacks in general require some design work before they're ready. I'll be working on them next week.

**Comment by rhatdan** [comment]
I am not sure what @baude is getting at.  We don't want podman to learn to restart itself.  We should leave this to systemd.  Getting podman/conmon to cleanup after itself, is important.

**Comment by baude** [comment]
something has to tell systemd about it though ...

**Comment by rhatdan** [comment]
Humans tell systemd by running podman command as a service and then having it automatically restart.

**Comment by giuseppe** [comment]
so should `create|run` have `--restart` at all?  Or do we prefer the users to use directly systemd?

If so, we will need to implement a way for podman to write the pid of conmon to a file, so that systemd can monitor it.

**Comment by rhatdan** [comment]
We don't have anything that monitors this, I don't want to hack up conmon to do it.  This is what systemd does best.  atomic CLI is already creating the unit files it it uses runc it needs to do it in the unit file podman should be no different.

We should document in the man page how to do this with a unit files.  We also don't do autostart, this should be done in a unit file.  We don't need conmon to grow to be an init daemon.

**Comment by giuseppe** [comment]
I've opened two PRs:

https://github.com/kubernetes-incubator/cri-o/pull/1469
https://github.com/projectatomic/libpod/pull/549
