### ISSUE TITLE
podman needs to support mounts.conf and secrets patch

### ISSUE THREAD

**Issue by rhatdan** [projectatomic/libpod#539]
Need support for secrets to be mounted into containers.

We want rhel users to be able to do `yum update` while in container and use subscription from the host.

**Comment by umohnani8** [comment]
ACK

**Comment by rhatdan** [comment]
I did this on the plane flight home, will submit a patch once I get internet that allows github.com

**Comment by umohnani8** [comment]
Fixed in #544
