### ISSUE TITLE
Document and implement or remove remaining run/create CLI options

### ISSUE THREAD

**Issue by mheon** [projectatomic/libpod#541]
We still have unimplemented CLI options in `podman run` and `podman create` (for example, `--ip` and `--ip6`). We need to document what these are, and either implement them, or disable them and remove them from manpages.

**Comment by mheon** [comment]
Networking options we don't implement because of CNI:
- `--ip`
- `--ip6`
- `--network-alias`
- `--link-local-ip`

Attach-related options we don't support (could probably be implemented):
- `--attach`

Misc flags we don't have support for yet:
- `--volumes-from`

This is from a cursory scan of `podman run --help` - I'm sure there are others

**Comment by rhatdan** [comment]
@dcbw How close is CNI to implementing --ip and --ip6, that would seem to be a fairly common request?

**Comment by ibuildthecloud** [comment]
Random fly by two cents:

I'd very much like to see `--volumes-from` supported.  When running something like mysql which has a VOLUME defined in the Dockerfile, to upgrade the container and not loose the state `--volumes-from` becomes important.

Regarding `ip`, `ip6`, `network-alias`, and `link-local-ip` I'd prefer you optimistically drop the options.  `ip` and `ip6` could maybe be a common ask, but today they only work in "user" (libnetwork) networks and not the default bridge.  So they aren't as commonly used even though the options exists today.

**Comment by mheon** [comment]
Update on this: implemented `--attach`

**Comment by mheon** [comment]
I tend to agree with dropping most of the network options.

Volumes-from should be doable, given we do share container create configs.

**Comment by rhatdan** [comment]
@umohnani8 Want to take a look at --volumesfrom?

**Comment by 42wim** [comment]
regarding to `--ip` and `--ip6`

Can already be done by running `CNI_ARGS=IP=10.88.1.142 podman run ...` or `CNI_ARGS=IP=2001:0db8::42 podman run ...`

Unfortunately not possible specifying both at the same time

**Comment by mheon** [comment]
Doesn't look like the CNI API exposes the ability to set this outside of environment variables, which is somewhat disappointing.

**Comment by mheon** [comment]
Also, once the `--volumes-from` PR from @umohnani8 gets merged, I think we can close this, as the flags are removed or implemented. We should open a separate issue to track potentially supporting `--ip` (and poke at the CNI maintainers to ask if it's doable).

**Comment by baude** [comment]
should we be filing an issue on CNI to make these exposed?

**Comment by rhatdan** [comment]
Yes, and closing this issue and making a new one focused on networking issues is a good idea.

**Comment by umohnani8** [comment]
#931 got in, closing this issue.
