### ISSUE TITLE
"kernel does not support overlay fs" even though it does

### ISSUE THREAD

**Issue by TomasTomecek** [projectatomic/libpod#545]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind bug

**Description**

podman fails to initialize telling me `kernel does not support overlay fs: driver not supported`. This is a standard Fedora 27 kernel. I presume this is related to the fact that I have XFS w/o dtype.

**Steps to reproduce the issue:**
1. `podman --log-level debug images`

**Describe the results you received:**
```
DEBU[0000] [graphdriver] trying provided driver "overlay"
DEBU[0000] overlay: override_kernelcheck=true
ERRO[0000] Could not get runtime: kernel does not support overlay fs: driver not supported
```

**Describe the results you expected:**

The list of images is presented.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:       0.3.4
Go Version:    go1.10
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
could not get runtime: kernel does not support overlay fs: driver not supported
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Fedora rawhide

**Comment by TomasTomecek** [comment]
Now I'm even more sure it's because of dtype b/c I created a new xfs partition with dtype and it works just fine. There, would be possible to

1. make the error message more precise?
2. and ideally suggest the user what it should do (reformat disk, use different backend)

WDYT?

**Comment by mheon** [comment]
I think we've seen this before - containers/storage was dropping specific error causes for certain things and instead giving a nonspecific `driver not supported` error. This was fixed in https://github.com/containers/storage/pull/163, but we haven't updated to pick up that fix. Let me open a PR to grab the latest version of c/storage and fix this, so we can have it resolved in the next release.

**Comment by rhatdan** [comment]
Since this is merged, I am going to close this Issue.
