### ISSUE TITLE
RFE: support passing through existing env var using `-e` for `exec` command

### ISSUE THREAD

**Issue by jlebon** [projectatomic/libpod#550]
`podman run` supports simply doing `-e FOO` to pass through whatever the current value of `FOO` is. It looks like that's not the case for `exec`:

```
$ sudo podman exec -t --env TERM pet /bin/bash
exec failed: container_linux.go:348: starting container process caused "invalid environment 'TERM'"
exit status 1
```

As expected `-e TERM=$TERM` does work.

**Comment by mheon** [comment]
This seems like it should be an easy enough fix. We can probably reuse the environment handling from `podman run`.

**Comment by rhatdan** [comment]
Since 552 is merged I am going to close this issue.
