### ISSUE TITLE
running make to build podman doesn't work

### ISSUE THREAD

**Issue by arashkaffamanesh** [projectatomic/libpod#581]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**Description**

**Steps to reproduce the issue:**

$ make

**Describe the results you received:**

[vagrant@localhost libpod]$ make
go build -i -ldflags '-X main.gitCommit="94301bab8f82b6bb7c70d9dde8b85ccd0ce3a0b1" -X main.buildInfo=1522700640' -tags "seccomp btrfs_noversion  exclude_graphdriver_btrfs containers_image_ostree_stub selinux" -o bin/podman github.com/projectatomic/libpod/cmd/podman
go build github.com/projectatomic/libpod/cmd/podman: /usr/lib/golang/pkg/tool/linux_amd64/link: signal: killed
make: *** [Makefile:88: podman] Error 1

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

running on Fedora release 27 (Twenty Seven) in a vagrant box

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
This looks like it could be an out-of-memory issue. Are you using the provided Vagrantfile?

**Comment by arashkaffamanesh** [comment]
Oh no, didn't noticed the Vagrantfile, but with the provided Vagrantfile I was getting:

`The box you attempted to add doesn't match the provider you specified.
Provider expected: virtualbox
Provider of box: libvirt`

Since I'm on mac and don't have a libvirt provider for vagrant on mac, had to change the Vagrantfile as follow:

```
Vagrant.configure(2) do |config|
    config.vm.provider "virtualbox" do |virtualbox, override|
        virtualbox.memory = 3096
        virtualbox.cpus = 3
    end
    config.vm.synced_folder ".", "/home/vagrant/sync", disabled: true
    config.vm.synced_folder ".", "/home/vagrant/libpod", type: "rsync", rsync__exclude: ["_output"]
    config.vm.define "fedora_cloud" do |fedora_cloud|
        fedora_cloud.vm.box =  "fedora/26-cloud-base"
    end
end
```

And the build went through:

```
[vagrant@localhost ~]$ podman version
Version:       0.4.1-dev
Go Version:    go1.8.7
Git Commit:    "f41dc0b2580ae83129264edbe45b92231bd119a2"
Built:         Mon Apr  2 21:07:53 2018
OS/Arch:       linux/amd64`
```

And can't wait to try podman now :-)
thanks so much!

**Comment by arashkaffamanesh** [comment]
The issue can be closed.
