### ISSUE TITLE
conmon-pidfile flag not recognized

### ISSUE THREAD

**Issue by nathwill** [projectatomic/libpod#582]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**Description**

testing the new `--conmon-pidfile` option, and podman throws an error

**Steps to reproduce the issue:**

1. install podman 0.3.5

2. try running a container with podman using --conmon-pidfile (e.g. `podman run --net=host --conmon-pidfile /run/test.pid busybox bash`)

**Describe the results you received:**

```
[root@default-fedora-27 ~]# podman run --net=host --conmon-pidfile /run/test.pid busybox bash
option parsing failed: Unknown option --conmon-pidfile
exit status 1
[root@default-fedora-27 ~]# dnf list podman
Installed Packages
podman.x86_64                                                0.3.5-1.gitdb6bf9e.fc27                                                 @updates
```

**Describe the results you expected:**

a running container with a conmon pidfile

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:       0.3.5
Go Version:    go1.9.4
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  MemFree: 406011904
  MemTotal: 1037946880
  SwapFree: 2143010816
  SwapTotal: 2147479552
  arch: amd64
  cpus: 1
  hostname: default-fedora-27.vagrantup.com
  kernel: 4.13.9-300.fc27.x86_64
  os: linux
  uptime: 1h 32m 24.71s (Approximately 0.04 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
store:
  ContainerStore:
    number: 3
  GraphDriverName: overlay
  GraphOptions:
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 4
  RunRoot: /var/run/containers/storage
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

virtualbox

**Comment by mheon** [comment]
I suspect this is a packaging issue. Are you building from source or using RPMs?

**Comment by mheon** [comment]
Thought: We briefly shipped a `conmon` in our Podman RPMs (separate from the main `conmon` package which was lagging too far to support the flags we needed). I believe this was recently removed as CRI-O bumped to a `conmon` we can use. Are we leaving the old `conmon` that was bundled by Podman in place? It's no longer being updataed, and set to override CRI-O's `conmon` in our config file... May require a packaging change to make that a symlink to CRI-O conmon.

**Comment by nathwill** [comment]
using RPMs in fedora

**Comment by mheon** [comment]
Alright, I'm suspecting that it's either using the older bundled `conmon` or our shipping `conmon` is too old to have the patch.

@lsm5 - are we still shipping bundled `conmon` in the Podman package in Fedora?

**Comment by nathwill** [comment]
it looks like both the conmon-package-provided conmon and the podman-package-provided conmon are throwing this error:

```
[root@default-fedora-27 ~]# podman --conmon=/usr/libexec/crio/conmon run --net=host --conmon-pidfile /run/test.pid busybox bash
option parsing failed: Unknown option --conmon-pidfile
write child: broken pipe
[root@default-fedora-27 ~]# dnf install c^C
[root@default-fedora-27 ~]# podman --conmon=/usr/libexec/podman/conmon run --net=host --conmon-pidfile /run/test.pid busybox bash
option parsing failed: Unknown option --conmon-pidfile
exit status 1
```

**Comment by rhatdan** [comment]
Latest conmon package in cri-o package does not include this change.  We have to update the

**Comment by rhatdan** [comment]
Building  podman-0.3.5-2.gitdb6bf9e

**Comment by rhatdan** [comment]
I have built a new version of podman for Fedora 27 Could you try it out.

https://bodhi.fedoraproject.org/updates/FEDORA-2018-1fa9ad30ec

**Comment by lsm5** [comment]
@mheon fedora 27 and 28 branches ship their own conmon inside of podman rpm

**Comment by lsm5** [comment]
seems @rhatdan just built new builds of it

**Comment by mheon** [comment]
@lsm5 Great, got confused and thought we debundled on non-rawhide too. Thanks!

**Comment by nathwill** [comment]
@rhatdan that build works

```
[root@default-fedora-27 ~]# podman run --net=host --conmon-pidfile /run/busy-date.pid busybox date
Tue Apr  3 15:20:12 UTC 2018
[root@default-fedora-27 ~]# cat /run/busy-date.pid 
6069
```

**Comment by rhatdan** [comment]
@nathwill Please update karma
