### ISSUE TITLE
podman run -a stdin: does not detach stdout

### ISSUE THREAD

**Issue by edsantiago** [projectatomic/libpod#604]
Running with `-a stdin` produces output on stdout 
```
# podman run -a stdin fedora date
Tue Apr 10 17:51:57 UTC 2018
# podman run -a stdin fedora ls /nonesuch
ls: cannot access '/nonesuch': No such file or directory
```
docker emits a container ID in both cases:
```
# docker run -a stdin fedora date
56f3a8de1746667b401181c09f844332da972861de81b47711583e3f6393c230
# docker run -a stdin fedora ls /nonesuch
7ad6159f3dbc3117eb66e0a4ce2caa2e13b00a483e2de4694dbcea9933d6c42a
```
(output accessible as expected via `docker logs`)

podman-0.4.1-1.gitb51d327.fc27

**Comment by mheon** [comment]
`podman run -a` is not implemented yet. Which is confusing because the flag throws no errors. We need to deal with that.

**Comment by mheon** [comment]
Working on a patch to implement --attach

**Comment by mheon** [comment]
Closed via #608

**Comment by edsantiago** [comment]
@mheon @baude can you confirm this is fixed? Even with `podman-0.4.3-git06f0d0b.fc27` (latest from baude's copr) I see the same behavior described in the initial comment.

To be precise: when specifying `-a stdin`, I expect stdout and stderr to *not* be attached; and I expect podman to emit a container ID to stdout.

**Comment by mheon** [comment]
OK. I think we fixed the attach part of things, but we did not fix the printing container ID thing.

Need to nail down exactly when Docker prints container ID. Is it only when STDERR and STDOUT are both not attached?

**Comment by edsantiago** [comment]
AFAICT the docker rule is: if (neither stdout nor stderr attached) then print container ID.

**Comment by mheon** [comment]
Should actually be fixed now
