### ISSUE TITLE
nit: superficially support -i in exec

### ISSUE THREAD

**Issue by ibuildthecloud** [projectatomic/libpod#606]
I understand that `--interactive` flag in `docker exec` might not make sense to be implemented in `podman` but `docker exec` essentially requires `-i` to be useful.  So muscle memory has me typing `-it` all the time.  It would be nice if exec had a dummy flag for `--interactive | -i` that did nothing.

**Comment by rhatdan** [comment]
SInce we mention in the man page, we should allow it to be entered.

**Comment by rhatdan** [comment]
Brent could you add the -i support and make it a no-op.

Man page says
       --interactive, -i Not supported.  All exec commands are interactive by default.

**Comment by mheon** [comment]
I don't see why it shouldn't be supported, though - it seems like something we should handle?

Exec as a whole needs a rework for CRI-O integration (we need to rework to call conmon instead of runc directly). We can probably get proper per-stream attach in then?
