### ISSUE TITLE
question: mount/umount concurrency

### ISSUE THREAD

**Issue by ibuildthecloud** [projectatomic/libpod#614]
`podman mount` always mounts to the same place.  I'm concerned if I'm running two scripts in parallel this can be error prone.  The mount, cp, umount flow in parallel can result in a umount before you'd like.  For safety it would be nice if you could specify the target dir which I'd expect would mount to the common location then bind mount to the target.

**Comment by mheon** [comment]
I don't know how the container's read/write layer would react to being mounted in multiple places, but if that can be addressed in containers/storage, I think this would definitely be a neat addition (`unmount` has always worried me a little with its potential interactions with running containers. We have checks in place to make sure you don't unmount a running container, but it'd be a lot cleaner if it was a completely separate mount).

**Comment by rhatdan** [comment]
Sadly this is not something you can do with overlay, I believe you could do this with devicemapper.  We could add a bind mount from the actual mount point to the specified location. 

@nalind WDYT?

**Comment by mheon** [comment]
I was thinking about this more, and I wonder if having some sort of session scheme would also work. `podman mount` would generate a session ID, and `podman unmount` would optionally accept an ID to unmount. If more than one mount session is active, `podman unmount` won't actually unmount, but will instead remove the mount session in question from the active sessions list. This would ensure unmount doesn't squash other active copy operations.

This would need a bit of work, especially if we want to do it in a backwards-compatible fashion, but it would solve the issue without further work on the storage side.

**Comment by rhatdan** [comment]
Sure we could do that, although we would probably need a --force  umount.  The datastore counting mounts should be done in /run. so that it will not exists on reboot.  We would also need to notice if someone umounts mount point outside of the podman command.

**Comment by mheon** [comment]
This should be fixed now via #1104 - we use a mount counter to ensure that we don't unmount until every active mount is done.
