### ISSUE TITLE
podman run: add -h alias for --hostname

### ISSUE THREAD

**Issue by edsantiago** [projectatomic/libpod#624]
docker allows (and documents) `-h` as a short alias for `--hostname`; podman seems to interpret it as `--help`:
```
# podman run -h foo.example.com fedora uname -n
[usage message]
# echo $?
0

# docker run -h foo.example.com fedora uname -n
foo.example.com
```

**Comment by mheon** [comment]
I think we can tell urfave/cli to not use `-h` for help, and then add it as a short option for `--hostname`

**Comment by rhatdan** [comment]
Seems like a bad docker design, but ...

**Comment by baude** [comment]
BC we are in agreement, closing
