### ISSUE TITLE
podman inspect : docker compatibility

### ISSUE THREAD

**Issue by edsantiago** [projectatomic/libpod#633]
Some headscratching today led to a quick script comparing the output of `podman inspect` against docker. Results:
```
Only in docker:                                                                                                                                                
   .Config.OnBuild
   .GraphDriver.Data.DeviceId
   .GraphDriver.Data.DeviceName
   .GraphDriver.Data.DeviceSize
   .HostConfig.Binds
   .HostConfig.CpuShares                 <--- podman calls it CPUSShares, note extra 'S'
   .HostConfig.Links
   .HostConfig.LogConfig.Config
   .HostConfig.LogConfig.Type
   .HostConfig.RestartPolicy
   .HostConfig.VolumeDriver
   .HostConfig.VolumesFrom
   .NetworkSettings.GlobalIPv6Address    <--- podman calls it '...Addresses', plural; also, podman value is array
   .NetworkSettings.Networks
Case mismatch between docker and (podman):
   .HostConfig.CpuCount (CPUCount)
   .HostConfig.CpuPercent (CPUPercent)
   .HostConfig.CpuPeriod (CPUPeriod)
   .HostConfig.CpuQuota (CPUQuota)
   .HostConfig.CpuRealtimePeriod (CPURealtimePeriod)
   .HostConfig.CpuRealtimeRuntime (CPURealtimeRuntime)
   .HostConfig.CpusetCpus (CPUSetCPUs)
   .HostConfig.CpusetMems (CPUSetMems)
   .HostConfig.Dns (DNS)
   .HostConfig.DnsOptions (DNSOptions)
   .HostConfig.DnsSearch (DNSSearch)
   .HostConfig.NanoCpus (NanoCPUs)
   .Id (ID)
Type difference between docker and (podman):
   .Config.User : scalar (hash)
   .ExecIDs : scalar (array)
   .HostConfig.CapAdd : scalar (array)
   .HostConfig.CapDrop : scalar (array)
   .HostConfig.ConsoleSize : array (scalar)
   .HostConfig.Devices : array (scalar)
   .HostConfig.SecurityOpt : scalar (array)
   .HostConfig.Ulimits : scalar (array)
   .NetworkSettings.Ports : scalar (array)
```
I don't know if any of these are important or worth fixing; although I think maybe at least the extra 'S' in CPUSShares deserves a fix or explanation.

**Comment by mheon** [comment]
CPUSShares sounds like a typo.

The IPv6 address/addresses reflects us potentially having multiple IPs in a single container (well, we don't have ANY IPv6 stuff right now, but CNI theoretically can do more than one).

The case changes were all deliberate to stop linter warnings IIRC. We can swap them back and nolint if we want to fix.

I don't know why Docker has ports, CapAdd/CapDrop, security-opt, and similar as scalars. IMO the way we're doing things makes a lot more sense in these cases.

**Comment by rhatdan** [comment]
If ours make sense, then stick with it, Fix spelling issue though. Only reason this could potentially cause issues would be if someone used a --format command, but I willing to live with the risk if our change is justifiable.
