### ISSUE TITLE
RFE:  touch /.dockerenv when running container

### ISSUE THREAD

**Issue by miabbott** [projectatomic/libpod#648]
/kind feature

When running a container via `docker`, it touches `/.dockerenv` in the container file system.  It's an empty file and appears to be [related to the LXC execution driver](https://superuser.com/questions/1021834/what-are-dockerenv-and-dockerinit#1021925), but it is a useful 'canary in a coal mine' to determine if you are in container environment or not.

For example, I have the following in my `.bashrc` which lets me know when I am in my pet container which has my home directory mounted in:

```bash
__in_dockerenv=no                                                              
if [ -f /.dockerenv ]; then  
    __in_dockerenv=yes           
fi        
                                                              
if [[ "$__in_dockerenv" == yes ]]; then
    export PS1="[\[$txtred\](container) \[\033[01;34m\]\w\[\033[00m\] \[$txtcyn\]\$git_branch\[$txtred\]\$git_dirty\[$txtrst\]]\$ "
fi 
```

The result is a red colored `(container)` in my bash prompt.

**Comment by mheon** [comment]
@miabbott We presently touch a file, `/run/containerenv`, that does the same thing. We debated on the naming, and decided that it wasn't essential to match Docker here.

**Comment by miabbott** [comment]
How about a symlinking `/.dockerenv` to `/run/containerenv`?

While I don't know how many users rely on `/.dockerenv`, keeping that in place would make the migration from `docker` to `podman` that much smoother.

**Comment by rhatdan** [comment]
I'm not crazy about embedding the name "docker" into our code then is necessary.   @miabbott Are you familiar with a lot of people who rely on this?  This is also a problem with readonly container images.  IE THe ability to share an image without modifying it.  But I think we potentially already have issues with this.

**Comment by miabbott** [comment]
No, I don't really have any hard numbers on how many users rely on this.  (I tried searching GitHub for some examples of this, but got a lot of false positives.)

I think the point of not including `docker` in the code is a good enough argument to punt on this request. 

I can easily adapt my own use case to also look for `/run/containerenv`.
