### ISSUE TITLE
bash completion to expand image names

### ISSUE THREAD

**Issue by carlwgeorge** [projectatomic/libpod#660]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**

The `docker` command's bash completion allows a user to tab to complete images names that have already been pulled.  The `podman` command's bash completion doesn't, but I would like it to.

**Steps to reproduce the issue:**

1. `podman pull registry.fedoraproject.org/fedora`

2. `podman run -it --rm <TAB>`

**Describe the results you received:**

Nothing.

**Describe the results you expected:**

The image name to be inserted as a completion.

**Comment by rhatdan** [comment]
I agree.  We need someone to work on improving bash completions.   If we don't get a volunteer, I can assign it to a summer intern.

**Comment by carlwgeorge** [comment]
Nice, thanks!
