### ISSUE TITLE
[low] docker compatibility: podman build URL-to-Dockerfile

### ISSUE THREAD

**Issue by edsantiago** [projectatomic/libpod#682]
This is a followup to [buildah issue #80](https://github.com/projectatomic/buildah/issues/80):
```
# podman build https://raw.githubusercontent.com/autotest/autotest-docker/master/subtests/docker_cli/build/full/Dockerfile
error prepping temporary context directory: Error processing tar file(exit status 1): unexpected EOF
error running the buildah build-using-dockerfile (bud) command: exit status 1
```
The workaround is to bracket the URL with '-f' and '.' (dot, i.e. cwd):
```
# podman build -f [url] .
```
I have no way of knowing if this is common in docker environments, or how important this usage may be. I'm filing this because if it's easy for podman to do the `-f/.` preprocessing, it might save people time down the road. If it's not easy, just close this and trust that future seekers will find this issue and the workaround.

**Comment by mheon** [comment]
A bit harder to parse around the Buildah implementation as we're moving to directly share code/flags with Buildah now. Still, we need to keep track of things like this... Maybe collect them into a docker-incompat.md file and link it in the readme?

**Comment by rhatdan** [comment]
I would say this is a bug in buildah.  buildah should be able to handle this the same way as docker.  Not require the -f if it is a url

**Comment by rhatdan** [comment]
@TomSweeneyRedHat Could you open up an issue on buildah to support this

**Comment by mheon** [comment]
Fixed in buildah, fix vendored into Podman, works on master. Closing.
