### ISSUE TITLE
varlink: InspectImage does not serialize the metadata

### ISSUE THREAD

**Issue by TomasTomecek** [projectatomic/libpod#742]
Fedora rawhide, podman-0.5.2-2.gitfa4705c.fc29.x86_64.

value of 'image' key is a string, it would be much better if it was serialized (hence it was a dict)

Current results
```
In [15]: podman.InspectImage("docker.io/library/fedora:27")
Out[15]: {'image': '{"Id":"9110ae7f579f35ee0c3938696f23fe0f5fbe641738ea52eb83c2df7e9995fa17","Digest":"sha256:8f...
```

Expected results
```
In [15]: podman.InspectImage("docker.io/library/fedora:27")
Out[15]: {'image': {"Id": "9110ae7f579f35ee0c3938696f23fe0f5fbe641738ea52eb83c2df7e9995fa17", "Digest": "sha256:8f...
```

**Comment by baude** [comment]
This is done with intent because we would prefer to not duplicate the massive structs for inspect image and inspect container for varlink.  the docs -> https://github.com/projectatomic/libpod/blob/master/API.md#func-inspectimage  point this out.

**Comment by TomasTomecek** [comment]
If this is intentional, feel free to close.

**Comment by rhatdan** [comment]
Yes I would rather fix this on the client, then have to deal with it on the server.  Hopefully we can build some helper client libraries like python.

**Comment by TomasTomecek** [comment]
Speaking of helper python libraries, we are working on this library https://github.com/user-cont/conu where we try to create a universal API for pretty much any container engine/manager/tool and we would love to integrate podman in it -- ideally via the varlink interface. Does it sound interesting to you?

**Comment by rhatdan** [comment]
Yes we would be interested in that.

**Comment by jwhonce** [comment]
@TomasTomecek This is our layer on varlink https://github.com/projectatomic/libpod/pull/748
