### ISSUE TITLE
SELinux context of host directory shared with container not reset to previous value.

### ISSUE THREAD

**Issue by jrm16020** [projectatomic/libpod#759]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**Description**

I want to use `podman` as a replacement for `docker` for working with containers locally.  Sometimes that means sharing at least part of the contents of my home directory as a volume to the container I spawn.  An example could be running a tool that needs AWS credentials and using `-v $( pwd )/.aws:/some/container/path:ro,z` for sharing those credentials to the container.

When using the `z` option for sharing something in my home directory the SELinux context is set to container_file_t and is kept that way even after that container is stopped and removed.  I probably wouldn't have noticed had it not broken the ability for `gdm-session-worker` to read the configuration for my Yubikeys in `$HOME/.yubico`.  After a logout and attempt to log back in with the mislabeled `$HOME` I can't log back in (due to the multi-factor auth I have configured in PAM requiring my Yubikey).  Example AVCs are pasted below.  

```
39. 05/11/2018 13:40:51 gdm-session-wor system_u:system_r:xdm_t:s0-s0:c0.c1023 0 dir write system_u:object_r:container_file_t:s0 denied 353
40. 05/11/2018 13:40:51 gdm-session-wor system_u:system_r:xdm_t:s0-s0:c0.c1023 0 dir add_name system_u:object_r:container_file_t:s0 denied 354
41. 05/11/2018 13:40:51 gdm-session-wor system_u:system_r:xdm_t:s0-s0:c0.c1023 0 file create system_u:object_r:container_file_t:s0 denied 355
42. 05/11/2018 13:40:51 gdm-session-wor system_u:system_r:xdm_t:s0-s0:c0.c1023 0 file write system_u:object_r:container_file_t:s0 denied 356
43. 05/11/2018 13:40:51 gdm-session-wor system_u:system_r:xdm_t:s0-s0:c0.c1023 0 file setattr system_u:object_r:container_file_t:s0 denied 357
44. 05/11/2018 13:40:51 gdm-session-wor system_u:system_r:xdm_t:s0-s0:c0.c1023 0 dir remove_name system_u:object_r:container_file_t:s0 denied 358
45. 05/11/2018 13:40:51 gdm-session-wor system_u:system_r:xdm_t:s0-s0:c0.c1023 0 file rename system_u:object_r:container_file_t:s0 denied 359
46. 05/11/2018 13:40:51 gdm-session-wor system_u:system_r:xdm_t:s0-s0:c0.c1023 0 file unlink system_u:object_r:container_file_t:s0 denied 360
```

**Steps to reproduce the issue:**

1. Confirm SELinux context of home before starting a container
```
drwx------. 55 jyoung  jyoung  unconfined_u:object_r:user_home_dir_t:s0 4.0K May 11 14:48 jyoung
```

2. Run some container with `podman` sharing `$HOME` to the container as a volume.
```
podman run --rm -itv /home/jyoung/:/host:ro,z alpine sh
```

3. Verify that SELinux context of `$HOME` is changed
```
drwx------. 55 jyoung  jyoung  system_u:object_r:container_file_t:s0    4.0K May 11 14:48 jyoung
```

**Describe the results you received:**
- `docker` reverts SELinux context of the host directory.  `podman` does not.

**Describe the results you expected:**
- `podman run -v /path:/container/path:z .........` shares directory with container for the container's lifetime and reverts file context of host directory when container stops

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 0.5.1
```

**Output of `podman info`:**

```
host:
  MemFree: 5592883200
  MemTotal: 16717160448
  SwapFree: 8430546944
  SwapTotal: 8430546944
  arch: amd64
  cpus: 4
  hostname: jkylaptop
  kernel: 4.16.7-300.fc28.x86_64
  os: linux
  uptime: 1h 35m 52.91s (Approximately 0.04 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
store:
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions:
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 1
  RunRoot: /var/run/containers/storage
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
```
 ostree://atomic-28:fedora/28/x86_64/workstation
                   Version: 28.20180510.0 (2018-05-10 19:49:37)
                BaseCommit: bc3cd76b0f2796ebe6af542846d0ac8d13bf16843a3866b0093059b306f99db5
              GPGSignature: Valid signature by 128CF232A9371991C8A65695E08E7E629DB62FB1
```

**Comment by rhatdan** [comment]
This works the same with Podman or with Docker.  If you add the :z or the :Z we always relabel, and the relabel is not reversed when the container is removed.

You can fix the label on by executing

restorecon -R -v -F ~/.aws

**Comment by jrm16020** [comment]
@rhatdan that may be the way it's supposed to work but that's definitely not my experience on Fedora Atomic Host 28.  Docker does relabel and persist that relabel for other directories on the filesystem, just not for anything I share via `$HOME`. 

It seems like the idea of containerized developer tooling doesn't work well without reversing the relabel when the container is removed.  Is the idea that I'd be using Flatpak instead of podman for running some tool in a container like this?  Project Atomic's own blog calls out [doing development in containers](https://www.projectatomic.io/blog/2018/02/fedora-atomic-workstation/).  That's what I want to do, just without the big fat daemon I currently need.

**Comment by cgwalters** [comment]
You can do two things today.  First, you can use `--privileged` for your container...that's mostly where I'm at today since it fixes other things I need.

If you want to use unprivileged containers (a good idea!) then the pattern I use is to drop the data in a separate `container_file_t` directory like `/srv`.

**Comment by cgwalters** [comment]
I've been thinking of changing Atomic Host/Silverblue to basically do `chcon system_u:object_r:container_file_t:s0 /var/srv`.

**Comment by rhatdan** [comment]
Yes as Colin said, you can run them either with container_file_t
or disable SELinux separation
podman run -ti --security-opt label:disable ...

We have been talking about adding a new type like container_user_t which would be allowed to user content in the users homedir.

**Comment by jrm16020** [comment]
That sounds like a great idea @rhatdan !

**Comment by FlorianLudwig** [comment]
```
podman run -ti --security-opt label=disable ...
```
if you happen to come here and end up with `Error: Invalid --security-opt 1: "label:disable"` ;)
