### ISSUE TITLE
Versioning differences podman v/s python-podman

### ISSUE THREAD

**Issue by lsm5** [projectatomic/libpod#786]
Continuing IRC discussion here..

python-podman has its own version. This will be painful as far as distro packaging goes, so I suggest any code with its own version be an independent upstream and thus an independent distro package.

@rhatdan @jwhonce @baude @mheon thoughts? ^

**Comment by rhatdan** [comment]
If they are going to be independent then fine. But why are they going to have different versions?  Seems simpler to keep them the same?

**Comment by mheon** [comment]
@jwhonce would prefer they be separate, given that the Python bindings could be changed independently of Podman and libpod (multiple releases for a single release of Podman for example)

**Comment by rhatdan** [comment]
If we do that I think they should move to totally different Repos then.  My concern is we end up with  a test matrix.  If I update podman and there is no new version of python3-podman, will python3-podman break?

**Comment by jwhonce** [comment]
My concern was version #  gaps if we start pushing content to places like pypi.  We can state that all versions are pushed even if the client content doesn't change.  Then having one version number won't confuse people.

**Comment by wking** [comment]
> Right now, we're just doing timed releases, with no guarantees of any sort of stability...

From [the SemVer spec][1]:

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

So you can adopt SemVer, stick to 0.x.y as long as you like, and basically do whatever you want (although personally I like to use the minor release number to mark pre-1.0 breaking changes).  Once you're comfortable with stability, you can cut a 1.0.0 and start being more careful.

[1]: https://semver.org/#spec-item-4

**Comment by baude** [comment]
we have agreement on how this works. ... versioning change/split when we cut podman-1.0.  at that time, the python code will also go to a different repo.
