### ISSUE TITLE
podman commit: output missing sha256: prefix

### ISSUE THREAD

**Issue by edsantiago** [projectatomic/libpod#788]
Followon to #493: `podman commit` emits a hash without the `sha256:` prefix:
```
podman run --name foo fedora date
Thu May 17 12:22:26 UTC 2018
# podman commit foo bar
Getting image source signatures
Skipping fetch of repeat blob sha256:891e1e4ef82ad02a4ea1f030831f942d722c7694c4db64ca3239c8163b811c58
Copying blob sha256:5b0a8ad8a78edd07b48a32be71f151580141ab0a2f3b1c14efc7f7b32fba67e5
 2.50 KB / 2.50 KB [========================================================] 0s
Copying config sha256:ab13eefc4963099c5271a84ca1af313c676fbe2a94a5b453ec063c55f9d4c593
 1.59 KB / 1.59 KB [========================================================] 0s
Writing manifest to image destination
Storing signatures
ab13eefc4963099c5271a84ca1af313c676fbe2a94a5b453ec063c55f9d4c593
```
(note that podman outputs `sha256:` in its stderr-only verbose messages). Compare to docker:
```
# docker run --name foo fedora date
Thu May 17 12:22:46 UTC 2018
# docker commit foo bar
sha256:3d2ab2ff0febb795aa87187727c63b09623c71685b159cfe2e49b2e09894553f
```
Minor as this is, automated tools may use this output to look up in `podman images --no-trunc`; it's also a docker compatibility issue, and could one day be important if the digest type changes.

**Comment by rhatdan** [comment]
I thinks @wking or someone pointed out that this was not a hash, but an ID is that correct?_

**Comment by wking** [comment]
> I thinks @wking or someone pointed out that this was not a hash, but an ID is that correct?

It was @mheon [here][1].

[1]: https://github.com/projectatomic/libpod/pull/816#discussion_r189617840

**Comment by rhatdan** [comment]
Thanks @wking skimming to many issues/bugzillas.  Ok I am going to close this then.
