### ISSUE TITLE
OWNERS: Update approvers (e.g. include @TomSweeneyRedHat)?

### ISSUE THREAD

**Issue by wking** [projectatomic/libpod#812]
There seems to be a mismatch between folks with the approval bit and folks in the `OWNERS` file.

```console
$ APPROVERS=$(git log | grep 'Approved by' | sort | uniq -c | sort -n)
$ echo "${APPROVERS}" | while read LINE; do UNAME="${LINE##* }"; if grep -q "${UNAME}" OWNERS; then X=''; else X='  (not in OWNERS)'; fi; echo "${LINE}${X}"; done
1     Approved by: edsantiago  (not in OWNERS)
2     Approved by: giuseppe  (not in OWNERS)
11     Approved by: umohnani8  (not in OWNERS)
15     Approved by: TomSweeneyRedHat  (not in OWNERS)
164     Approved by: baude
167     Approved by: mheon
341     Approved by: rhatdan
```

Should @TomSweeneyRedHat, @umohnani8, @giuseppe, and/or @edsantiago be added to `OWNERS`?

And these folks in `OWNERS` seem to have never approved a libpod commit, although they're all active in the larger community:

```console
$ sed -n 's/^  - //p' OWNERS | while read UNAME; do if ! grep -q "${UNAME}" <(echo "${APPROVERS}"); then echo "no approvals by ${UNAME}"; fi; done
no approvals by mrunalp
no approvals by runcom
no approvals by nalind
```

Should @mrunalp, @runcom, and/or @nalind be removed from `OWNERS`?

Are we really committed to `OWNERS`?  The Kubernetes Template Project [lists it as required][1], but I haven't been able to turn up a charter or anything (e.g. [here][2]) to back that up.  If the plan is to stick with `OWNERS`, do we want to use [Prow][3] or other tooling that actually reads `OWNERS` to determine approval powers?  That would probably help avoid future false negative (like @TomSweeneyRedHat not being listed), although it wouldn't help with apparent false positives (like @mrunalp being listed).

And things seem to be moving along smoothly despite these issues, so this is obviously not pressing.  I'm just filing the issue to help gradually bring our documented process in line with reality ;).

[1]: https://github.com/kubernetes/kubernetes-template-project/tree/1839f7a0f1c11138bde0d88cdc4dcc369348548a#kubernetes-template-project
[2]: https://github.com/kubernetes/community/blob/0a614ded6f114487dd78b5cec4329d19df8711d4/kubernetes-repositories.md
[3]: https://github.com/kubernetes/test-infra/tree/master/prow#prow

**Comment by rhatdan** [comment]
Perhaps we should look at this differently.  We have trusted reviewers.  We want to get two or more people to review each patch.  We should require rh-atomic-bot to merge all PRs since it makes sure that all tests pass and the heading does not have [WIP] in it.  Then have actual OWNERS who can hit the MERGE button, when @rh-atomic-bot is not working correctly.  Those would be @baude @mheon and Myself.

**Comment by wking** [comment]
> We have trusted reviewers... Then have actual OWNERS who can hit the MERGE button...

`OWNERS` [has][1] `reviewers` and `/lgtm` for the former and `approvers` and `/approve` for the latter.

> We should require rh-atomic-bot to merge all PRs since it makes sure that all tests pass and the heading does not have [WIP] in it.

Prow has a WIP plugin (kubernetes/test-infra#4145) and also supports similar use cases with [`/hold`][2].  It also has [`/test` and `/retest`][2] and [requires presibmit jobs to succeed before merging][3].  It also [supports Jenkins jobs][4].

I don't know what @rh-atomic-bot is running (it would be nice if https://github.com/rh-atomic-bot said), and retooling takes time, but I think it would be easier to keep our docs local if we do one of:

a. Change to prow  (via @k8s-ci-robot, something [self-hosted][5], or otherwise) to get real `OWNERS` consumption,
b. Teach @rh-atomic-bot to respect `OWNERS`, or
c. Replace `OWNERS` with whatever @rh-atomic-bot's currently-supported analog is.

In the short term, the easiest path is probably "manually bump `OWNERS` when someone notices that it's gone stale", but I think that will lead to lower quality data than the above approaches.  It probably comes down to how you balance up-front transition costs (favoring manual bumps) against long-term maintenance costs (favoring a or c?).

[1]: https://github.com/kubernetes/community/blob/0a614ded6f114487dd78b5cec4329d19df8711d4/contributors/guide/owners.md#owners
[2]: https://prow.k8s.io/command-help
[3]: https://github.com/kubernetes/community/blob/0a614ded6f114487dd78b5cec4329d19df8711d4/contributors/guide/owners.md#the-code-review-process
[4]: https://github.com/kubernetes/test-infra/blob/c93bc3c03350214e8975efd4121c17dec884b8be/prow/cmd/jenkins-operator/README.md
[5]: https://github.com/kubernetes/test-infra/blob/master/prow/getting_started.md

**Comment by rhatdan** [comment]
https://github.com/projectatomic/libpod/pull/894
