### ISSUE TITLE
podman run -m: unexpected cgroup readings

### ISSUE THREAD

**Issue by edsantiago** [projectatomic/libpod#826]
Disclaimer: I find this all confusing, and could easily be doing something wrong on my end.
```
# cid=$(podman run -d -m 8M fedora sleep 60)
# cat /sys/fs/cgroup/memory/libpod_parent/libpod-$cid/memory.limit_in_bytes 
9223372036854771712     <--- 0x7FFFFFFFFFFFF000, which is what I expect when not using -m)
```
Compare to docker:
```
# cid=$(docker run -d -m 8M fedora sleep 60)
# cat /sys/fs/cgroup/memory/system.slice/docker-$cid.scope/memory.limit_in_bytes                          
8388608    <--- 0x800000
```
I don't understand cgroups well enough to comment but I'll do so anyway: could this be related to the path element difference? (`libpod_parent` vs `system.slice`, and the missing `.scope`)?

podman-0.5.4-1527007540.git926d07d.fc27.x86_64 , which no longer has a `--cgroup-manager` option

With sincere apologies to @mheon

**Comment by rhatdan** [comment]
That looks like a bug to me.  @mheon has been doing a lot of work with cgroups so maybe this is fixed there.

**Comment by mheon** [comment]
@edsantiago I thibk this is because that's not actually the container's cgroup, but the parent cgroup for the container and conmon both. Try the `ctr/` subdirectory under `libpod-$cid`, which should have the actual container's cgroups (for reference, there is also a `conmon` subdirectory that has the conmon CGroup).

**Comment by edsantiago** [comment]
>Try the ctr/ subdirectory

That was it. Thank you, and sorry for the false alarm.

**Comment by edsantiago** [comment]
@mheon as of podman-0.7.1-1.git802d4f2.fc28 the `ctr/` subdirectory is gone, and podman is reporting `memory.limit_in_bytes` exactly the same as docker; iow the `cat` command in the initial report is now resulting in 8M. I assume this is part of the cgroups work you mentioned this morning. Can you confirm that this new behavior is intentional and desired?

**Comment by mheon** [comment]
@edsantiago Yes, that sounds right. Further alignment with docker is a fun side effect of that work I hadn't anticipated.
