### ISSUE TITLE
podman ps is not sorted by date

### ISSUE THREAD

**Issue by rhatdan** [projectatomic/libpod#830]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug

podman ps and podman ps -a should sort the list of containers to show the newest container at the top and the oldest at the bottom.
It should also show the date in a more human understandable format.

Probably need to similarly sort images.
>
> /kind feature

**Description**

**Steps to reproduce the issue:**

1.

2.

3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
Under the old SQLite data store, we could trivially make the guarantee that containers retrieved from the database were ordered by date with an `ORDER BY`. We did not preserve this guarantee when we moved to boltdb, for simplicity and performance. We should rewrite the output logic to do this ordering (the output logic really needs a rewrite anyways).
