### ISSUE TITLE
podman-build: improve error message for unqualified images

### ISSUE THREAD

**Issue by vrothberg** [projectatomic/libpod#838]
> /kind bug

**Description**

`podman-build` with a Dockerfile using an unqualified image yields the following error:
```
error creating build container: Get https://localhost/v2/: dial tcp [::1]:443: connect: connection refused
```

This is not very helpful to the user, and I have received complaints on openSUSE aiming to improve the situation. A more user-friendly error message could be to either use fully-qualified images or to put the desired regisry in the `/etc/containers/registries.conf` configuration.

**Comment by mheon** [comment]
@rhatdan This sounds like it might be from renaming images created locally to `localhost`?

**Comment by TomSweeneyRedHat** [comment]
@vrothberg do you by chance have a Dockerfle that you can share that reproduces this?

**Comment by vrothberg** [comment]
> @vrothberg do you by chance have a Dockerfle that you can share that reproduces this?

Sure, I my case I used:
```Dockerfile
FROM opensuse:tumbleweed
RUN  touch /foo
```

In this case, it's important that `docker.io` isn't mentioned in the search registries in the registries.conf.

**Comment by TomSweeneyRedHat** [comment]
@pixdrift can you take a peak at this one?  This is a bad error handling issue in Buildah where you've poked under the covers before.

**Comment by vrothberg** [comment]
Closing as it has already been fixed with https://github.com/projectatomic/libpod/pull/897
