### ISSUE TITLE
SELinux error running nginx:alpine image

### ISSUE THREAD

**Issue by mheon** [projectatomic/libpod#852]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**Description**

Running the `nginx:alpine` image in `podman run` produces an error if SELinux is enforcing

**Steps to reproduce the issue:**

1. `podman run nginx:alpine`

**Describe the results you received:**

`2018/05/30 17:55:13 [emerg] 1#1: open() "/var/log/nginx/error.log" failed (13: Permission denied)`

**Describe the results you expected:**

Podman run works without error

**Additional information you deem important (e.g. issue happens only occasionally):**

`setenforce 0` will cause the image to run successfully - the error only happens when SELinux is enforcing.

I checked the audit logs, but didn't find anything obviously wrong.

Tested on Podman master on Fedora 27.

**Comment by mheon** [comment]
@rhatdan PTAL - I'm seeing nothing in the audit logs, could be a do not audit rule?

**Comment by rhatdan** [comment]
I think this is fixed with the latest container-selinux.  Reopen if this is still an issue.
