### ISSUE TITLE
Detached containers leak network namespaces after deletion

### ISSUE THREAD

**Issue by mheon** [projectatomic/libpod#858]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**Description**

There are lingering network namespaces after a cycle of heavy podman use, and subsequently removing all containers (not necessarily all at once). As such, `podman rm` does not seem to reap network namespaces under all circumstances. It seems to be linked to detached containers.

**Steps to reproduce the issue:**

1. `podman run -d fedora sleep 5`

2. `podman rm -l`

**Describe the results you received:**

An instance `nsfs` present in `mount` after all Podman containers removed

**Describe the results you expected:**

No `nsfs` present after all Podman containers removed

**Additional information you deem important (e.g. issue happens only occasionally):**

Only happens on detached containers

**Comment by rhatdan** [comment]
@mheon Isn't this why we were looking at adding a post call to conmon to call a cleanup function?

**Comment by mheon** [comment]
@rhatdan `podman rm` should be removing them regardless - but it may well have something to do with that.

**Comment by rhatdan** [comment]
Does podman rm umount them if they are mounted?

**Comment by mheon** [comment]
It calls `cleanup()` which should unmount and remove the namespaces.

**Comment by wking** [comment]
Possibly related, in [the CI logs from another PR][1]:

```
/tmp/test_runner.output =====
time="2018-05-31T20:22:47Z" level=error msg="could not create new watcher too many open files" 
...a number of other "to many open files" errors...
time="2018-05-31T20:23:27Z" level=error msg="could not create new watcher too many open files" 
time="2018-05-31T20:23:37Z" level=error msg="Failed to tear down network namespace for container 41ddc9bfa634fce380b05615bddbc3adb7d765591334c7635290c13b9be9d7d2: cni config uninitialized" 
time="2018-05-31T20:23:47Z" level=error msg="Failed to tear down network namespace for container 8aee1d2ba0143b3c8aaa48b0545a78991a2b055499f42540ca162e148215ead9: cni config uninitialized" 
time="2018-05-31T20:23:47Z" level=error msg="Failed to tear down network namespace for container f32b49152a8caff2972a4315dbe544703f2a70d54dc715cc396dfc1b0109e3c2: cni config uninitialized" 
```

So maybe a CNI config issue?

[1]: https://s3.amazonaws.com/aos-ci/ghprb/projectatomic/libpod/a492f1d179071a6729406aa1d19a3d4eff0081e2.2.1527797417223330604/output.log

**Comment by giuseppe** [comment]
@rhatdan we already have that since https://github.com/kubernetes-incubator/cri-o/pull/1366

**Comment by rhatdan** [comment]
RIght but we need to plumb this into podman so that it uses it to cleanup on detatched containers.

**Comment by rhatdan** [comment]
Perhaps have a call like:
```
podman containers cleanup CID?
```

**Comment by mheon** [comment]
I've confirmed that even commands that should run `cleanup()` are not removing the network namespace (in this case, `podman stop` on a detached container).

**Comment by mheon** [comment]
Correction, `stop()` just calls `cleanupStorage()`. That needs to be fixed...

**Comment by mheon** [comment]
Confirmed that, even with a full cleanup, the network ns is still being left open. It looks like anything in a new process won't remove the network ns on `cleanup()`

**Comment by mheon** [comment]
Alright, I think I've located the offending code.

https://github.com/projectatomic/libpod/blob/master/vendor/github.com/containernetworking/plugins/pkg/ns/ns_linux.go#L127-L135

`ns.mounted` is only ever set when creating a new namespace, not opening an existing one. As such, when we open the namespace in a new process to clean it up, it will not execute this cleanup code.

**Comment by mheon** [comment]
The simplest way to deal with this is probably to fire the unmount and remove unconditionally and ignore EEXIST and the like

**Comment by mheon** [comment]
Opened #949 to fix
