### ISSUE TITLE
using --net=host broke from 0.5.4 to 0.6.1

### ISSUE THREAD

**Issue by nathwill** [projectatomic/libpod#861]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**Description**

upgrading from 0.5.4 to 0.6.1, using --net=host no longer causes the container to use the host network.

**Steps to reproduce the issue:**

1. run a container with --net=host

2. observe that a veth is created and bound ports are not bound on the host

**Describe the results you received:**

container does not run on host network 

**Describe the results you expected:**

container runs on host network when using `--net=host`

**Output of `podman version`:**

broken
```
Version:       0.6.1-dev
Go Version:    go1.9.4
OS/Arch:       linux/amd64
```

works
```
Version:       0.5.4-dev
Go Version:    go1.9.4
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  MemFree: 663461888
  MemTotal: 4143251456
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 2
  hostname: ws-mgr0.stage.wdc04.treehouse
  kernel: 4.4.130-1.el7.elrepo.x86_64
  os: linux
  uptime: 696h 19m 10.56s (Approximately 29.00 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.centos.org
  - registry.access.redhat.com
store:
  ContainerStore:
    number: 5
  GraphDriverName: overlay
  GraphOptions:
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 7
  RunRoot: /var/run/containers/storage```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

OpenStack

**Comment by nathwill** [comment]
looks like `--network=host` works, though? is this intentional?

**Comment by mheon** [comment]
`--net` should be an alias for `--network`, so this sounds like a bug

**Comment by rhatdan** [comment]
They are now aliases, Closing.

**Comment by nathwill** [comment]
just confirming that this did resolve the issue i reported. thanks @mheon for the quick fix!
