### ISSUE TITLE
oci-nvidia-hook  not working as expected with podman command

### ISSUE THREAD

**Issue by garyedwards** [projectatomic/libpod#884]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
 /kind bug
>
> /kind feature

**Description**

**Steps to reproduce the issue:**

1.
Set up the the hook as per the the Openshift guide: https://blog.openshift.com/use-gpus-with-device-plugin-in-openshift-3-9/

I have also tried the 1.0.0 Hook Schema Nvidia example documented in this repo for the oci-nvidia-hook.json file.

2.
Run the test container suggested in the Openshift guide with podman:

sudo podman run -it --rm docker.io/mirrorgooglecontainers/cuda-vector-add:v0.1

**Describe the results you received:**
None of the Nvidia or CUDA tools are mounted and the test fails:

Failed to allocate device vector A (error code CUDA driver version is insufficient for CUDA runtime version)!

**Describe the results you expected:**
For the vector-add test to pass as it does when using the fedora docker command.

**Additional information you deem important (e.g. issue happens only occasionally):**
A work around is to use the nvidia-container-runtime with the podman --runtime option but I would rather use the native runc with the Nvidia hook if possible.

**Output of `podman version`:**

```
Version:       0.6.1-dev
Go Version:    go1.10.2
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  MemFree: 181026816
  MemTotal: 8314044416
  SwapFree: 8455450624
  SwapTotal: 8455712768
  arch: amd64
  cpus: 8
  hostname: kfworkstation
  kernel: 4.16.12-200.fc27.x86_64
  os: linux
  uptime: 4h 29m 19.44s (Approximately 0.17 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
store:
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions:
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 13
  RunRoot: /var/run/containers/storage
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on physical hardware with Quadro 1000M.

**Comment by mheon** [comment]
@garyedwards Can you add a `--log-level=debug` to the `podman run` command you're using and pastebin the results?

I know hooks in general are working, so I suspect that the hook in question isn't being added. This likely comes down to a missing annotation which would be used to identify the container as requiring the nvidia hook.

**Comment by garyedwards** [comment]
@mheon see link to pastebin below as requested.  I have tried using the "when" "always" from the 1.0.0 Schema as well as annotations to force it to trigger, also with no success.  Any advice much appreciated.

https://pastebin.com/t9HABDKQ

**Comment by rhatdan** [comment]
What does the the file in /usr/share/containers/oci/hooks.d look like?

**Comment by garyedwards** [comment]
Hi @rhatdan, see the contents below:

    {
       "hook": "/usr/bin/nvidia-container-runtime-hook",
       "stage": [ "prestart" ]
    }

I have also tried the various versions from the man page in this repo.  The above works with the fedora docker command.

Docker version 1.13.1, build 19d432b-unsupported

**Comment by rhatdan** [comment]
You need to add an Annotations flag to your config and then add the Annotations to the container.
"annotations": {"useNvidia"}

And then run a container with tue UseNvidia annotation. Not fully sure of the syntax. @wking probably would no best.

**Comment by garyedwards** [comment]
Excellent so the follow works great as "sandbox" seems to be a default annotation.  Now will look into getting the buildah bud --annotation option adding annotations so that it does not run for every container.  Initial tests are not adding annotations visible in podman inspect command, but I will look deeper and open a ticket on buildah if it seems to be an issue.

Thanks both for your help!

    {
       "hook": "/usr/bin/nvidia-container-runtime-hook",
       "arguments": ["prestart"],
       "annotations": ["sandbox"],
       "stage": [ "prestart" ]
    }

**Comment by garyedwards** [comment]
Just a quick not on the annotations.  Buildah seems to add the annotations to the image which can be seen with a podman inspect agaist that image.

However but when podman creates a new container and that container is inspected the annotations are lost and only a load of default io.kubernetes.cri-o annotations are present.  I am not sure if this is the correct behaviour or if my image annotations should be carried over the the container?  Will keep digging.

**Comment by mheon** [comment]
@garyedwards I think that's a bug. Took a quick look at the code, and it doesn't we don't actually preserve the annotations when creating a container from an image. Can you make an issue about this to track it? Should be an easy fix on our end.

I wonder if it's also worth it to add a flag for modifying annotations of the created container.

**Comment by wking** [comment]
@garyedwards, I'm surprised the 1.0.0 hooks did not work.  You tried [this example][1]?  Which annotation key has the `sandbox` value?  And I'm really surprised it didn't fire when you set `always` `true`.

[1]: https://github.com/projectatomic/libpod/blame/master/pkg/hooks/docs/oci-hooks.5.md#L120-L136

**Comment by garyedwards** [comment]
Hi @wking, the 1.0.0 may well work now that I have got to the bottom of this a bit further.  I have just opened a second issue #885 relating to annotations not being carried across to containers.  This may have been making the 1.0.0 hooks appear not to work in my tests when in fact it was due to the annotation not being there.  I will test with the 1.0.0 syntax again shortly.  The sandbox key is below:

    "io.kubernetes.cri-o.ContainerType": "sandbox"

**Comment by wking** [comment]
So try:

```json
"when": {
  "annotations": {
    "^io\\.kubernetes\\.cri-o\\.ContainerType$": "^sandbox$"
  }
}
```

(looks like I need to double the backslashes in the docs).

But annotations not getting passed through doesn't explain why:

```json
"when": {
  "always": true
}
```

didn't work for you earlier.

**Comment by garyedwards** [comment]
I have tried the following two versions both of which result in the command hanging.  The third 0.1.0 style works as expected.  See pastebin for the debug log from 1.0.0 syntax:  https://pastebin.com/xkFqP9Js

    {
      "hook": {
        "path": "/usr/bin/nvidia-container-runtime-hook",
        "args": ["nvidia-container-runtime-hook", "prestart"]
      },
      "when": {
        "annotations": {
          "^io\\.kubernetes\\.cri-o\\.ContainerType$": "^sandbox$"
        }
      },
      "stages": ["prestart"]
    }

    {
      "hook": {
        "path": "/usr/bin/nvidia-container-runtime-hook",
        "args": ["nvidia-container-runtime-hook", "prestart"]
      },
      "when": {
        "always": true
      },
      "stages": ["prestart"]
    }

Working 0.1.0 version:

    {
       "hook": "/usr/bin/nvidia-container-runtime-hook",
       "arguments": ["prestart"],
       "annotations": ["sandbox"],
       "stage": [ "prestart" ]
    }

**Comment by wking** [comment]
```
time="2018-06-03T16:32:17+01:00" level=warning msg="failed to parse language "en_GB.UTF-8": language: tag is not well-formed" 
```

That is golang/go#25340, but you should be getting our [POSIX fallback][1].  Both of those are followed by "Cleaning up container" messages, so I don't see anything obvious going wrong (but no evidence of them going right either).

[1]: https://github.com/projectatomic/libpod/blob/v0.6.1/libpod/container_internal.go#L1342

**Comment by garyedwards** [comment]
You see the clean up as I Ctrl+c the process.  For comparison see the pasebin from the successful 0.1.0 hook.  As you both point out there does not seem to be much information relating to what is going on with the hooks in the log.

https://pastebin.com/DMvxpdZa

**Comment by garyedwards** [comment]
The reason for the hanging seemed to be the omission of the version information:

    {
      "version": "1.0.0",
      "hook": {
        "path": "/usr/bin/nvidia-container-runtime-hook",
        "args": ["nvidia-container-runtime-hook", "prestart"]
      },
      "when": {
        "always": true
      },
      "stages": ["prestart"]
    }

The command now runs but the hook does not seem to be triggered as non of the Nvidia tools are mounted.

**Comment by wking** [comment]
> The reason for the hanging seemed to be the omission of the version information:

I've filed #887 to fix that in the example (and fix a few other things as well).  But with the missing `version` we should be failing to unmarshal the JSON using the 0.1.0 structure.  For example:

```console
$ cat /tmp/hook.json 
{
  "hook": {
    "path": "/bin/sh",
    "args": ["nvidia-container-runtime-hook", "prestart"],
    "env": [
      "NVIDIA_REQUIRE_CUDA=cuda>=9.1",
      "NVIDIA_VISIBLE_DEVICES=GPU-fef8089b"
    ]
  },
  "when": {
    "annotations": {
      "^com\\.example\\.department$": ".*fluid-dynamics$"
    }
  },
  "stages": ["prestart"]
}
$ git describe 
v0.6.1
$ cat test.go 
package main

import (
        "context"
        "fmt"
        "os"
        rspec "github.com/opencontainers/runtime-spec/specs-go"
        "github.com/projectatomic/libpod/pkg/hooks"
        _ "github.com/projectatomic/libpod/pkg/hooks/0.1.0"
        "github.com/sirupsen/logrus"
        "golang.org/x/text/language"
)

func die(err error) {
        fmt.Printf("%v\n", err)
        os.Exit(1)
}

func main() {
        ctx := context.Background()

        logrus.SetLevel(logrus.DebugLevel)

        lang, err := language.Parse("und-u-va-posix")
        if err != nil {
                die(err)
        }

        manager, err := hooks.New(ctx, []string{"/tmp"}, []string{}, lang)
        if err != nil {
                die(err)
        }

        config := &rspec.Spec{}
        _, err = manager.Hooks(config, map[string]string{
                "com.example.department": "fluid-dynamics",
        }, false)
        if err != nil {
                die(err)
        }

        fmt.Printf("%v\n", config)
}
$ go run test.go 
parsing hook "/tmp/hook.json": : json: cannot unmarshal object into Go struct field Hook.hook of type string
exit status 1
```

**Comment by wking** [comment]
@garyedwards, with #887 landed in master and its better logging, can you take another pass at the `always` and `annotations` 1.0.0 forms.  I doubt the `always` behavior has changed, but the debug logging may help us understand why the hooks are not getting injected.

**Comment by rhatdan** [comment]
Rawhide is automatically built daily from anything that we checked in that day.  So most likely this is already in rawhide.  Will be in the weekly build by tomorrow.
