### ISSUE TITLE
annotations not carried over from images to containers when created with podman

### ISSUE THREAD

**Issue by garyedwards** [projectatomic/libpod#885]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
>
> /kind feature

**Description**

**Steps to reproduce the issue:**

1. Build an image with buildah including annotations

2. Use podman to create a container form that image

3. Use podman inspect to check the container annotations

**Describe the results you received:**
Only the default io.kubernetes.cri-o.* annotations are present and not the custom ones set in the image.

**Describe the results you expected:**
My custom annotations to be concatenated or replace the default ones and be carried across from the image to container.

**Additional information you deem important (e.g. issue happens only occasionally):**
Without bring the annotations across there does not seem to be a way of setting container annotations required for triggering hooks etc.

**Output of `podman version`:**

```
Version:       0.6.1-dev
Go Version:    go1.10.2
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
Version:       0.6.1-dev
Go Version:    go1.10.2
OS/Arch:       linux/amd64
[gary@kfworkstation cuda-vector-add]$ sudo podman info
host:
  MemFree: 450596864
  MemTotal: 8314048512
  SwapFree: 8450207744
  SwapTotal: 8455712768
  arch: amd64
  cpus: 8
  hostname: kfworkstation
  kernel: 4.16.12-200.fc27.x86_64
  os: linux
  uptime: 4h 5m 41.88s (Approximately 0.17 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
store:
  ContainerStore:
    number: 20
  GraphDriverName: overlay
  GraphOptions:
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 25
  RunRoot: /var/run/containers/storage

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by garyedwards** [comment]
@mheon suggested adding a flag for modifying annotations of the created container.  I think would be a good idea so that ones does not have to create derivative images every time they want to add an annotation to a container for triggering a hook for example.

**Comment by wking** [comment]
Is this closable now that #886 has landed, or do we need additional work to support adding container annotations beyond those specified in the backing image?

**Comment by mheon** [comment]
I think we should be set... Closing
