### ISSUE TITLE
Issue with getting method response as expected from varlink api

### ISSUE THREAD

**Issue by praveenkumar** [projectatomic/libpod#889]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**Description**

Not able to get each parameter value from the method response.

**Steps to reproduce the issue:**

1. $ podman varlink tcp::12345 --timeout 0

2. Copy following go code (as gopodman) which use varlink connection to connect with api.

```golang
package main

import (
	"fmt"

	"github.com/varlink/go/varlink"
)

func main() {
	type versionOutput struct {
		Built     int    `json:"built"`
		GitCommit string `json:"git_commit"`
		GoVersion string `json:"go_version"`
		OsArch    string `json:"os_arch"`
		Version   string `json:"version"`
	}

	var outResponse versionOutput

	type pingOutput struct {
		Message string `json:"message"`
	}

	var pingResponse pingOutput

	conn, err := varlink.NewConnection("tcp:10.70.48.27:8443")
	if err != nil {
		fmt.Printf("Varlink connection error: %v", err)
	}

	err = conn.Call("io.projectatomic.podman.GetVersion", nil, &outResponse)
	if err != nil {
		fmt.Printf("Not able to Call: %v", err)
	}

	fmt.Printf("Response : %#v\n", outResponse)

	err = conn.Call("io.projectatomic.podman.Ping", nil, &pingResponse)
	if err != nil {
		fmt.Printf("Not able to Call: %v", err)
	}

	fmt.Printf("Response : %#v", pingResponse)
}
```

```
$ go run gopodman.go
Response : main.versionOutput{Built:0, GitCommit:"", GoVersion:"", OsArch:"", Version:""}
Response : main.pingOutput{Message:""}
```

**Describe the results you received:**
Got an empty response from the podman varlink api.

**Describe the results you expected:**
Should be able to get a proper response like in case of ping it should be `Response : main.pingOutput{Message:"OK"}`

**Output of `podman version`:**
```
$ podman version
Version:       0.6.1
Go Version:    go1.10.2
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  MemFree: 1622609920
  MemTotal: 16818241536
  SwapFree: 8458059776
  SwapTotal: 8459907072
  arch: amd64
  cpus: 8
  hostname: foo
  kernel: 4.16.11-300.fc28.x86_64
  os: linux
  uptime: 168h 23m 12.2s (Approximately 7.00 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
store:
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions:
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 1
  RunRoot: /var/run/containers/storage
```

**Comment by vrothberg** [comment]
In order to make it work you need to use the interfaces defined in podman. An example use can be found here: https://github.com/projectatomic/libpod/blob/master/cmd/podman/varlink.go#L7

For other examples, you can `git grep ioprojectatomicpodman`. A quick-fix for your example would be to use the generic `interface{}` type instead of the structs, for instance:
```golang
var reply interface{}
err = conn.Call("io.projectatomic.podman.Ping", nil, &p)
if err != nil { ... }
fmt.Printf("Reply: %#v\n", p)
```

**Comment by TomSweeneyRedHat** [comment]
if by chance @vrothberg 's example is not in a tutorial, we ought to get it there.

**Comment by baude** [comment]
I assumed people who wanted to interact with podman via go would vendor in libpod ... I had not envisioned a go varlink tutorial.  @vrothberg is right on how to use it though and the varlink stuff is behaving.  Marking as closed.  Re-open if you would like to discuss.

**Comment by rhatdan** [comment]
@baude having a couple of go examples using it would not be a bad idea.
