### ISSUE TITLE
Add --sort parameter to ps and images commands

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [projectatomic/libpod#898]
> /kind feature

**Description**

Add a --sort parameter to the `podman ps` and `podman images` commands such that you could sort the output by the variable passed in to the sort.    Currently the default sort is by created time, it would be nice to be able to sort by at least container or image name respectively.

**Comment by haircommander** [comment]
Any other parameters that would be useful to sort @TomSweeneyRedHat ? Once one option is implemented it should be fairly easy to do any others.

**Comment by rhatdan** [comment]
Name, Size, and Date are the three obvious ones, but I think any field is fine.

**Comment by TomSweeneyRedHat** [comment]
+1 @rhatdan's thinking.  I think if you can specify the field in the format param, you should be able to sort on it.  As an FYI, they're listed on the ps man page.  For this pass I'd only worry about doing a one-way sort, i.e. Sort by name, not a Sort by name, then secondary sort by date, then final sort by size type of thing.

**Comment by rhatdan** [comment]
@haircommander fix it for images first.

**Comment by haircommander** [comment]
closed because #948 and #937 merge
