### ISSUE TITLE
Undeferred Unlock

### ISSUE THREAD

**Issue by haircommander** [projectatomic/libpod#907]
https://github.com/projectatomic/libpod/blob/7965bf54048044d63f967d2b4ce8efe1e1072f05/libpod/pod.go#L81

This line seems as though the unlocking should be deferred. Would there be any reason to grab a lock and immediately release it?

**Comment by rhatdan** [comment]
@mheon PTAL

**Comment by rhatdan** [comment]
Yes this should be a defer

**Comment by rhatdan** [comment]
Open A PR TO fix.
