### ISSUE TITLE
command arguments to `podman run` are ignored if image has entrypoint defined

### ISSUE THREAD

**Issue by miabbott** [projectatomic/libpod#912]
/kind bug

**Description**

Arguments passed to a container with an entrypoint defined are ignored when using `podman run`

**Steps to reproduce the issue:**

1.  Build a simple container via `buildah` with an entrypoint defined
2.  Run container with `podman run <args>`

**Describe the results you received:**

Arguments passed to the container are ignored.

**Describe the results you expected:**

Arguments passed to the container are passed along to the entrypoint.

**Additional information you deem important (e.g. issue happens only occasionally):**

Bash script used to build container:

```bash
$ cat buildah.sh
#!/bin/bash
set -xeou pipefail
 
# create base container
ctr=$(buildah from registry.fedoraproject.org/fedora:28)
 
# mount container filesystem
mp=$(buildah mount $ctr)
 
# configure the container
buildah config --author "Micah Abbott <miabbott@redhat.com>" --entrypoint /usr/bin/curl $ctr
 
# commit the image
buildah commit $ctr miabbott/curl
 
# unmount and remove the container
buildah unmount $ctr
buildah rm $ctr
```

Example `podman run` with no args and various args:

```
$ sudo podman run --rm -it localhost/miabbott/curl                                                                                                                           
curl: try 'curl --help' or 'curl --manual' for more information
 
$ sudo podman run --rm -it localhost/miabbott/curl --help
curl: try 'curl --help' or 'curl --manual' for more information
 
$ sudo podman run --rm -it localhost/miabbott/curl -I https://google.com
curl: try 'curl --help' or 'curl --manual' for more information 

$ sudo podman run --rm -it localhost/miabbott/curl https://google.com
curl: try 'curl --help' or 'curl --manual' for more information 
```

Strangely, if I explicitly configure the entrypoint to the same binary when using `podman run`, the arguments are respected:

```
$ sudo podman run --rm -it --entrypoint /usr/bin/curl localhost/miabbott/curl -I https://google.com
HTTP/2 301 
location: https://www.google.com/
content-type: text/html; charset=UTF-8
date: Wed, 06 Jun 2018 15:53:47 GMT
expires: Fri, 06 Jul 2018 15:53:47 GMT
cache-control: public, max-age=2592000
server: gws
content-length: 220
x-xss-protection: 1; mode=block
x-frame-options: SAMEORIGIN
alt-svc: quic=":443"; ma=2592000; v="43,42,41,39,35"
```

**Output of `podman version`:**

```
$ podman version
Version:       0.5.4
Go Version:    go1.10.2
OS/Arch:       linux/amd64
```

```
$ sudo podman info
[sudo] password for miabbott: 
host:
  MemFree: 1140948992
  MemTotal: 16692690944
  SwapFree: 2148003840
  SwapTotal: 2149576704
  arch: amd64
  cpus: 4
  hostname: mastershake
  kernel: 4.16.12-300.fc28.x86_64
  os: linux
  uptime: 25h 17m 45.03s (Approximately 1.04 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
store:
  ContainerStore:
    number: 128
  GraphDriverName: overlay
  GraphOptions:
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 36
  RunRoot: /var/run/containers/storage
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Using Fedora 28 Atomic Workstation

**Comment by miabbott** [comment]
@baude said he wanted this one

**Comment by miabbott** [comment]
@TomSweeneyRedHat suggested I try `buildah run`, but that wasn't successful either:

```
$ sudo buildah images | grep curl
650cd04d7368         localhost/miabbott/curl:latest                           Jun 6, 2018 10:27      263 MB
$ sudo buildah from 650cd04d7368
curl-working-container-2
$ sudo buildah run curl-working-container-2
command must be specified
```

**Comment by miabbott** [comment]
I think this is related to the different ways a user can define the ENTRYPOINT in a container image.  The [Dockerfile reference](https://docs.docker.com/engine/reference/builder/#entrypoint) describes the two variants of the ENTRYPOINT:  exec form and shell form.

If I build a similar container with a Dockerfile that uses the shell form of the ENTRYPOINT, I hit the same error:

```
# cat Dockerfile
FROM registry.fedoraproject.org/fedora:28
ENTRYPOINT "/usr/bin/curl"

$ sudo /usr/bin/docker build -t miabbott/curl .
Sending build context to Docker daemon 2.048 kB        
Step 1/2 : FROM registry.fedoraproject.org/fedora:28
Trying to pull repository registry.fedoraproject.org/fedora ...
sha256:39994db8f1ee63244dc6baa35cd88988eb4be8ac6c026be0570bd618fd84d5af: Pulling from registry.fedoraproject.org/fedora
bd02462c6d09: Pull complete          
Digest: sha256:39994db8f1ee63244dc6baa35cd88988eb4be8ac6c026be0570bd618fd84d5af
Status: Downloaded newer image for registry.fedoraproject.org/fedora:28
 ---> 75aeb7f897fd                                  
Step 2/2 : ENTRYPOINT "/usr/bin/curl"
 ---> Running in 75145f84ad79              
 ---> 9a6284ea1c94                                                                                                                                                                                                
Removing intermediate container 75145f84ad79                                                                                                                                                                      
Successfully built 9a6284ea1c94                          

$ sudo /usr/bin/docker run -it miabbott/curl -I https://github.com
curl: try 'curl --help' or 'curl --manual' for more information                                      
$ sudo /usr/bin/docker run -it miabbott/curl https://github.com                
curl: try 'curl --help' or 'curl --manual' for more information                       
```

However, If I change the ENTRYPOINT to the exec form, the container runs successfully:

```
$ cat Dockerfile
FROM registry.fedoraproject.org/fedora:28
ENTRYPOINT ["/usr/bin/curl"]

$ sudo /usr/bin/docker build -t miabbott/curl .
Sending build context to Docker daemon 3.072 kB
Step 1/2 : FROM registry.fedoraproject.org/fedora:28
 ---> 75aeb7f897fd
Step 2/2 : ENTRYPOINT /usr/bin/curl
 ---> Using cache
 ---> e7350d34e242
Successfully built e7350d34e242

$ sudo /usr/bin/docker run --rm -it miabbott/curl -I https://github.com
HTTP/1.1 200 OK
Server: GitHub.com
Date: Wed, 06 Jun 2018 17:46:33 GMT
Content-Type: text/html; charset=utf-8
Status: 200 OK
Cache-Control: no-cache
Vary: X-PJAX
Set-Cookie: logged_in=no; domain=.github.com; path=/; expires=Sun, 06 Jun 2038 17:46:33 -0000; secure; HttpOnly
Set-Cookie: _gh_sess=YlN3RWpqZHlrSGlDNCtUT2oySHhKMndyd1hZS3hJREJ6NGRuNVJHeldvdjhsaXVHZytScStIclEwQVRPQ2lFTEVNWVU3WDhKNDhMRlR3MzVUeXE5eWwwMjN3Q1NHSGNCalNOUDZac2xnNmNmRGhLNzRnYVZib1NldlNVNnFqOVFkalZIRzFuOG1yYW1PWDZ5dFhWclIraWQ2T3VpYkl5Yld3SkIwaGVqVGEwL3hndDI4RThYaXZRR0hialRJNjBqLS1DWjUrRkVFdXBlMmJKNk1XdEMveU1BPT0%3D--8fa64bb390baf2a8b171ffd51a2dc24c35b546f8; path=/; secure; HttpOnly
X-Request-Id: 67f621e8-a9fd-4ba8-bb60-18e943c44342
X-Runtime: 0.054836
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Expect-CT: max-age=2592000, report-uri="https://api.github.com/_private/browser/errors"
Content-Security-Policy: default-src 'none'; base-uri 'self'; block-all-mixed-content; connect-src 'self' uploads.github.com status.github.com collector.githubapp.com api.github.com www.google-analytics.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com wss://live.github.com; font-src assets-cdn.github.com; form-action 'self' github.com gist.github.com; frame-ancestors 'none'; frame-src render.githubusercontent.com; img-src 'self' data: assets-cdn.github.com identicons.github.com collector.githubapp.com github-cloud.s3.amazonaws.com *.githubusercontent.com; manifest-src 'self'; media-src 'none'; script-src assets-cdn.github.com; style-src 'unsafe-inline' assets-cdn.github.com
X-Runtime-rack: 0.064622
X-GitHub-Request-Id: EA6E:7CF6:1AAEFDF:31530C4:5B181DF8
```

The trouble is, I'm not sure how to specify the exec form of the ENTRYPOINT with `buildah`

I tried the following:

` buildah config --entrypoint ["/usr/bin/curl"] $ctr`
` buildah config --entrypoint '["/usr/bin/curl"]' $ctr`

But the container fails like so when run with `podman`:

```
$ sudo podman run --rm -it localhost/miabbott/curl -I https://github.com
-I: [/usr/bin/curl]: No such file or directory
$ sudo podman run --rm -it localhost/miabbott/curl
/bin/sh: [/usr/bin/curl]: No such file or directory
```

**Comment by rhatdan** [comment]
We have a recent PR to allow the specification of the '["/usr/bin/curl"]' $ctr

https://github.com/projectatomic/buildah/pull/736

**Comment by mheon** [comment]
I consider this more of a `buildah` issue than Podman - we're handling the entrypoint correctly, the issue was with the entrypoint being set in the image. As such, I think we can close this. @rhatdan agree?

**Comment by rhatdan** [comment]
Yes.

**Comment by coppercash** [comment]
> I think this is related to the different ways a user can define the ENTRYPOINT in a container image. The [Dockerfile reference](https://docs.docker.com/engine/reference/builder/#entrypoint) describes the two variants of the ENTRYPOINT: exec form and shell form.
> 
> If I build a similar container with a Dockerfile that uses the shell form of the ENTRYPOINT, I hit the same error:
> 
> ```
> # cat Dockerfile
> FROM registry.fedoraproject.org/fedora:28
> ENTRYPOINT "/usr/bin/curl"
> 
> $ sudo /usr/bin/docker build -t miabbott/curl .
> Sending build context to Docker daemon 2.048 kB        
> Step 1/2 : FROM registry.fedoraproject.org/fedora:28
> Trying to pull repository registry.fedoraproject.org/fedora ...
> sha256:39994db8f1ee63244dc6baa35cd88988eb4be8ac6c026be0570bd618fd84d5af: Pulling from registry.fedoraproject.org/fedora
> bd02462c6d09: Pull complete          
> Digest: sha256:39994db8f1ee63244dc6baa35cd88988eb4be8ac6c026be0570bd618fd84d5af
> Status: Downloaded newer image for registry.fedoraproject.org/fedora:28
>  ---> 75aeb7f897fd                                  
> Step 2/2 : ENTRYPOINT "/usr/bin/curl"
>  ---> Running in 75145f84ad79              
>  ---> 9a6284ea1c94                                                                                                                                                                                                
> Removing intermediate container 75145f84ad79                                                                                                                                                                      
> Successfully built 9a6284ea1c94                          
> 
> $ sudo /usr/bin/docker run -it miabbott/curl -I https://github.com
> curl: try 'curl --help' or 'curl --manual' for more information                                      
> $ sudo /usr/bin/docker run -it miabbott/curl https://github.com                
> curl: try 'curl --help' or 'curl --manual' for more information                       
> ```
> 
> However, If I change the ENTRYPOINT to the exec form, the container runs successfully:
> 
> ```
> $ cat Dockerfile
> FROM registry.fedoraproject.org/fedora:28
> ENTRYPOINT ["/usr/bin/curl"]
> 
> $ sudo /usr/bin/docker build -t miabbott/curl .
> Sending build context to Docker daemon 3.072 kB
> Step 1/2 : FROM registry.fedoraproject.org/fedora:28
>  ---> 75aeb7f897fd
> Step 2/2 : ENTRYPOINT /usr/bin/curl
>  ---> Using cache
>  ---> e7350d34e242
> Successfully built e7350d34e242
> 
> $ sudo /usr/bin/docker run --rm -it miabbott/curl -I https://github.com
> HTTP/1.1 200 OK
> Server: GitHub.com
> Date: Wed, 06 Jun 2018 17:46:33 GMT
> Content-Type: text/html; charset=utf-8
> Status: 200 OK
> Cache-Control: no-cache
> Vary: X-PJAX
> Set-Cookie: logged_in=no; domain=.github.com; path=/; expires=Sun, 06 Jun 2038 17:46:33 -0000; secure; HttpOnly
> Set-Cookie: _gh_sess=YlN3RWpqZHlrSGlDNCtUT2oySHhKMndyd1hZS3hJREJ6NGRuNVJHeldvdjhsaXVHZytScStIclEwQVRPQ2lFTEVNWVU3WDhKNDhMRlR3MzVUeXE5eWwwMjN3Q1NHSGNCalNOUDZac2xnNmNmRGhLNzRnYVZib1NldlNVNnFqOVFkalZIRzFuOG1yYW1PWDZ5dFhWclIraWQ2T3VpYkl5Yld3SkIwaGVqVGEwL3hndDI4RThYaXZRR0hialRJNjBqLS1DWjUrRkVFdXBlMmJKNk1XdEMveU1BPT0%3D--8fa64bb390baf2a8b171ffd51a2dc24c35b546f8; path=/; secure; HttpOnly
> X-Request-Id: 67f621e8-a9fd-4ba8-bb60-18e943c44342
> X-Runtime: 0.054836
> Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
> X-Frame-Options: deny
> X-Content-Type-Options: nosniff
> X-XSS-Protection: 1; mode=block
> Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
> Expect-CT: max-age=2592000, report-uri="https://api.github.com/_private/browser/errors"
> Content-Security-Policy: default-src 'none'; base-uri 'self'; block-all-mixed-content; connect-src 'self' uploads.github.com status.github.com collector.githubapp.com api.github.com www.google-analytics.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com wss://live.github.com; font-src assets-cdn.github.com; form-action 'self' github.com gist.github.com; frame-ancestors 'none'; frame-src render.githubusercontent.com; img-src 'self' data: assets-cdn.github.com identicons.github.com collector.githubapp.com github-cloud.s3.amazonaws.com *.githubusercontent.com; manifest-src 'self'; media-src 'none'; script-src assets-cdn.github.com; style-src 'unsafe-inline' assets-cdn.github.com
> X-Runtime-rack: 0.064622
> X-GitHub-Request-Id: EA6E:7CF6:1AAEFDF:31530C4:5B181DF8
> ```
> 
> The trouble is, I'm not sure how to specify the exec form of the ENTRYPOINT with `buildah`
> 
> I tried the following:
> 
> ` buildah config --entrypoint ["/usr/bin/curl"] $ctr` ` buildah config --entrypoint '["/usr/bin/curl"]' $ctr`
> 
> But the container fails like so when run with `podman`:
> 
> ```
> $ sudo podman run --rm -it localhost/miabbott/curl -I https://github.com
> -I: [/usr/bin/curl]: No such file or directory
> $ sudo podman run --rm -it localhost/miabbott/curl
> /bin/sh: [/usr/bin/curl]: No such file or directory
> ```

I have suffered from this for a long time, until I find your found.

**Comment by rhatdan** [comment]
Please open an new issue if this is not fixed in current Podman/Buildah.
