### ISSUE TITLE
[obscure] podman run --rm --cgroup-parent ... : iptables EPERM

### ISSUE THREAD

**Issue by edsantiago** [projectatomic/libpod#923]
Scratching my head over this one:
```
# podman --cgroup-manager=systemd run --rm --cgroup-parent=a.slice fedora date
Thu Jun  7 20:33:32 UTC 2018
ERRO[0000] `iptables -t filter -D FORWARD -s 10.88.0.241 ! -o 10.88.0.241 -j ACCEPT` failed:   (fork/exec /usr/sbin/iptables: permission denied) 
# echo $?
0
```
Repeating the command (e.g. `!!`) results in good output, no warnings. To reproduce, change the cgroup name (e.g. `aa.slice`, `aaa.slice`, etc) or:
```
# rmdir /sys/fs/cgroup/systemd/a.slice
```
The `--rm` seems important; I can't seem to reproduce using just `podman run` and subsequent `podman rm`.

podman-0.6.2-1528392993.gitcf7c829.fc28.x86_64

**Comment by rhatdan** [comment]
This is an SELinux issue/race condition.  I have a fix for it, should be fixed in tomorrows release.

**Comment by rhatdan** [comment]
https://github.com/projectatomic/libpod/pull/906

**Comment by mheon** [comment]
With #906 merged is this fixed?

**Comment by edsantiago** [comment]
Unable to reproduce with podman-0.6.2-10.git72c0b4f.fc28

**Comment by edsantiago** [comment]
Seeing this again, but inconsistently (fails one out of 3-4 runs), on podman-0.6.3-1.gitcd39b62.fc28

Can someone with privs please reopen?

**Comment by TomSweeneyRedHat** [comment]
FWIW, I ran into this once today during two baseline test runs.  I shrugged it off as a network hiccup, perhaps too quickly.

**Comment by rhatdan** [comment]
Ok I looked into this, and it is caused by a bad selinux library.
https://github.com/opencontainers/selinux/pull/29

**Comment by rhatdan** [comment]
Closing again since this has been vendored. Hopefully it is fully fixed.
