### ISSUE TITLE
podman-run: improve "name already in use" error message

### ISSUE THREAD

**Issue by vrothberg** [projectatomic/libpod#956]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind feature

**Description**

podman-run's error message when setting a name that's already being used by another container could be more verbose to guide less seasoned users in the right direction (e.g., chosing another name or removing the other container). It would also be helpful to actually print the name (easier to read logs).

Currently, the output looks as follow:
``` bash
$ podman run --name foo alpine echo "foo" > /dev/null
$ podman run --name foo alpine echo "foo" > /dev/null
error creating container storage: that name is already in use
```

**Describe the results you received:**

`error creating container storage: that name is already in use`

**Describe the results you expected:**

A more Docker-ish kind of output, e.g.:
`docker: Error response from daemon: Conflict. The container name "/foo" is already in use by container "c6c908895cb656718e15d5313a8e94fc3743e5ed3aa7ceb16ff0c865e8bc6f5c". You have to remove (or rename) that container to be able to reuse that name.`

**Comment by vrothberg** [comment]
@rhatdan, I had a look at the code and I think that this is something affecting more error cases (see https://github.com/containers/storage/blob/master/errors.go). I think that all conflict scenarios could be improved to print the source of the conflict (not only the fact), such as "name XYZ already in use by containers/image ABC" etc. I suggest opening an issue for containers/storage instead and use this one as a tracker?

**Comment by rhatdan** [comment]
SGTM

**Comment by mheon** [comment]
We can also handle most basic cases ourselves by adding a check for pods and containers with the same name before https://github.com/projectatomic/libpod/blob/master/libpod/runtime_ctr.go#L108 - right now, if you don't manually specify a name, we will ensure one without conflict is found, but manually specifying will cause you to hit c/storage and get an error back from them. Checking ourselves will let us control the error message.

**Comment by vrothberg** [comment]
@mheon I think `containers/storage` is the best place to do all that. I guess your proposal is orthogonal to that, but I can imagine running into race conditions.

**Comment by mheon** [comment]
@vrothberg True. Least racy place to do it would be c/storage.

**Comment by vrothberg** [comment]
I opened an issue for containers/storage (see https://github.com/containers/storage/issues/189). I suggest keeping the one here open until we can re-vendor improved error message from containers/storage.

**Comment by rhatdan** [comment]
Closing sine it has been vendored.
