### ISSUE TITLE
podman top: %CPU column is now labeled 'C'

### ISSUE THREAD

**Issue by edsantiago** [projectatomic/libpod#994]
```
# podman run --name foo -d fedora sleep
3e33e2fe93d2c54638711719bed4a16ccf77f95374fff66a59a7e39a60ff7786
# podman top foo
UID                 PID                 PPID                C [...]
root                2536                2525                0 [...]
```
(some columns truncated for readability). The last column shown should be `%CPU`, not `C`. This may be related to b1e7098 but I can't figure out how.

podman-0.6.4-1.gitd5beb2f.fc28

**Comment by edsantiago** [comment]
@vrothberg would you mind taking a look and seeing if this is a side effect of your recent PR? TIA.

**Comment by vrothberg** [comment]
@edsantiago you are right, that comes exactly from commit b1e7098. I agree that a `CPU` would be nicer, but the commit aimed to be compatible with Docker, which is running a `ps -ef` yielding this output. As we wanted to be compatible with Docker, I don't consider this to be an issue.

**Comment by rhatdan** [comment]
Does docker chop off the last two letters?

**Comment by vrothberg** [comment]
@rhatdan, yes it does (see the verbatime copy below):

``` bash
# docker run --rm -d alpine sleep 100
7baa017015734da8c8c1e3d301211d83ddd1e22b5145e09f45e2c19861873c0c
# docker top 7baa
UID                 PID                 PPID                C                   STIME               TTY                 TIME                CMD
root                10229               10210               1                   15:56               ?                   00:00:00            sleep 100
```

**Comment by rhatdan** [comment]
Yuck but that is our goal.  @edsantiago If you think we should reverse this, we can change it versus Docker.

**Comment by edsantiago** [comment]
Thanks; it looks like this is a bug in docker, too, but I see no reason to file it. The root cause of the test failure I see is that `podman top` ignores `-waux`. Filed #1006.
