### ISSUE TITLE
podman ps: hangs while rm --force in progress, then chokes

### ISSUE THREAD

**Issue by edsantiago** [projectatomic/libpod#995]
`podman rm --force` of a running container blocks for a while (expected). What I don't expect is, if I run `podman ps` while the `rm` is in progress, to have `ps` blow up on me:
```
# podman run -d -i --name foo1 fedora /bin/bash                                                                           
5224255e7c66b103551fbe9c7bf64caad974576ec62195a6a93409fb9c8c6d41
# podman run -d -i --name foo2 fedora /bin/bash                                                                           
201ae33ce987871c4bf6856e0ccb75253947781f7dbebe0bcd98c74ed31f7979
```
In a separate window, run `podman ps -a`, confirm that containers are running. Back to the original window:
```
# podman rm --force foo1
```
Then, quickly (before the 10-second timeout) go back to the other window and run ps:
```
# podman ps -a  (hangs a few seconds until the rm finishes)
container 5224255e7c66b103551fbe9c7bf64caad974576ec62195a6a93409fb9c8c6d41 does not exist in database: no such container
# echo $?
125
```
5224 is the ID of the killed `foo1` container. Note that the other running container is not shown. Rerunning `ps` immediately afterward shows `foo2` running.

podman-0.6.4-1.gitd5beb2f.fc28

**Comment by mheon** [comment]
I don't think we can avoid this. Maybe some sort of parallel generation for ps to avoid the locked container as long as possible, but we cannot unlock the container while kill is waiting (someone else could get in and change the state further), so we basically have to hang until the container finishes stopping and unlocks.

**Comment by rhatdan** [comment]
I think the failure is fine, the problem here is the failure is fatal.  I have another PR to make these failures not fatal.  Just report the missing container and continue.

**Comment by edsantiago** [comment]
I agree with @rhatdan. I don't mind the delay, and can live with the scary error message, but aborting without showing other containers is surprising.

**Comment by mheon** [comment]
@rhatdan If you're talking about https://github.com/projectatomic/libpod/pull/918 that is a separate issue - `ps` just needs to handle ErrNoSuchCtr gracefully here

**Comment by vrothberg** [comment]
This issue seems to be fixed in the meanwhile, so we can close it.
