### ISSUE TITLE
Regression: podman push: 500 Internal Server Error

### ISSUE THREAD

**Issue by edsantiago** [projectatomic/libpod#997]
I'm not sure if this is podman or if it's the registry image or phase of the moon.

Setup:
```
# d=$(mktemp -d);cd $d
# podman run --rm --entrypoint htpasswd registry-1.docker.io/distribution/registry:2.1 -Bbn testuser testpass >htpasswd                                                                                                                                   
# openssl req -newkey rsa:4096 -nodes -sha256 -keyout domain.key -x509 -days 2 -out domain.crt -subj "/C=US/ST=Foo/L=Bar/O=Red Hat, Inc./CN=localhost.localdomain"
...
# podman run -d -p 5000:5000 -v $d:/auth:Z -e REGISTRY_HTTP_TLS_CERTIFICATE=/auth/domain.crt -e REGISTRY_HTTP_TLS_KEY=/auth/domain.key -e REGISTRY_AUTH=htpasswd -e REGISTRY_AUTH_HTPASSWD_REALM="Registry Realm" -e REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd registry-1.docker.io/distribution/registry:2.1
39b5b73f7de3353158355be9babf94a1300e3f4a38fae1eeaba0827880d32a50
# podman login --username testuser --password testpass --tls-verify=false --authfile /root/.podman-auth.json localhost.localdomain:5000                                                             
Login Succeeded!
# podman pull busybox
# podman tag busybox localhost.localdomain:5000/push_ok:tag_ok
```
Phew. Now try to push:
```
# podman push --tls-verify=false --authfile /root/.podman-auth.json localhost.localdomain:5000/push_ok:tag_ok
Getting image source signatures
Copying blob sha256:432b65032b9466b4dadcc5c7b11701e71d21c18400aae946b101ad16be62333a
 8 B / 1.30 MB [>-----------------------------------------------------------] 0s
Error copying image to the remote destination: Error writing blob: Error initiating layer upload to /v2/push_ok/blobs/uploads/ in localhost.localdomain:5000: received unexpected HTTP status: 500 Internal Server Error
# echo $?
125
```
podman-0.6.4-1.gitd5beb2f.fc28. The above was working until this build.

**Comment by edsantiago** [comment]
Logs are copious and hard to analyze, but this looks suspicious:
```
time="2018-06-25T22:01:41.711261392Z" level=error msg="response completed with error" auth.user.name=testuser environment=development err.code=UNKNOWN err.detail="mkdir /var/lib/registry/docker: permission denied" err.message="unknown error" http.request.host="localhost.localdomain:5000" http.request.id=8e1af8bf-c9e0-4935-b571-a19554e1cfca http.request.method=POST http.request.remoteaddr="10.88.0.1:40900" http.request.uri="/v2/push_ok/blobs/uploads/" http.request.useragent="Go-http-client/1.1" http.response.contenttype="application/json; charset=utf-8" http.response.duration=6.314709ms http.response.status=500 http.response.written=125 instance.id=c3d35fda-4277-4db1-99b0-5b16a293c934 service=registry vars.name="push_ok" version=v2.1.1
```

**Comment by wking** [comment]
>     ...mkdir /var/lib/registry/docker: permission denied...

I haven't looked at the backend code, but I'm surprised that a `podman push ...` run as root (as suggested by your `#` prompt in the initial comment) would be getting permission-denied errors.  I guess that error is from your registry's logs?  If so, seems like it's an issue with your registry (or that registry's configuration), and not a podman issue.

**Comment by edsantiago** [comment]
I've just double-confirmed that all tests pass in podman-0.6.3-1.gitcd39b62.fc28. The following command produces no output.
```
# podman logs fe65 | grep perm
```

**Comment by mheon** [comment]
I don't think we touched any of that code this release, so I'm going to
blame infra flakes that went away?

**Comment by edsantiago** [comment]
Well, except that it continues to fail on 0.6.4-1.gitd5beb2f.fc28. Downgrade to 0.6.3 -> success; re-upgrade to 0.6.4 -> fail.

**Comment by mheon** [comment]
Oh, huh, I misread that as 0.6.5 and thought we fixed in our latest
release... Hm. Alright, so something actually broke. Probably a
containers/image bug then, given our push code hasn't seen a significant
change in months.

**Comment by edsantiago** [comment]
Is there a 0.6.5? I looked this morning and haven't seen one on bodhi.

**Comment by wking** [comment]
> Well, except that it continues to fail on 0.6.4-1.gitd5beb2f.fc28. Downgrade to 0.6.3 -> success; re-upgrade to 0.6.4 -> fail.

If it's alway reproducible, you may be able to track it down to a breaking commit with `git bisect ...`.

**Comment by mheon** [comment]
It's tagged, but the release went in so late on Friday I doubt that the
build is available yet.

**Comment by edsantiago** [comment]
@mheon I'm not convinced that the problem is in `push`: if I upgrade to 0.6.4 and try `push` against the currently-running (0.6.3) registry, it passes. If I do a 0.6.4 setup, leave the registry running, downgrade to 0.6.3, and `push`, it fails. To me this implies that the problem is in the version of podman that is running the registry container.

@wking my setup is for testing built images; I don't have an easy way to build podman myself. Not an insurmountable problem, but one I'd rather not spend time on unless absolutely necessary.

**Comment by edsantiago** [comment]
Unable to reproduce in podman-0.6.5-1.git9d97bd6.fc28 but I'm reluctant to close this without some understanding of what happened.
